-- ***************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Automotive EDW Demo by heather.ready+yew@sqldbm.com *


-- ************************************** "CORE"."DIM_VEHICLE"
CREATE OR REPLACE TABLE "CORE"."DIM_VEHICLE"
(
 "VEHICLE_SK"        number,
 "VEHICLE_NK"        varchar,
 "MAKE"              varchar,
 "MODEL"             varchar,
 "TRIM"              varchar,
 "MODEL_YEAR"        number(4),
 "BODY_STYLE"        varchar,
 "DRIVETRAIN"        varchar,
 "FUEL_TYPE"         varchar,
 "TRANSMISSION"      varchar,
 "DOORS"             number,
 "CREATED_TS"        timestamp_tz DEFAULT CURRENT_TIMESTAMP(),
 "UPDATED_TS"        timestamp_tz,
 "EFFECTIVE_FROM_TS" timestamp_tz,
 "EFFECTIVE_TO_TS"   timestamp_tz,
 "IS_CURRENT"        boolean
);

-- ************************************** "CORE"."DIM_LOCATION"
CREATE OR REPLACE TABLE "CORE"."DIM_LOCATION"
(
 "LOCATION_SK"       number,
 "LOCATION_NK"       varchar,
 "COUNTRY"           varchar,
 "STATE_PROVINCE"    varchar,
 "CITY"              varchar,
 "POSTAL_CODE"       varchar,
 "LATITUDE"          number(9,6),
 "LONGITUDE"         number(9,6),
 "MARKET_AREA"       varchar,
 "CREATED_TS"        timestamp_tz DEFAULT CURRENT_TIMESTAMP(),
 "UPDATED_TS"        timestamp_tz,
 "EFFECTIVE_FROM_TS" timestamp_tz,
 "EFFECTIVE_TO_TS"   timestamp_tz,
 "IS_CURRENT"        boolean
);

-- ************************************** "CORE"."DIM_DEALER"
CREATE OR REPLACE TABLE "CORE"."DIM_DEALER"
(
 "DEALER_SK"         number NOT NULL,
 "DEALER_NK"         varchar,
 "DEALER_NAME"       varchar,
 "DEALER_TIER"       varchar,
 "PHONE"             varchar,
 "EMAIL"             varchar,
 "WEBSITE_URL"       varchar,
 "CREATED_TS"        timestamp_tz DEFAULT CURRENT_TIMESTAMP(),
 "UPDATED_TS"        timestamp_tz,
 "EFFECTIVE_FROM_TS" timestamp_tz,
 "EFFECTIVE_TO_TS"   timestamp_tz,
 "IS_CURRENT"        boolean,

 CONSTRAINT "PK_1" PRIMARY KEY ( "DEALER_SK" )
);

-- ************************************** "CORE"."FACT_AD_METRICS"
CREATE OR REPLACE TABLE "CORE"."FACT_AD_METRICS"
(
 "EVENT_TS"    timestamp_tz,
 "CAMPAIGN_ID" varchar,
 "DEALER_SK"   number,
 "LISTING_SK"  number,
 "IMPRESSIONS" number,
 "CLICKS"      number,
 "SPEND_USD"   number(12,2)
);

-- ************************************** "CORE"."DIM_LISTING"
CREATE OR REPLACE TABLE "CORE"."DIM_LISTING"
(
 "LISTING_SK"        number,
 "LISTING_NK"        varchar,
 "VEHICLE_SK"        number,
 "DEALER_SK"         number,
 "LOCATION_SK"       number,
 "LISTING_STATUS"    varchar,
 "MILEAGE"           number,
 "ASKING_PRICE"      number(12,2),
 "PRICE_CURRENCY"    varchar(3),
 "CPO_FLAG"          boolean,
 "CREATED_TS"        timestamp_tz DEFAULT CURRENT_TIMESTAMP(),
 "UPDATED_TS"        timestamp_tz,
 "EFFECTIVE_FROM_TS" timestamp_tz,
 "EFFECTIVE_TO_TS"   timestamp_tz,
 "IS_CURRENT"        boolean
);

