-- ************************************ SqlDBM: Snowflake ***********************************
-- * Generated by SqlDBM: Jira Project - Sample , v18 vs v8 by heather.ready+yew@sqldbm.com *

ALTER TABLE fact_sales
    ADD COLUMN emp_key NOT NULL;

CREATE TABLE dim_employee
(
 emp_key  NOT NULL,
 fname   string NOT NULL COMMENT 'Example Description.',
 lname   string NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( emp_key )
);

CREATE TABLE table_8
(

);

CREATE TABLE table_9
(

);

ALTER TABLE fact_sales
    ADD CONSTRAINT FK_6 FOREIGN KEY ( emp_key ) REFERENCES dim_employee ( emp_key );