-- ****************************************** SqlDBM: Databricks *****************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer , v53 vs v17 by heather.ready+yew@sqldbm.com *

ALTER TABLE veh_dm.dim_model
DROP CONSTRAINT FK_11;
ALTER TABLE veh_dm.fact_inventory_snapshot
DROP CONSTRAINT FK_20;
ALTER TABLE veh_dm.fact_purchase_order
DROP CONSTRAINT FK_12;
ALTER TABLE veh_dm.fact_purchase_order
DROP CONSTRAINT FK_25;
ALTER TABLE veh_dm.fact_purchase_order
DROP CONSTRAINT FK_26;
ALTER TABLE veh_dm.fact_sales_order
DROP CONSTRAINT FK_8;
ALTER TABLE veh_dm.fact_sales_order
DROP CONSTRAINT FK_17;
ALTER TABLE veh_dm.fact_sales_order
DROP CONSTRAINT FK_19;
ALTER TABLE veh_dm.fact_service_event
DROP CONSTRAINT FK_3;
ALTER TABLE veh_dm.fact_service_event
DROP CONSTRAINT FK_13;
ALTER TABLE veh_dm.fact_service_event
DROP CONSTRAINT FK_18;
ALTER TABLE veh_dm.fact_service_event
DROP CONSTRAINT FK_23;
ALTER TABLE veh_dm.fact_shipment
DROP CONSTRAINT FK_14;
ALTER TABLE veh_dm.fact_shipment
DROP CONSTRAINT FK_21;
ALTER TABLE veh_dm.fact_shipment
DROP CONSTRAINT FK_24;
ALTER TABLE veh_dm.fact_vehicle_telemetry
DROP CONSTRAINT FK_1;
ALTER TABLE veh_dm.fact_vehicle_telemetry
DROP CONSTRAINT FK_2;
ALTER TABLE veh_dm.fact_warranty_claim
DROP CONSTRAINT FK_6;
ALTER TABLE veh_dm.fact_warranty_claim
DROP CONSTRAINT FK_9;
ALTER TABLE veh_dm.fact_warranty_claim
DROP CONSTRAINT FK_22;
ALTER TABLE veh_dm.fact_work_order
DROP CONSTRAINT FK_4;
ALTER TABLE veh_dm.fact_work_order
DROP CONSTRAINT FK_16;
DROP TABLE veh_dm.fact_operation_exec;
DROP TABLE veh_dm.dim_operation;
ALTER TABLE veh_dm.dim_contract
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.dim_contract
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_contract
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.dim_contract
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_contract
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.dim_contract
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.dim_customer
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.dim_customer
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_customer
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.dim_customer
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_customer
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.dim_customer
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.dim_date
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.dim_date
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_date
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.dim_date
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_date
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.dim_date
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.dim_event_type
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.dim_event_type
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_event_type
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.dim_event_type
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_event_type
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.dim_event_type
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.dim_failure
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.dim_failure
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_failure
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.dim_failure
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_failure
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.dim_failure
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.dim_model
  ADD COLUMNS (
    dw_created_ts      timestamp COMMENT 'When the record was first created',
    created_by         varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts         timestamp COMMENT 'When the record was last updated.',
    updated_by         varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted         boolean COMMENT 'Logical deletion flag.',
    forecast_type_hkey binary);
ALTER TABLE veh_dm.dim_model
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_model
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.dim_model
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_model
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.dim_model
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.dim_model
ALTER COLUMN forecast_type_hkey SET NOT NULL;
ALTER TABLE veh_dm.dim_part
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.dim_part
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_part
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.dim_part
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_part
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.dim_part
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.dim_plant
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.dim_plant
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_plant
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.dim_plant
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_plant
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.dim_plant
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.dim_platform
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.dim_platform
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_platform
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.dim_platform
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_platform
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.dim_platform
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.dim_platform
ALTER COLUMN platform_sk SET NOT NULL;
ALTER TABLE veh_dm.dim_supplier
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.dim_supplier
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_supplier
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.dim_supplier
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_supplier
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.dim_supplier
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.dim_time
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.dim_time
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_time
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.dim_time
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_time
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.dim_time
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.dim_vehicle
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.dim_vehicle
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_vehicle
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.dim_vehicle
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.dim_vehicle
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.dim_vehicle
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.fact_inventory_snapshot
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.fact_inventory_snapshot
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.fact_inventory_snapshot
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.fact_inventory_snapshot
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.fact_inventory_snapshot
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.fact_inventory_snapshot
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.fact_purchase_order
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.fact_purchase_order
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.fact_purchase_order
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.fact_purchase_order
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.fact_purchase_order
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.fact_purchase_order
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.fact_sales_order
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.fact_sales_order
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.fact_sales_order
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.fact_sales_order
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.fact_sales_order
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.fact_sales_order
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.fact_service_event
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.fact_service_event
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.fact_service_event
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.fact_service_event
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.fact_service_event
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.fact_service_event
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.fact_shipment
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.fact_shipment
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.fact_shipment
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.fact_shipment
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.fact_shipment
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.fact_shipment
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.fact_vehicle_telemetry
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.fact_vehicle_telemetry
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.fact_vehicle_telemetry
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.fact_vehicle_telemetry
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.fact_vehicle_telemetry
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.fact_vehicle_telemetry
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.fact_warranty_claim
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.fact_warranty_claim
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.fact_warranty_claim
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.fact_warranty_claim
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.fact_warranty_claim
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.fact_warranty_claim
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.fact_work_order
  ADD COLUMNS (
    dw_created_ts timestamp COMMENT 'When the record was first created',
    created_by    varchar(50) COMMENT 'Process or user that created the record.',
    updated_ts    timestamp COMMENT 'When the record was last updated.',
    updated_by    varchar(50) COMMENT 'Process or user that modified the record.',
    is_deleted    boolean COMMENT 'Logical deletion flag.');
ALTER TABLE veh_dm.fact_work_order
ALTER COLUMN dw_created_ts SET NOT NULL;
ALTER TABLE veh_dm.fact_work_order
ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE veh_dm.fact_work_order
ALTER COLUMN updated_ts SET NOT NULL;
ALTER TABLE veh_dm.fact_work_order
ALTER COLUMN updated_by SET NOT NULL;
ALTER TABLE veh_dm.fact_work_order
ALTER COLUMN is_deleted SET NOT NULL;
ALTER TABLE veh_dm.dim_business_unit
DROP CONSTRAINT PK_7;
ALTER TABLE veh_dm.dim_business_unit
ADD CONSTRAINT pk_dim_business_unit PRIMARY KEY (bu_sk);
ALTER TABLE veh_dm.dim_contract
DROP CONSTRAINT PK_8;
ALTER TABLE veh_dm.dim_contract
ADD CONSTRAINT pk_dim_contract PRIMARY KEY (contract_sk);
ALTER TABLE veh_dm.dim_customer
DROP CONSTRAINT PK_13;
ALTER TABLE veh_dm.dim_customer
ADD CONSTRAINT pk_dim_customer PRIMARY KEY (customer_sk);
ALTER TABLE veh_dm.dim_date
DROP CONSTRAINT PK_19;
ALTER TABLE veh_dm.dim_date
ADD CONSTRAINT pk_dim_date PRIMARY KEY (date_key);
ALTER TABLE veh_dm.dim_event_type
DROP CONSTRAINT PK_5;
ALTER TABLE veh_dm.dim_event_type
ADD CONSTRAINT pk_dim_event_type PRIMARY KEY (event_type_sk);
ALTER TABLE veh_dm.dim_failure
DROP CONSTRAINT PK_16;
ALTER TABLE veh_dm.dim_failure
ADD CONSTRAINT pk_dim_failure PRIMARY KEY (failure_sk);
ALTER TABLE veh_dm.dim_model
DROP CONSTRAINT PK_3;
ALTER TABLE veh_dm.dim_model
ADD CONSTRAINT pk_dim_model PRIMARY KEY (model_sk);
ALTER TABLE veh_dm.dim_part
DROP CONSTRAINT PK_15;
ALTER TABLE veh_dm.dim_part
ADD CONSTRAINT pk_dim_part PRIMARY KEY (part_sk);
ALTER TABLE veh_dm.dim_plant
DROP CONSTRAINT PK_21;
ALTER TABLE veh_dm.dim_plant
ADD CONSTRAINT pk_dim_plant PRIMARY KEY (plant_sk);
ALTER TABLE veh_dm.dim_platform
ADD CONSTRAINT pk_dim_platform PRIMARY KEY (platform_sk);
ALTER TABLE veh_dm.dim_supplier
DROP CONSTRAINT PK_10;
ALTER TABLE veh_dm.dim_supplier
ADD CONSTRAINT pk_dim_supplier PRIMARY KEY (supplier_sk);
ALTER TABLE veh_dm.dim_time
DROP CONSTRAINT PK_18;
ALTER TABLE veh_dm.dim_time
ADD CONSTRAINT pk_dim_time PRIMARY KEY (time_key);
ALTER TABLE veh_dm.dim_vehicle
DROP CONSTRAINT PK_1;
ALTER TABLE veh_dm.dim_vehicle
ADD CONSTRAINT pk_dim_vehicle PRIMARY KEY (vehicle_sk);
ALTER TABLE veh_dm.fact_inventory_snapshot
DROP CONSTRAINT PK_20;
ALTER TABLE veh_dm.fact_inventory_snapshot
ADD CONSTRAINT pk_fact_inventory_snapshot PRIMARY KEY (inv_snap_sk);
ALTER TABLE veh_dm.fact_purchase_order
DROP CONSTRAINT PK_22;
ALTER TABLE veh_dm.fact_purchase_order
ADD CONSTRAINT pk_fact_purchase_order PRIMARY KEY (po_line_sk);
ALTER TABLE veh_dm.fact_sales_order
DROP CONSTRAINT PK_12;
ALTER TABLE veh_dm.fact_sales_order
ADD CONSTRAINT pk_fact_sales_order PRIMARY KEY (so_line_sk);
ALTER TABLE veh_dm.fact_service_event
DROP CONSTRAINT PK_4;
ALTER TABLE veh_dm.fact_service_event
ADD CONSTRAINT pk_fact_service_event PRIMARY KEY (service_sk);
ALTER TABLE veh_dm.fact_shipment
DROP CONSTRAINT PK_14;
ALTER TABLE veh_dm.fact_shipment
ADD CONSTRAINT pk_fact_shipment PRIMARY KEY (shipment_sk);
ALTER TABLE veh_dm.fact_vehicle_telemetry
DROP CONSTRAINT PK_2;
ALTER TABLE veh_dm.fact_vehicle_telemetry
ADD CONSTRAINT pk_fact_vehicle_telemetry PRIMARY KEY (veh_telem_sk);
ALTER TABLE veh_dm.fact_warranty_claim
DROP CONSTRAINT PK_11;
ALTER TABLE veh_dm.fact_warranty_claim
ADD CONSTRAINT pk_fact_warranty_claim PRIMARY KEY (claim_sk);
ALTER TABLE veh_dm.fact_work_order
DROP CONSTRAINT PK_6;
ALTER TABLE veh_dm.fact_work_order
ADD CONSTRAINT pk_fact_work_order PRIMARY KEY (wo_sk);
CREATE TABLE veh_dm.dim_op
(
 op_sk         bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for operation' CONSTRAINT pk_dim_op PRIMARY KEY,
 op_code       string COMMENT 'Unique operation identifier',
 op_name       string COMMENT 'Descriptive name of the operation',
 work_center   string COMMENT 'Manufacturing work center associated with operation',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Manufacturing operations for routings.';
CREATE TABLE veh_dm.fact_op_exec
(
 op_exec_sk    bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for operation execution' CONSTRAINT pk_fact_op_exec PRIMARY KEY,
 work_order_id string COMMENT 'Identifier for work order',
 date_key      int COMMENT 'Date of operation execution',
 op_sk         bigint COMMENT 'Reference to specific operation' CONSTRAINT fk_fact_op_exec_dim_op REFERENCES veh_dm.dim_op,
 plant_sk      bigint COMMENT 'Reference to manufacturing plant',
 model_sk      bigint COMMENT 'Reference to product model' CONSTRAINT fk_fact_op_exec_dim_model REFERENCES veh_dm.dim_model,
 labor_minutes decimal(18, 2) COMMENT 'Labor time spent on operation',
 yield_qty     decimal(18, 2) COMMENT 'Quantity of successful units produced',
 scrap_qty     decimal(18, 2) COMMENT 'Quantity of units scrapped during operation',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Executed operations for throughput/FPY.';
ALTER TABLE veh_dm.dim_model
ADD CONSTRAINT fk_dim_model_dim_platform FOREIGN KEY (platform_sk) REFERENCES veh_dm.dim_platform (platform_sk);
ALTER TABLE veh_dm.dim_model
ADD CONSTRAINT fk_dim_model_dim_forecast_type FOREIGN KEY (forecast_type_hkey) REFERENCES sales_infomart.dim_forecast_type (forecast_type_hkey);
ALTER TABLE veh_dm.fact_inventory_snapshot
ADD CONSTRAINT fk_fact_inventory_snapshot_dim_plant FOREIGN KEY (plant_sk) REFERENCES veh_dm.dim_plant (plant_sk);
ALTER TABLE veh_dm.fact_purchase_order
ADD CONSTRAINT fk_fact_purchase_order_dim_supplier FOREIGN KEY (supplier_sk) REFERENCES veh_dm.dim_supplier (supplier_sk);
ALTER TABLE veh_dm.fact_purchase_order
ADD CONSTRAINT fk_fact_purchase_order_dim_plant FOREIGN KEY (plant_sk) REFERENCES veh_dm.dim_plant (plant_sk);
ALTER TABLE veh_dm.fact_purchase_order
ADD CONSTRAINT fk_fact_purchase_order_dim_part FOREIGN KEY (part_sk) REFERENCES veh_dm.dim_part (part_sk);
ALTER TABLE veh_dm.fact_sales_order
ADD CONSTRAINT fk_fact_sales_order_dim_contract FOREIGN KEY (contract_sk) REFERENCES veh_dm.dim_contract (contract_sk);
ALTER TABLE veh_dm.fact_sales_order
ADD CONSTRAINT fk_fact_sales_order_dim_model FOREIGN KEY (model_sk) REFERENCES veh_dm.dim_model (model_sk);
ALTER TABLE veh_dm.fact_sales_order
ADD CONSTRAINT fk_fact_sales_order_dim_customer FOREIGN KEY (customer_sk) REFERENCES veh_dm.dim_customer (customer_sk);
ALTER TABLE veh_dm.fact_service_event
ADD CONSTRAINT fk_fact_service_event_dim_event_type FOREIGN KEY (event_type_sk) REFERENCES veh_dm.dim_event_type (event_type_sk);
ALTER TABLE veh_dm.fact_service_event
ADD CONSTRAINT fk_fact_service_event_dim_model FOREIGN KEY (model_sk) REFERENCES veh_dm.dim_model (model_sk);
ALTER TABLE veh_dm.fact_service_event
ADD CONSTRAINT fk_fact_service_event_dim_vehicle FOREIGN KEY (vehicle_sk) REFERENCES veh_dm.dim_vehicle (vehicle_sk);
ALTER TABLE veh_dm.fact_service_event
ADD CONSTRAINT fk_fact_service_event_dim_customer FOREIGN KEY (customer_sk) REFERENCES veh_dm.dim_customer (customer_sk);
ALTER TABLE veh_dm.fact_shipment
ADD CONSTRAINT fk_fact_shipment_dim_model FOREIGN KEY (model_sk) REFERENCES veh_dm.dim_model (model_sk);
ALTER TABLE veh_dm.fact_shipment
ADD CONSTRAINT fk_fact_shipment_dim_plant FOREIGN KEY (plant_sk) REFERENCES veh_dm.dim_plant (plant_sk);
ALTER TABLE veh_dm.fact_shipment
ADD CONSTRAINT fk_fact_shipment_dim_customer FOREIGN KEY (customer_sk) REFERENCES veh_dm.dim_customer (customer_sk);
ALTER TABLE veh_dm.fact_vehicle_telemetry
ADD CONSTRAINT fk_fact_vehicle_telemetry_dim_vehicle FOREIGN KEY (vehicle_sk) REFERENCES veh_dm.dim_vehicle (vehicle_sk);
ALTER TABLE veh_dm.fact_vehicle_telemetry
ADD CONSTRAINT fk_fact_vehicle_telemetry_dim_model FOREIGN KEY (model_sk) REFERENCES veh_dm.dim_model (model_sk);
ALTER TABLE veh_dm.fact_warranty_claim
ADD CONSTRAINT fk_fact_warranty_claim_dim_model FOREIGN KEY (model_sk) REFERENCES veh_dm.dim_model (model_sk);
ALTER TABLE veh_dm.fact_warranty_claim
ADD CONSTRAINT fk_fact_warranty_claim_dim_failure FOREIGN KEY (failure_sk) REFERENCES veh_dm.dim_failure (failure_sk);
ALTER TABLE veh_dm.fact_warranty_claim
ADD CONSTRAINT fk_fact_warranty_claim_dim_vehicle FOREIGN KEY (vehicle_sk) REFERENCES veh_dm.dim_vehicle (vehicle_sk);
ALTER TABLE veh_dm.fact_work_order
ADD CONSTRAINT fk_fact_work_order_dim_model FOREIGN KEY (model_sk) REFERENCES veh_dm.dim_model (model_sk);
ALTER TABLE veh_dm.fact_work_order
ADD CONSTRAINT fk_fact_work_order_dim_plant FOREIGN KEY (plant_sk) REFERENCES veh_dm.dim_plant (plant_sk);