-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- **************************************  SUPPLYCHAIN.PII
CREATE TAG SUPPLYCHAIN.PII ALLOWED_VALUES 'NO', 'YES';
