-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- **************************************  SUPPLYCHAIN.RETENTION_PERIOD
CREATE TAG SUPPLYCHAIN.RETENTION_PERIOD ALLOWED_VALUES '7 YEARS';
