-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- **************************************  SUPPLYCHAIN.DATA_OWNER
CREATE TAG SUPPLYCHAIN.DATA_OWNER ALLOWED_VALUES 'SUPPLYCHAINTEAM';
