-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dynamic Tables Snowflake by heather.ready+yew@sqldbm.com *

-- ************************************** GOLD.FACT_SALES_DT
CREATE DYNAMIC TABLE GOLD.FACT_SALES_DT
(
 SALES_SK,
 CUSTOMER_SK,
 PRODUCT_SK,
 STORE_SK,
 SALES_REP_SK,
 DATE_SK,
 SALES_AMOUNT,
 SALES_TIMESTAMP,
 LOAD_TIMESTAMP
)
WAREHOUSE = COMPUTE_WH
TARGET_LAG = '5 MINUTES'
INITIALIZE = ON_CREATE
REFRESH_MODE = AUTO
  AS SELECT
    rs.sales_id AS sales_sk,
    dc.customer_sk,
    dp.product_sk,
    ds.store_sk,
    dr.sales_rep_sk,
    dd.date_sk,
    rs.sales_amount,
    rs.sales_timestamp,
    CURRENT_TIMESTAMP() AS load_timestamp
FROM silver_sales rs
LEFT JOIN dim_customer dc
ON rs.customer_id = dc.customer_id
AND rs.sales_timestamp::date BETWEEN dc.eff_start_date AND dc.eff_end_date
LEFT JOIN dim_product dp
ON rs.product_id = dp.product_id
AND rs.sales_timestamp::date BETWEEN dp.eff_start_date AND dp.eff_end_date
LEFT JOIN dim_store ds
ON rs.store_id = ds.store_id
AND rs.sales_timestamp::date BETWEEN ds.eff_start_date AND ds.eff_end_date
LEFT JOIN dim_sales_rep dr
ON rs.sales_rep_id = dr.sales_rep_id
AND rs.sales_timestamp::date BETWEEN dr.eff_start_date AND dr.eff_end_date
LEFT JOIN dim_date dd
ON DATE(rs.sales_timestamp) = dd.date_value;
