-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dynamic Tables Snowflake by heather.ready+yew@sqldbm.com *

-- ************************************** PUBLIC.DT_ORDERS
CREATE DYNAMIC TABLE PUBLIC.DT_ORDERS
(
 ORDER_ID,
 CUS_ID,
 ORDER_AMOUNT,
 ORDER_TIMESTAMP,
 LOAD_TIMESTAMP
)
WAREHOUSE = COMPUTE_WH
TARGET_LAG = '5 MINUTES'
INITIALIZE = ON_CREATE
REFRESH_MODE = AUTO
  AS SELECT
    order_id,
    customer_id,
    order_amount,
    order_timestamp,
    CURRENT_TIMESTAMP() AS load_timestamp
FROM raw_orders;
