-- ******************************************* SqlDBM: Databricks ******************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer- , v58 vs PROD by heather.ready+yew@sqldbm.com *

DROP TABLE fact_vehicle_telemetry;
DROP TABLE fact_service_event;
DROP TABLE fact_work_order;
DROP TABLE fact_warranty_claim;
DROP TABLE fact_shipment;
DROP TABLE fact_sales_order;
DROP TABLE fact_purchase_order;
DROP TABLE fact_operation_exec;
DROP TABLE fact_inventory_snapshot;
DROP TABLE dim_vehicle;
DROP TABLE dim_time;
DROP TABLE dim_supplier;
DROP TABLE dim_platform;
DROP TABLE dim_plant;
DROP TABLE dim_part;
DROP TABLE dim_operation;
DROP TABLE dim_model;
DROP TABLE dim_failure;
DROP TABLE dim_event_type;
DROP TABLE dim_date;
DROP TABLE dim_customer;
DROP TABLE dim_contract;
DROP TABLE dim_business_unit;
CREATE SCHEMA veh_dm;
CREATE TABLE table_24
(
 pk_test    NOT NULL,
 pk_test_1  NOT NULL,
 CONSTRAINT pk_table_24 PRIMARY KEY (pk_test, pk_test_1)
)
 TBLPROPERTIES (delta.columnMapping.mode = 'name');
CREATE TABLE veh_dm.dim_time
(
 time_key      int NOT NULL COMMENT 'Unique time identifier' CONSTRAINT pk_dim_time PRIMARY KEY,
 hour          int COMMENT 'Hour of the day',
 minute        int COMMENT 'Minute within the hour',
 second        int COMMENT 'Second within the minute',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Time-of-day dimension (optional, for telemetry/service).';
CREATE TABLE veh_dm.dim_supplier
(
 supplier_sk   bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for supplier' CONSTRAINT pk_dim_supplier PRIMARY KEY,
 supplier_code string COMMENT 'Unique supplier identifier',
 supplier_name string COMMENT 'Full name of supplier',
 country       string COMMENT 'Country of supplier origin',
 is_preferred  boolean COMMENT 'Indicates if supplier is preferred vendor',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Suppliers for direct/indirect materials.';
CREATE TABLE veh_dm.dim_platform
(
 platform_sk     bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for platform' CONSTRAINT pk_dim_platform PRIMARY KEY,
 platform_code   string COMMENT 'Unique platform identifier',
 platform_name   string COMMENT 'Descriptive name of platform',
 lifecycle_stage string COMMENT 'Current stage in platform lifecycle',
 bu_sk           bigint COMMENT 'Reference to business unit',
 dw_created_ts   timestamp NOT NULL COMMENT 'When the record was first created',
 created_by      varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts      timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by      varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted      boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Vehicle/equipment platform family.';
CREATE TABLE veh_dm.dim_part
(
 part_sk       bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for part' CONSTRAINT pk_dim_part PRIMARY KEY,
 part_number   string COMMENT 'Unique part identifier',
 part_desc     string COMMENT 'Detailed description of part',
 uom           string COMMENT 'Unit of measurement',
 part_type     string COMMENT 'Classification of part type',
 is_serialized boolean COMMENT 'Indicates if part is tracked by serial number',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Parts and assemblies (includes finished goods).';
CREATE TABLE veh_dm.dim_op
(
 op_sk         bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for operation' CONSTRAINT pk_dim_op PRIMARY KEY,
 op_code       string COMMENT 'Unique operation identifier',
 op_name       string COMMENT 'Descriptive name of the operation',
 work_center   string COMMENT 'Manufacturing work center associated with operation',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Manufacturing operations for routings.';
CREATE TABLE veh_dm.dim_failure
(
 failure_sk    bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for failure mode' CONSTRAINT pk_dim_failure PRIMARY KEY,
 failure_code  string COMMENT 'Standardized failure identification code',
 failure_desc  string COMMENT 'Detailed description of failure mode',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Optional: normalize warranty/service failure codes.';
CREATE TABLE veh_dm.dim_event_type
(
 event_type_sk bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for event type' CONSTRAINT pk_dim_event_type PRIMARY KEY,
 event_type    string COMMENT 'Description of event type',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Optional: normalize service/maintenance event types.';
CREATE TABLE veh_dm.dim_date
(
 date_key      int NOT NULL COMMENT 'Unique date identifier' CONSTRAINT pk_dim_date PRIMARY KEY,
 full_date     date COMMENT 'Complete calendar date',
 `year`        int COMMENT 'Year of the date',
 quarter       int COMMENT 'Quarter of the year',
 month         int COMMENT 'Month of the year',
 day_of_month  int COMMENT 'Day within the month',
 day_of_week   int COMMENT 'Day of the week (1-7)',
 week_of_year  int COMMENT 'Week number within the year',
 month_name    string COMMENT 'Full name of the month',
 day_name      string COMMENT 'Full name of the day',
 is_weekend    boolean COMMENT 'Flag indicating if the date is a weekend',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Calendar/date dimension (populate via seed script).';
CREATE TABLE veh_dm.dim_customer
(
 customer_sk   bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for customer' CONSTRAINT pk_dim_customer PRIMARY KEY,
 customer_code string COMMENT 'Unique customer identifier',
 customer_name string COMMENT 'Full name of customer',
 segment       string COMMENT 'Customer market segment classification',
 country       string COMMENT 'Customer''s country of origin',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'End customers and dealers.';
CREATE TABLE veh_dm.dim_contract
(
 contract_sk   bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for contract' CONSTRAINT pk_dim_contract PRIMARY KEY,
 contract_code string COMMENT 'Unique identifier for contract',
 contract_type string COMMENT 'Classification of contract',
 incoterms     string COMMENT 'International commercial terms defining shipping responsibilities',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Sales contracts/terms.';
CREATE TABLE veh_dm.dim_business_unit
(
 bu_sk   bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Surrogate key for business unit, used as the primary unique identifier.' CONSTRAINT pk_dim_business_unit PRIMARY KEY,
 bu_code string COMMENT 'Unique code representing the business unit.',
 bu_name string COMMENT 'Full name of the business unit.'
)
USING DELTA
 COMMENT 'Business unit (e.g., defense, access, fire & emergency).';
CREATE TABLE table_26
(
 `<tablename>_id`  bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Surrogate identifier' CONSTRAINT pk_table_26 PRIMARY KEY,
 business_key      string NOT NULL COMMENT 'Natural key from source system',
 created_timestamp timestamp NOT NULL GENERATED ALWAYS AS (current_timestamp()) COMMENT 'When the record was created',
 dw_created_ts     timestamp NOT NULL COMMENT 'When the record was first created',
 created_by        varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts        timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by        varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted        boolean NOT NULL COMMENT 'Logical deletion flag.'
)
 COMMENT 'Modeled via template. Includes ingestion, audit, DQ, and governance metadata.'
 TBLPROPERTIES (delta.columnMapping.mode = 'name');
CREATE TABLE table_25
(
 pk_test    NOT NULL,
 pk_test_1  NOT NULL,
 CONSTRAINT fk_table_25_table_24 FOREIGN KEY (pk_test, pk_test_1) REFERENCES table_24 (pk_test, pk_test_1)
)
 TBLPROPERTIES (delta.columnMapping.mode = 'name');
CREATE TABLE veh_dm.dim_model
(
 model_sk           bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for model' CONSTRAINT pk_dim_model PRIMARY KEY,
 model_code         string COMMENT 'Unique model identifier',
 model_name         string COMMENT 'Descriptive name of the model',
 powertrain         string COMMENT 'Type of powertrain configuration',
 gvwr_class         string COMMENT 'Gross vehicle weight rating classification',
 platform_sk        bigint COMMENT 'Reference to platform family' CONSTRAINT fk_dim_model_dim_platform REFERENCES veh_dm.dim_platform,
 dw_created_ts      timestamp NOT NULL COMMENT 'When the record was first created',
 created_by         varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts         timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by         varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted         boolean NOT NULL COMMENT 'Logical deletion flag.',
 forecast_type_hkey binary NOT NULL CONSTRAINT fk_dim_model_dim_forecast_type REFERENCES sales_infomart.dim_forecast_type
)
USING DELTA
 COMMENT 'Specific models under a platform.';
CREATE TABLE veh_dm.fact_shipment
(
 shipment_sk   bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for shipment' CONSTRAINT pk_fact_shipment PRIMARY KEY,
 shipment_id   string COMMENT 'Unique identifier for shipment',
 order_number  string COMMENT 'Related sales order number',
 ship_date_key int COMMENT 'Date of shipment',
 plant_sk      bigint COMMENT 'Reference to shipping manufacturing plant',
 customer_sk   bigint COMMENT 'Reference to receiving customer' CONSTRAINT fk_fact_shipment_dim_customer REFERENCES veh_dm.dim_customer,
 model_sk      bigint COMMENT 'Reference to product model' CONSTRAINT fk_fact_shipment_dim_model REFERENCES veh_dm.dim_model,
 shipped_qty   decimal(18, 2) COMMENT 'Quantity of items shipped',
 carrier       string COMMENT 'Shipping carrier name',
 tracking_no   string COMMENT 'Carrier tracking number',
 on_time_flag  int COMMENT 'Indicator of shipment timeliness',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Outbound shipments and OTD metrics.';
CREATE TABLE veh_dm.fact_sales_order
(
 so_line_sk              bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for sales order line' CONSTRAINT pk_fact_sales_order PRIMARY KEY,
 order_number            string COMMENT 'Unique sales order identifier',
 order_line_number       int COMMENT 'Line number within sales order',
 order_date_key          int COMMENT 'Date of sales order creation',
 requested_ship_date_key int COMMENT 'Customer requested shipment date',
 customer_sk             bigint COMMENT 'Reference to customer' CONSTRAINT fk_fact_sales_order_dim_customer REFERENCES veh_dm.dim_customer,
 contract_sk             bigint COMMENT 'Reference to sales contract' CONSTRAINT fk_fact_sales_order_dim_contract REFERENCES veh_dm.dim_contract,
 model_sk                bigint COMMENT 'Reference to product model' CONSTRAINT fk_fact_sales_order_dim_model REFERENCES veh_dm.dim_model,
 qty_ordered             decimal(18, 2) COMMENT 'Quantity of items ordered',
 unit_price              decimal(18, 4) COMMENT 'Price per unit',
 extended_amount         decimal(18, 4) COMMENT 'Total order line amount',
 dw_created_ts           timestamp NOT NULL COMMENT 'When the record was first created',
 created_by              varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts              timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by              varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted              boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Sales order lines (bookings/backlog analysis).';
CREATE TABLE veh_dm.fact_op_exec
(
 op_exec_sk    bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for operation execution' CONSTRAINT pk_fact_op_exec PRIMARY KEY,
 work_order_id string COMMENT 'Identifier for work order',
 date_key      int COMMENT 'Date of operation execution',
 op_sk         bigint COMMENT 'Reference to specific operation' CONSTRAINT fk_fact_op_exec_dim_op REFERENCES veh_dm.dim_op,
 plant_sk      bigint COMMENT 'Reference to manufacturing plant',
 model_sk      bigint COMMENT 'Reference to product model' CONSTRAINT fk_fact_op_exec_dim_model REFERENCES veh_dm.dim_model,
 labor_minutes decimal(18, 2) COMMENT 'Labor time spent on operation',
 yield_qty     decimal(18, 2) COMMENT 'Quantity of successful units produced',
 scrap_qty     decimal(18, 2) COMMENT 'Quantity of units scrapped during operation',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Executed operations for throughput/FPY.';
CREATE TABLE veh_dm.dim_vehicle
(
 vehicle_sk     bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for vehicle' CONSTRAINT pk_dim_vehicle PRIMARY KEY,
 serial_no      string COMMENT 'Unique serial number of vehicle',
 model_sk       bigint COMMENT 'Reference to vehicle model',
 plant_sk       bigint COMMENT 'Reference to manufacturing plant',
 customer_sk    bigint COMMENT 'Reference to customer owning vehicle',
 status         string COMMENT 'Current status of vehicle',
 build_date_key int COMMENT 'Date of vehicle manufacture',
 ship_date_key  int COMMENT 'Date of vehicle shipment',
 dw_created_ts  timestamp NOT NULL COMMENT 'When the record was first created',
 created_by     varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts     timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by     varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted     boolean NOT NULL COMMENT 'Logical deletion flag.',
 employee_id    int NOT NULL CONSTRAINT fk_dim_vehicle_EMPLOYEES REFERENCES EMPLOYEES (EMPLOYEE_ID)
)
USING DELTA
 COMMENT 'Serialized finished units for lifecycle analytics.';
CREATE TABLE veh_dm.fact_warranty_claim
(
 claim_sk       bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for warranty claim' CONSTRAINT pk_fact_warranty_claim PRIMARY KEY,
 claim_id       string COMMENT 'Unique identifier for warranty claim',
 claim_date_key int COMMENT 'Date of warranty claim',
 vehicle_sk     bigint COMMENT 'Reference to specific vehicle' CONSTRAINT fk_fact_warranty_claim_dim_vehicle REFERENCES veh_dm.dim_vehicle,
 model_sk       bigint COMMENT 'Reference to vehicle model' CONSTRAINT fk_fact_warranty_claim_dim_model REFERENCES veh_dm.dim_model,
 failure_sk     bigint COMMENT 'Reference to failure mode' CONSTRAINT fk_fact_warranty_claim_dim_failure REFERENCES veh_dm.dim_failure,
 claim_status   string COMMENT 'Current status of warranty claim',
 labor_cost     decimal(18, 2) COMMENT 'Labor costs associated with claim',
 parts_cost     decimal(18, 2) COMMENT 'Parts costs associated with claim',
 total_cost     decimal(18, 2) COMMENT 'Total cost of warranty claim',
 dw_created_ts  timestamp NOT NULL COMMENT 'When the record was first created',
 created_by     varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts     timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by     varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted     boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Warranty claims and costs.';
CREATE TABLE veh_dm.fact_vehicle_telemetry
(
 veh_telem_sk   bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for vehicle telemetry event' CONSTRAINT pk_fact_vehicle_telemetry PRIMARY KEY,
 event_date_key int COMMENT 'Date of telemetry event',
 event_time_key int COMMENT 'Time of telemetry event',
 vehicle_sk     bigint COMMENT 'Reference to specific vehicle',
 model_sk       bigint COMMENT 'Reference to vehicle model',
 latitude       double COMMENT 'Geographical latitude of vehicle',
 longitude      double COMMENT 'Geographical longitude of vehicle',
 odo_km         double COMMENT 'Vehicle odometer reading in kilometers',
 soc_pct        double COMMENT 'State of charge percentage (for electric vehicles)',
 fault_code     string COMMENT 'Vehicle diagnostic fault code',
 dw_created_ts  timestamp NOT NULL COMMENT 'When the record was first created',
 created_by     varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts     timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by     varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted     boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 PARTITIONED BY (event_date_key)
 COMMENT 'High-volume time-series from connected vehicles.';
CREATE TABLE veh_dm.fact_service_event
(
 service_sk     bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for service event' CONSTRAINT pk_fact_service_event PRIMARY KEY,
 event_id       string COMMENT 'Unique identifier for service event',
 event_date_key int COMMENT 'Date of service event',
 event_time_key int COMMENT 'Time of service event',
 vehicle_sk     bigint COMMENT 'Reference to specific vehicle' CONSTRAINT fk_fact_service_event_dim_vehicle REFERENCES veh_dm.dim_vehicle,
 model_sk       bigint COMMENT 'Reference to vehicle model' CONSTRAINT fk_fact_service_event_dim_model REFERENCES veh_dm.dim_model,
 customer_sk    bigint COMMENT 'Reference to customer' CONSTRAINT fk_fact_service_event_dim_customer REFERENCES veh_dm.dim_customer,
 event_type_sk  bigint COMMENT 'Reference to event type' CONSTRAINT fk_fact_service_event_dim_event_type REFERENCES veh_dm.dim_event_type,
 labor_minutes  decimal(18, 2) COMMENT 'Labor time spent on service event',
 dw_created_ts  timestamp NOT NULL COMMENT 'When the record was first created',
 created_by     varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts     timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by     varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted     boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Field service activity by vehicle/customer.';
CREATE TABLE veh_dm.dim_plant
(
 plant_sk   bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for plant',
 plant_code string COMMENT 'Unique plant identifier',
 plant_name string COMMENT 'Descriptive name of plant',
 country    string COMMENT 'Country where plant is located',
 tz         string COMMENT 'Timezone of the plant',
 bu_sk      bigint COMMENT 'Reference to business unit'
)
USING DELTA
 COMMENT 'Manufacturing / assembly sites.';
CREATE TABLE veh_dm.fact_work_order
(
 wo_sk          bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for work order' CONSTRAINT pk_fact_work_order PRIMARY KEY,
 work_order_id  string COMMENT 'Unique identifier for work order',
 start_date_key int COMMENT 'Planned start date of work order',
 due_date_key   int COMMENT 'Planned completion date of work order',
 plant_sk       bigint COMMENT 'Reference to manufacturing plant',
 model_sk       bigint COMMENT 'Reference to product model' CONSTRAINT fk_fact_work_order_dim_model REFERENCES veh_dm.dim_model,
 qty_planned    decimal(18, 2) COMMENT 'Planned quantity of units to produce',
 qty_completed  decimal(18, 2) COMMENT 'Actual quantity of units produced',
 status         string COMMENT 'Current status of work order',
 dw_created_ts  timestamp NOT NULL COMMENT 'When the record was first created',
 created_by     varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts     timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by     varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted     boolean NOT NULL COMMENT 'Logical deletion flag.',
 CONSTRAINT fk_fact_work_order_dim_plant FOREIGN KEY () REFERENCES veh_dm.dim_plant ()
)
USING DELTA
 COMMENT 'Production orders by model/plant.';
CREATE TABLE veh_dm.fact_purchase_order
(
 po_line_sk                bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for purchase order line' CONSTRAINT pk_fact_purchase_order PRIMARY KEY,
 po_number                 string COMMENT 'Unique purchase order identifier',
 po_line_number            int COMMENT 'Line number within purchase order',
 order_date_key            int COMMENT 'Date of purchase order creation',
 expected_receipt_date_key int COMMENT 'Planned date of material receipt',
 plant_sk                  bigint COMMENT 'Reference to receiving manufacturing plant',
 supplier_sk               bigint COMMENT 'Reference to supplier' CONSTRAINT fk_fact_purchase_order_dim_supplier REFERENCES veh_dm.dim_supplier,
 part_sk                   bigint COMMENT 'Reference to purchased part' CONSTRAINT fk_fact_purchase_order_dim_part REFERENCES veh_dm.dim_part,
 ordered_qty               decimal(18, 2) COMMENT 'Quantity of parts ordered',
 unit_price                decimal(18, 4) COMMENT 'Price per unit of part',
 received_qty              decimal(18, 2) COMMENT 'Quantity of parts actually received',
 dw_created_ts             timestamp NOT NULL COMMENT 'When the record was first created',
 created_by                varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts                timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by                varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted                boolean NOT NULL COMMENT 'Logical deletion flag.',
 CONSTRAINT fk_fact_purchase_order_dim_plant FOREIGN KEY () REFERENCES veh_dm.dim_plant ()
)
USING DELTA
 COMMENT 'Materials purchasing and receipts.';
CREATE TABLE veh_dm.fact_inventory_snapshot
(
 inv_snap_sk   bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for inventory snapshot' CONSTRAINT pk_fact_inventory_snapshot PRIMARY KEY,
 date_key      int COMMENT 'Date of inventory snapshot',
 plant_sk      bigint COMMENT 'Reference to manufacturing plant',
 part_sk       bigint COMMENT 'Reference to specific part',
 on_hand_qty   decimal(18, 2) COMMENT 'Current quantity of part in inventory',
 reserved_qty  decimal(18, 2) COMMENT 'Quantity of part reserved for specific purposes',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.',
 CONSTRAINT fk_fact_inventory_snapshot_dim_plant FOREIGN KEY () REFERENCES veh_dm.dim_plant ()
)
USING DELTA
 COMMENT 'Daily inventory snapshot.';