-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- ************************************** ACMECORP.SUPPLYCHAIN.CALCULATE_AND_LOG_MAINTENANCE_COST
CREATE PROCEDURE ACMECORP.SUPPLYCHAIN.CALCULATE_AND_LOG_MAINTENANCE_COST("START_DATE" DATE, "END_DATE" DATE)
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '
try {
    // Define a SQL query to calculate the total maintenance cost by warehouse within the date range
    var query = `
        SELECT 
            wm.WarehouseKey, 
            SUM(wm.MaintenanceCost) AS total_maintenance_cost
        FROM 
            WarehouseMaintenanceFact wm
        WHERE 
            wm.DateKey BETWEEN :start_date AND :end_date
        GROUP BY 
            wm.WarehouseKey;
    `;
    
    // Execute the SQL query
    var result = snowflake.execute({
        sqlText: query,
        binds: [start_date, end_date]
    });

    // Loop through the result set and insert the log into a separate logging table
    while (result.next()) {
        var warehouseKey = result.getColumnValue("WarehouseKey");
        var totalCost = result.getColumnValue("total_maintenance_cost");

        // Insert the result into a log table for maintenance cost tracking
        var insertLogQuery = `
            INSERT INTO MaintenanceCostLog (WarehouseKey, TotalMaintenanceCost, LogDate)
            VALUES (?, ?, CURRENT_DATE);
        `;
        snowflake.execute({
            sqlText: insertLogQuery,
            binds: [warehouseKey, totalCost]
        });
    }

    return "Maintenance costs calculated and logged successfully.";
    
} catch (err) {
    return "Failed: " + err;
}
';
