-- ************************************ SqlDBM: Snowflake ***********************************
-- * Generated by SqlDBM: Sample/Sample Project: Healthcare by heather.ready+yew@sqldbm.com *


-- ************************************** ANALYTICS
CREATE SCHEMA ANALYTICS;

-- ************************************** ANALYTICS.REF_PROCEDURE_CODE
CREATE TABLE ANALYTICS.REF_PROCEDURE_CODE
(
 PROCEDURE_CODE        varchar(20) NOT NULL COMMENT 'Procedure code, for example CPT or HCPCS',
 PROCEDURE_DESCRIPTION varchar(255) NOT NULL COMMENT 'Description of the procedure code',
 CODE_SYSTEM           varchar(50) NOT NULL COMMENT 'Code system, for example CPT',
 EFFECTIVE_START_DATE  date NOT NULL COMMENT 'Date the code became valid',
 EFFECTIVE_END_DATE    date COMMENT 'Date the code expired, if applicable',
 IS_ACTIVE             boolean NOT NULL DEFAULT TRUE COMMENT 'Indicates if the code is currently active',
 CREATED_TIMESTAMP     timestamp NOT NULL,
 CREATED_BY_NAME       varchar(50) NOT NULL,
 UPDATED_TIMESTAMP     timestamp NOT NULL,
 UPDATED_BY_NAME       varchar(50) NOT NULL,

 CONSTRAINT pk_REF_PROCEDURE_CODE PRIMARY KEY ( PROCEDURE_CODE )
)
COMMENT = 'Reference table for procedure codes, such as CPT.';

-- ************************************** ANALYTICS.REF_LAB_TEST
CREATE TABLE ANALYTICS.REF_LAB_TEST
(
 LAB_TEST_CODE       varchar(50) NOT NULL COMMENT 'Lab test code, for example LOINC code',
 LAB_TEST_NAME       varchar(255) NOT NULL COMMENT 'Display name for the lab test',
 RESULT_UNIT_DEFAULT varchar(50) COMMENT 'Default unit of measure for this test',
 CATEGORY            varchar(100) COMMENT 'Category, for example Chemistry, Hematology',
 IS_ACTIVE           boolean NOT NULL DEFAULT TRUE COMMENT 'Indicates if the lab test code is active',
 CREATED_TIMESTAMP   timestamp NOT NULL,
 CREATED_BY_NAME     varchar(50) NOT NULL,
 UPDATED_TIMESTAMP   timestamp NOT NULL,
 UPDATED_BY_NAME     varchar(50) NOT NULL,

 CONSTRAINT pk_REF_LAB_TEST PRIMARY KEY ( LAB_TEST_CODE )
)
COMMENT = 'Reference table for lab test codes, such as LOINC.';

-- ************************************** ANALYTICS.REF_DIAGNOSIS_CODE
CREATE TABLE ANALYTICS.REF_DIAGNOSIS_CODE
(
 DIAGNOSIS_CODE        varchar(20) NOT NULL COMMENT 'ICD diagnosis code',
 DIAGNOSIS_DESCRIPTION varchar(255) NOT NULL COMMENT 'Description of the diagnosis code',
 CODE_SYSTEM           varchar(50) NOT NULL COMMENT 'Code system, for example ICD-10',
 EFFECTIVE_START_DATE  date NOT NULL COMMENT 'Date the code became valid',
 EFFECTIVE_END_DATE    date COMMENT 'Date the code expired, if applicable',
 IS_ACTIVE             boolean NOT NULL DEFAULT TRUE COMMENT 'Indicates if the code is currently active',
 CREATED_TIMESTAMP     timestamp NOT NULL,
 CREATED_BY_NAME       varchar(50) NOT NULL,
 UPDATED_TIMESTAMP     timestamp NOT NULL,
 UPDATED_BY_NAME       varchar(50) NOT NULL,

 CONSTRAINT pk_REF_DIAGNOSIS_CODE PRIMARY KEY ( DIAGNOSIS_CODE )
)
COMMENT = 'Reference table for diagnosis codes, such as ICD-10.';

-- ************************************** ANALYTICS.DIM_PROVIDER
CREATE TABLE ANALYTICS.DIM_PROVIDER
(
 PROVIDER_KEY         number(38,0) NOT NULL COMMENT 'Surrogate key for the provider dimension',
 PROVIDER_ID          varchar(50) NOT NULL COMMENT 'Natural identifier for the provider from source system',
 EFFECTIVE_START_DATE date NOT NULL COMMENT 'Start date for this version of the provider record',
 EFFECTIVE_END_DATE   date COMMENT 'End date for this version of the provider record',
 IS_CURRENT           boolean NOT NULL DEFAULT TRUE COMMENT 'Indicates if this is the current provider row',
 PROVIDER_NPI         varchar(20) COMMENT 'National Provider Identifier or equivalent',
 PROVIDER_NAME        varchar(255) COMMENT 'Full provider name',
 PROVIDER_FIRST_NAME  varchar(100) COMMENT 'Provider first name',
 PROVIDER_LAST_NAME   varchar(100) COMMENT 'Provider last name',
 SPECIALTY            varchar(100) COMMENT 'Primary specialty',
 SUBSPECIALTY         varchar(100) COMMENT 'Subspecialty if applicable',
 EMPLOYMENT_TYPE      varchar(50) COMMENT 'Employment type, for example Employed, Contracted',
 ACTIVE_FLAG          boolean COMMENT 'Indicates if provider is active in the network',
 CREATED_TIMESTAMP    timestamp NOT NULL,
 CREATED_BY_NAME      varchar(50) NOT NULL,
 UPDATED_TIMESTAMP    timestamp NOT NULL,
 UPDATED_BY_NAME      varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_PROVIDER PRIMARY KEY ( PROVIDER_KEY ),
 CONSTRAINT UK_DIM_PROVIDER_BK_EFF UNIQUE ( PROVIDER_ID, EFFECTIVE_START_DATE )
)
COMMENT = 'Provider dimension with SCD2 tracking of changes such as specialty and employment.';

-- ************************************** ANALYTICS.DIM_PAYER_PLAN
CREATE TABLE ANALYTICS.DIM_PAYER_PLAN
(
 PAYER_PLAN_KEY       number(38,0) NOT NULL COMMENT 'Surrogate key for the payer plan dimension',
 PAYER_PLAN_ID        varchar(50) NOT NULL COMMENT 'Natural identifier for the payer plan from source',
 EFFECTIVE_START_DATE date NOT NULL COMMENT 'Start date for this version of the payer plan record',
 EFFECTIVE_END_DATE   date COMMENT 'End date for this version of the payer plan record',
 IS_CURRENT           boolean NOT NULL DEFAULT TRUE COMMENT 'Indicates if this is the current payer plan row',
 PAYER_NAME           varchar(255) NOT NULL COMMENT 'Payer organization name',
 PLAN_NAME            varchar(255) NOT NULL COMMENT 'Insurance plan name',
 PLAN_TYPE            varchar(100) COMMENT 'Plan type, for example HMO, PPO, EPO',
 NETWORK_TYPE         varchar(100) COMMENT 'Network type, for example In-network, Out-of-network',
 METAL_TIER           varchar(50) COMMENT 'Metal tier for ACA plans, for example Bronze, Silver',
 ACTIVE_FLAG          boolean COMMENT 'Indicates if plan is active',
 CREATED_TIMESTAMP    timestamp NOT NULL,
 CREATED_BY_NAME      varchar(50) NOT NULL,
 UPDATED_TIMESTAMP    timestamp NOT NULL,
 UPDATED_BY_NAME      varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_PAYER_PLAN PRIMARY KEY ( PAYER_PLAN_KEY ),
 CONSTRAINT UK_DIM_PAYER_PLAN_BK_EFF UNIQUE ( EFFECTIVE_START_DATE, PAYER_PLAN_ID )
)
COMMENT = 'Payer and insurance plan dimension with SCD2 tracking.';

-- ************************************** ANALYTICS.DIM_PATIENT
CREATE TABLE ANALYTICS.DIM_PATIENT
(
 PATIENT_KEY          number(38,0) NOT NULL COMMENT 'Surrogate key for the patient dimension',
 PATIENT_ID           varchar(50) NOT NULL COMMENT 'Natural business identifier for the patient from source system',
 EFFECTIVE_START_DATE date NOT NULL COMMENT 'Start date for this version of the patient record',
 EFFECTIVE_END_DATE   date COMMENT 'End date for this version of the patient record',
 IS_CURRENT           boolean NOT NULL DEFAULT TRUE COMMENT 'Indicates if this is the current version of the patient record',
 FIRST_NAME           varchar(100) COMMENT 'Patient first name',
 LAST_NAME            varchar(100) COMMENT 'Patient last name',
 DATE_OF_BIRTH        date COMMENT 'Patient date of birth',
 GENDER               varchar(50) COMMENT 'Gender as stored in the source system',
 MARITAL_STATUS       varchar(50) COMMENT 'Marital status',
 EMAIL_ADDRESS        varchar(255) COMMENT 'Patient email address',
 PHONE_NUMBER         varchar(50) COMMENT 'Primary phone number',
 ADDRESS_LINE_1       varchar(255) COMMENT 'Primary street address line 1',
 ADDRESS_LINE_2       varchar(255) COMMENT 'Primary street address line 2',
 CITY                 varchar(100) COMMENT 'Patient city',
 STATE_PROVINCE       varchar(50) COMMENT 'Patient state or province',
 POSTAL_CODE          varchar(20) COMMENT 'Postal or ZIP code',
 COUNTRY              varchar(100) COMMENT 'Patient country',
 PRIMARY_LANGUAGE     varchar(100) COMMENT 'Primary language',
 RACE_ETHNICITY       varchar(100) COMMENT 'Race or ethnicity as captured in source',
 DECEASED_FLAG        boolean COMMENT 'Indicates if the patient is deceased',
 DECEASED_DATE        date COMMENT 'Date of death if available',
 CREATED_TIMESTAMP    timestamp NOT NULL,
 CREATED_BY_NAME      varchar(50) NOT NULL,
 UPDATED_TIMESTAMP    timestamp NOT NULL,
 UPDATED_BY_NAME      varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_PATIENT PRIMARY KEY ( PATIENT_KEY ),
 CONSTRAINT UK_DIM_PATIENT_BK_EFF UNIQUE ( PATIENT_ID, EFFECTIVE_START_DATE )
)
COMMENT = 'Patient dimension with SCD2 tracking of demographic changes.';

-- ************************************** ANALYTICS.DIM_MEDICATION
CREATE TABLE ANALYTICS.DIM_MEDICATION
(
 MEDICATION_KEY    number(38,0) NOT NULL COMMENT 'Surrogate key for the medication dimension',
 MEDICATION_ID     varchar(50) NOT NULL COMMENT 'Medication identifier from source system or formulary',
 MEDICATION_NAME   varchar(255) NOT NULL COMMENT 'Display name for the medication',
 GENERIC_NAME      varchar(255) COMMENT 'Generic medication name',
 BRAND_NAME        varchar(255) COMMENT 'Brand name',
 THERAPEUTIC_CLASS varchar(255) COMMENT 'Therapeutic class',
 ROUTE_OF_ADMIN    varchar(100) COMMENT 'Route of administration, for example Oral, IV',
 FORM_STRENGTH     varchar(100) COMMENT 'Dose form and strength text',
 CREATED_TIMESTAMP timestamp NOT NULL,
 CREATED_BY_NAME   varchar(50) NOT NULL,
 UPDATED_TIMESTAMP timestamp NOT NULL,
 UPDATED_BY_NAME   varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_MEDICATION PRIMARY KEY ( MEDICATION_KEY ),
 CONSTRAINT UK_DIM_MEDICATION_BK UNIQUE ( MEDICATION_ID )
)
COMMENT = 'Medication dimension for orders and administrations.';

-- ************************************** ANALYTICS.DIM_LOCATION
CREATE TABLE ANALYTICS.DIM_LOCATION
(
 LOCATION_KEY      number(38,0) NOT NULL COMMENT 'Surrogate key for the location dimension',
 LOCATION_ID       varchar(50) NOT NULL COMMENT 'Location identifier from source system',
 LOCATION_NAME     varchar(255) NOT NULL COMMENT 'Location name, for example Nursing unit, Room',
 LOCATION_TYPE     varchar(100) COMMENT 'Location type, for example Nursing unit, Bed, Clinic room',
 CREATED_TIMESTAMP timestamp NOT NULL,
 CREATED_BY_NAME   varchar(50) NOT NULL,
 UPDATED_TIMESTAMP timestamp NOT NULL,
 UPDATED_BY_NAME   varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_LOCATION PRIMARY KEY ( LOCATION_KEY ),
 CONSTRAINT UK_DIM_LOCATION_BK UNIQUE ( LOCATION_ID )
)
COMMENT = 'Location dimension representing nursing units, rooms, and other physical locations.';

-- ************************************** ANALYTICS.DIM_INSURANCE_COVERAGE
CREATE TABLE ANALYTICS.DIM_INSURANCE_COVERAGE
(
 INSURANCE_COVERAGE_KEY number(38,0) NOT NULL COMMENT 'Surrogate key for the insurance coverage dimension',
 PATIENT_ID             varchar(50) NOT NULL COMMENT 'Patient business key to link coverage to the patient',
 PAYER_PLAN_ID          varchar(50) NOT NULL COMMENT 'Business key of the payer plan',
 EFFECTIVE_START_DATE   date NOT NULL COMMENT 'Coverage effective start date',
 EFFECTIVE_END_DATE     date COMMENT 'Coverage effective end date',
 IS_CURRENT             boolean NOT NULL DEFAULT TRUE COMMENT 'Indicates if this is the current coverage row',
 COVERAGE_TIER          varchar(50) COMMENT 'Coverage tier, for example Employee, Spouse, Dependent',
 SUBSCRIBER_ID          varchar(50) COMMENT 'Subscriber identifier',
 GROUP_NUMBER           varchar(50) COMMENT 'Employer or group number',
 COB_PRIORITY           number(3,0) COMMENT 'Coordination of benefits priority, lower is primary',
 CREATED_TIMESTAMP      timestamp NOT NULL,
 CREATED_BY_NAME        varchar(50) NOT NULL,
 UPDATED_TIMESTAMP      timestamp NOT NULL,
 UPDATED_BY_NAME        varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_INSURANCE_COVERAGE PRIMARY KEY ( INSURANCE_COVERAGE_KEY ),
 CONSTRAINT UK_DIM_INSURANCE_COVERAGE_BK_EFF UNIQUE ( PAYER_PLAN_ID, EFFECTIVE_START_DATE, PATIENT_ID )
)
COMMENT = 'Insurance coverage dimension, SCD2, representing patient coverage periods.';

-- ************************************** ANALYTICS.DIM_FACILITY
CREATE TABLE ANALYTICS.DIM_FACILITY
(
 FACILITY_KEY         number(38,0) NOT NULL COMMENT 'Surrogate key for the facility dimension',
 FACILITY_ID          varchar(50) NOT NULL COMMENT 'Natural identifier for the facility from source system',
 EFFECTIVE_START_DATE date NOT NULL COMMENT 'Start date for this version of the facility record',
 EFFECTIVE_END_DATE   date COMMENT 'End date for this version of the facility record',
 IS_CURRENT           boolean NOT NULL DEFAULT TRUE COMMENT 'Indicates if this is the current facility row',
 FACILITY_NAME        varchar(255) NOT NULL COMMENT 'Facility name, for example Hospital or Clinic name',
 FACILITY_TYPE        varchar(100) COMMENT 'Type, for example Hospital, Clinic, ASC',
 ADDRESS_LINE_1       varchar(255) COMMENT 'Facility address line 1',
 ADDRESS_LINE_2       varchar(255) COMMENT 'Facility address line 2',
 CITY                 varchar(100) COMMENT 'Facility city',
 STATE_PROVINCE       varchar(50) COMMENT 'Facility state or province',
 POSTAL_CODE          varchar(20) COMMENT 'Facility postal or ZIP code',
 COUNTRY              varchar(100) COMMENT 'Facility country',
 REGION               varchar(100) COMMENT 'Region or market assignment',
 ACTIVE_FLAG          boolean COMMENT 'Indicates if facility is active',
 CREATED_TIMESTAMP    timestamp NOT NULL,
 CREATED_BY_NAME      varchar(50) NOT NULL,
 UPDATED_TIMESTAMP    timestamp NOT NULL,
 UPDATED_BY_NAME      varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_FACILITY PRIMARY KEY ( FACILITY_KEY ),
 CONSTRAINT UK_DIM_FACILITY_BK_EFF UNIQUE ( FACILITY_ID, EFFECTIVE_START_DATE )
)
COMMENT = 'Facility dimension with SCD2 tracking, representing hospitals, clinics, and other sites.';

-- ************************************** ANALYTICS.DIM_DEPARTMENT
CREATE TABLE ANALYTICS.DIM_DEPARTMENT
(
 DEPARTMENT_KEY    number(38,0) NOT NULL COMMENT 'Surrogate key for the department dimension',
 DEPARTMENT_ID     varchar(50) NOT NULL COMMENT 'Department identifier from source system',
 DEPARTMENT_NAME   varchar(255) NOT NULL COMMENT 'Name of the department',
 DEPARTMENT_TYPE   varchar(100) COMMENT 'Type, for example Emergency, Inpatient, Outpatient, Radiology',
 SERVICE_LINE      varchar(100) COMMENT 'Clinical service line classification',
 CREATED_TIMESTAMP timestamp NOT NULL,
 CREATED_BY_NAME   varchar(50) NOT NULL,
 UPDATED_TIMESTAMP timestamp NOT NULL,
 UPDATED_BY_NAME   varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_DEPARTMENT PRIMARY KEY ( DEPARTMENT_KEY ),
 CONSTRAINT UK_DIM_DEPARTMENT_BK UNIQUE ( DEPARTMENT_ID )
)
COMMENT = 'Department dimension representing clinical and operational departments.';

-- ************************************** ANALYTICS.DIM_DATE
CREATE TABLE ANALYTICS.DIM_DATE
(
 DATE_KEY          number(8,0) NOT NULL COMMENT 'Surrogate key in YYYYMMDD format',
 CALENDAR_DATE     date NOT NULL COMMENT 'Actual calendar date',
 DAY_OF_WEEK       number(1,0) NOT NULL COMMENT 'Day of week as number, for example 1 = Monday',
 DAY_NAME          varchar(20) NOT NULL COMMENT 'Day of week name',
 DAY_OF_MONTH      number(2,0) NOT NULL COMMENT 'Day of month',
 DAY_OF_YEAR       number(3,0) NOT NULL COMMENT 'Day of year',
 WEEK_OF_YEAR      number(2,0) NOT NULL COMMENT 'Week of year number',
 MONTH_NUMBER      number(2,0) NOT NULL COMMENT 'Month number 1 to 12',
 MONTH_NAME        varchar(20) NOT NULL COMMENT 'Full month name',
 QUARTER_NUMBER    number(1,0) NOT NULL COMMENT 'Quarter number 1 to 4',
 YEAR_NUMBER       number(4,0) NOT NULL COMMENT 'Calendar year',
 IS_WEEKEND        boolean NOT NULL COMMENT 'Indicates if the date falls on a weekend',
 IS_HOLIDAY        boolean NOT NULL DEFAULT FALSE COMMENT 'Indicates if the date is a holiday in the local region',
 CREATED_TIMESTAMP timestamp NOT NULL,
 CREATED_BY_NAME   varchar(50) NOT NULL,
 UPDATED_TIMESTAMP timestamp NOT NULL,
 UPDATED_BY_NAME   varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_DATE PRIMARY KEY ( DATE_KEY ),
 CONSTRAINT UK_DIM_DATE UNIQUE ( CALENDAR_DATE )
)
COMMENT = 'Date dimension with standard calendar breakdown for analytics.';

-- ************************************** ANALYTICS.DIM_APPOINTMENT_STATUS
CREATE TABLE ANALYTICS.DIM_APPOINTMENT_STATUS
(
 APPOINTMENT_STATUS_KEY  number(38,0) NOT NULL COMMENT 'Surrogate key for appointment status dimension',
 APPOINTMENT_STATUS_CODE varchar(50) NOT NULL COMMENT 'Code for appointment status',
 APPOINTMENT_STATUS_NAME varchar(100) NOT NULL COMMENT 'Description of appointment status, for example Completed, Canceled, No show',
 CREATED_TIMESTAMP       timestamp NOT NULL,
 CREATED_BY_NAME         varchar(50) NOT NULL,
 UPDATED_TIMESTAMP       timestamp NOT NULL,
 UPDATED_BY_NAME         varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_APPOINTMENT_STATUS PRIMARY KEY ( APPOINTMENT_STATUS_KEY ),
 CONSTRAINT UK_DIM_APPOINTMENT_STATUS_BK UNIQUE ( APPOINTMENT_STATUS_CODE )
)
COMMENT = 'Appointment status dimension used by appointment facts.';

-- ************************************** ANALYTICS.FACT_PROVIDER_PRODUCTIVITY
CREATE TABLE ANALYTICS.FACT_PROVIDER_PRODUCTIVITY
(
 PROVIDER_PRODUCTIVITY_KEY number(38,0) NOT NULL COMMENT 'Surrogate key for provider productivity fact row',
 PROVIDER_KEY              number(38,0) NOT NULL COMMENT 'Link to provider dimension',
 DATE_KEY                  number(8,0) NOT NULL COMMENT 'Date key for productivity aggregation',
 ENCOUNTER_COUNT           number(18,0) COMMENT 'Number of encounters for the provider on the date',
 PROCEDURE_COUNT           number(18,0) COMMENT 'Number of procedures performed',
 WORK_RVU_TOTAL            number(18,2) COMMENT 'Total work RVUs for the date',
 CHARGES_TOTAL_AMOUNT      number(18,2) COMMENT 'Total charges for the date',
 CREATED_TIMESTAMP         timestamp NOT NULL,
 CREATED_BY_NAME           varchar(50) NOT NULL,
 UPDATED_TIMESTAMP         timestamp NOT NULL,
 UPDATED_BY_NAME           varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_PROVIDER_PRODUCTIVITY PRIMARY KEY ( PROVIDER_PRODUCTIVITY_KEY ),
 CONSTRAINT UK_FACT_PROVIDER_PROD_BK UNIQUE ( PROVIDER_KEY, DATE_KEY ),
 CONSTRAINT fk_FACT_PROVIDER_PRODUCTIVITY_DIM_DATE FOREIGN KEY ( DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_PROVIDER_PRODUCTIVITY_DIM_PROVIDER FOREIGN KEY ( PROVIDER_KEY ) REFERENCES ANALYTICS.DIM_PROVIDER ( PROVIDER_KEY )
)
CLUSTER BY ( DATE_KEY, PROVIDER_KEY )
COMMENT = 'Provider productivity fact table, usually aggregated at daily grain.';

-- ************************************** ANALYTICS.FACT_PROCEDURE
CREATE TABLE ANALYTICS.FACT_PROCEDURE
(
 PROCEDURE_FACT_KEY     number(38,0) NOT NULL COMMENT 'Surrogate key for procedure fact row',
 ENCOUNTER_KEY          number(38,0) COMMENT 'Encounter surrogate key reference value (no FK constraint)',
 PATIENT_KEY            number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 PROVIDER_KEY           number(38,0) COMMENT 'Provider performing the procedure',
 PROCEDURE_CODE         varchar(20) NOT NULL COMMENT 'Procedure code',
 PROCEDURE_DATE_KEY     number(8,0) COMMENT 'Date key when procedure was performed',
 PRIMARY_PROCEDURE_FLAG boolean COMMENT 'Indicates if this was the primary procedure for the encounter',
 ANESTHESIA_MINUTES     number(5,0) COMMENT 'Anesthesia time in minutes if applicable',
 CREATED_TIMESTAMP      timestamp NOT NULL,
 CREATED_BY_NAME        varchar(50) NOT NULL,
 UPDATED_TIMESTAMP      timestamp NOT NULL,
 UPDATED_BY_NAME        varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_PROCEDURE PRIMARY KEY ( PROCEDURE_FACT_KEY ),
 CONSTRAINT fk_FACT_PROCEDURE_DIM_DATE FOREIGN KEY ( PROCEDURE_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_PROCEDURE_DIM_PATIENT FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY ),
 CONSTRAINT fk_FACT_PROCEDURE_DIM_PROVIDER FOREIGN KEY ( PROVIDER_KEY ) REFERENCES ANALYTICS.DIM_PROVIDER ( PROVIDER_KEY )
)
CLUSTER BY ( PROCEDURE_DATE_KEY, PATIENT_KEY )
COMMENT = 'Procedure fact table, one row per procedure performed.';

-- ************************************** ANALYTICS.FACT_PATIENT_RISK
CREATE TABLE ANALYTICS.FACT_PATIENT_RISK
(
 PATIENT_RISK_KEY      number(38,0) NOT NULL COMMENT 'Surrogate key for patient risk fact row',
 PATIENT_KEY           number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 AS_OF_DATE_KEY        number(8,0) NOT NULL COMMENT 'Date key representing when the risk score was calculated',
 RISK_SCORE            number(9,4) COMMENT 'Calculated risk score for the patient',
 RISK_SCORE_MODEL_NAME varchar(100) COMMENT 'Name of the risk scoring model, for example HCC or custom model',
 RISK_BAND             varchar(50) COMMENT 'Bucket of risk such as Low, Medium, High',
 HIGH_RISK_FLAG        boolean COMMENT 'Indicates if patient is considered high risk',
 CREATED_TIMESTAMP     timestamp NOT NULL,
 CREATED_BY_NAME       varchar(50) NOT NULL,
 UPDATED_TIMESTAMP     timestamp NOT NULL,
 UPDATED_BY_NAME       varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_PATIENT_RISK PRIMARY KEY ( PATIENT_RISK_KEY ),
 CONSTRAINT UK_FACT_PATIENT_RISK_BK UNIQUE ( PATIENT_KEY, AS_OF_DATE_KEY, RISK_SCORE_MODEL_NAME ),
 CONSTRAINT fk_FACT_PATIENT_RISK_DIM_DATE FOREIGN KEY ( AS_OF_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_PATIENT_RISK_DIM_PATIENT FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY )
)
CLUSTER BY ( PATIENT_KEY, AS_OF_DATE_KEY )
COMMENT = 'Patient risk fact table, one row per patient per risk model and as of date.';

-- ************************************** ANALYTICS.FACT_MEDICATION_ORDER
CREATE TABLE ANALYTICS.FACT_MEDICATION_ORDER
(
 MEDICATION_ORDER_KEY number(38,0) NOT NULL COMMENT 'Surrogate key for medication order fact row',
 ENCOUNTER_KEY        number(38,0) COMMENT 'Encounter surrogate key reference value (no FK constraint)',
 PATIENT_KEY          number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 PROVIDER_KEY         number(38,0) COMMENT 'Ordering provider',
 MEDICATION_KEY       number(38,0) NOT NULL COMMENT 'Link to medication dimension',
 ORDER_DATE_KEY       number(8,0) COMMENT 'Date key when order was placed',
 START_DATE_KEY       number(8,0) COMMENT 'Date key when therapy started',
 END_DATE_KEY         number(8,0) COMMENT 'Date key when therapy ended or order was completed',
 ORDER_STATUS         varchar(50) COMMENT 'Status of the order, for example Ordered, Active, Completed, Canceled',
 ORDERING_ROUTE       varchar(100) COMMENT 'Route of administration as ordered',
 ORDERED_DOSE         number(18,4) COMMENT 'Ordered dose amount',
 ORDERED_DOSE_UNIT    varchar(50) COMMENT 'Unit for ordered dose',
 FREQUENCY_TEXT       varchar(100) COMMENT 'Frequency instructions text',
 CREATED_TIMESTAMP    timestamp NOT NULL,
 CREATED_BY_NAME      varchar(50) NOT NULL,
 UPDATED_TIMESTAMP    timestamp NOT NULL,
 UPDATED_BY_NAME      varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_MEDICATION_ORDER PRIMARY KEY ( MEDICATION_ORDER_KEY ),
 CONSTRAINT fk_FACT_MEDICATION_ORDER_DIM_DATE FOREIGN KEY ( END_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_MEDICATION_ORDER_DIM_MEDICATION FOREIGN KEY ( MEDICATION_KEY ) REFERENCES ANALYTICS.DIM_MEDICATION ( MEDICATION_KEY ),
 CONSTRAINT fk_FACT_MEDICATION_ORDER_DIM_PATIENT FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY ),
 CONSTRAINT fk_FACT_MEDICATION_ORDER_DIM_PROVIDER FOREIGN KEY ( PROVIDER_KEY ) REFERENCES ANALYTICS.DIM_PROVIDER ( PROVIDER_KEY )
)
CLUSTER BY ( PATIENT_KEY, ORDER_DATE_KEY )
COMMENT = 'Medication order fact table, one row per medication order.';

-- ************************************** ANALYTICS.FACT_LAB_RESULT
CREATE TABLE ANALYTICS.FACT_LAB_RESULT
(
 LAB_RESULT_KEY       number(38,0) NOT NULL COMMENT 'Surrogate key for lab result fact row',
 ENCOUNTER_KEY        number(38,0) COMMENT 'Encounter surrogate key reference value (no FK constraint)',
 PATIENT_KEY          number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 PROVIDER_KEY         number(38,0) COMMENT 'Ordering provider',
 LAB_TEST_CODE        varchar(50) NOT NULL COMMENT 'Lab test code',
 ORDER_DATE_KEY       number(8,0) COMMENT 'Date key when lab was ordered',
 RESULT_DATE_KEY      number(8,0) COMMENT 'Date key when result was finalized',
 RESULT_VALUE_NUMERIC number(18,4) COMMENT 'Numeric result value when applicable',
 RESULT_VALUE_TEXT    varchar(255) COMMENT 'Text result, for example Positive or Negative',
 RESULT_UNIT          varchar(50) COMMENT 'Unit of measure for the numeric result',
 ABNORMAL_FLAG        varchar(10) COMMENT 'Flag for high, low, or critical results',
 REFERENCE_RANGE      varchar(100) COMMENT 'Reference range for the result',
 CREATED_TIMESTAMP    timestamp NOT NULL,
 CREATED_BY_NAME      varchar(50) NOT NULL,
 UPDATED_TIMESTAMP    timestamp NOT NULL,
 UPDATED_BY_NAME      varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_LAB_RESULT PRIMARY KEY ( LAB_RESULT_KEY ),
 CONSTRAINT fk_FACT_LAB_RESULT_DIM_DATE FOREIGN KEY ( ORDER_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_LAB_RESULT_DIM_PATIENT FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY ),
 CONSTRAINT fk_FACT_LAB_RESULT_DIM_PROVIDER FOREIGN KEY ( PROVIDER_KEY ) REFERENCES ANALYTICS.DIM_PROVIDER ( PROVIDER_KEY )
)
CLUSTER BY ( PATIENT_KEY, RESULT_DATE_KEY )
COMMENT = 'Lab result fact table, one row per lab test result.';

-- ************************************** ANALYTICS.FACT_ENCOUNTER
CREATE TABLE ANALYTICS.FACT_ENCOUNTER
(
 ENCOUNTER_KEY          number(38,0) NOT NULL COMMENT 'Surrogate key for the encounter fact row',
 ENCOUNTER_ID           varchar(50) NOT NULL COMMENT 'Encounter identifier from source system',
 PATIENT_KEY            number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 PROVIDER_KEY           number(38,0) COMMENT 'Attending or rendering provider',
 FACILITY_KEY           number(38,0) COMMENT 'Facility where encounter occurred',
 DEPARTMENT_KEY         number(38,0) COMMENT 'Department responsible for the encounter',
 LOCATION_KEY           number(38,0) COMMENT 'Location where encounter took place',
 ADMIT_DATE_KEY         number(8,0) COMMENT 'Date key when patient was admitted',
 DISCHARGE_DATE_KEY     number(8,0) COMMENT 'Date key when patient was discharged',
 PAYER_PLAN_KEY         number(38,0) COMMENT 'Payer plan at time of encounter',
 INSURANCE_COVERAGE_KEY number(38,0) COMMENT 'Insurance coverage record at time of encounter',
 ENCOUNTER_TYPE         varchar(100) COMMENT 'Encounter type, for example Inpatient, Outpatient, Emergency',
 ENCOUNTER_CLASS        varchar(100) COMMENT 'Additional classification of encounter',
 LENGTH_OF_STAY_DAYS    number(5,2) COMMENT 'Length of stay in days',
 TOTAL_CHARGES_AMOUNT   number(18,2) COMMENT 'Total charges associated with the encounter',
 TOTAL_PAYMENTS_AMOUNT  number(18,2) COMMENT 'Total payments applied to the encounter',
 READMISSION_FLAG       boolean COMMENT 'Indicates if this encounter is a readmission within policy window',
 CREATED_TIMESTAMP      timestamp NOT NULL,
 CREATED_BY_NAME        varchar(50) NOT NULL,
 UPDATED_TIMESTAMP      timestamp NOT NULL,
 UPDATED_BY_NAME        varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_ENCOUNTER PRIMARY KEY ( ENCOUNTER_KEY ),
 CONSTRAINT UK_FACT_ENCOUNTER_BK UNIQUE ( ENCOUNTER_ID ),
 CONSTRAINT fk_FACT_ENCOUNTER_DIM_DATE FOREIGN KEY ( ADMIT_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_ENCOUNTER_DIM_PATIENT FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY )
)
CLUSTER BY ( PATIENT_KEY, ADMIT_DATE_KEY )
COMMENT = 'Encounter fact table, one row per patient encounter.';

-- ************************************** ANALYTICS.FACT_DIAGNOSIS
CREATE TABLE ANALYTICS.FACT_DIAGNOSIS
(
 DIAGNOSIS_FACT_KEY        number(38,0) NOT NULL COMMENT 'Surrogate key for diagnosis fact row',
 ENCOUNTER_KEY             number(38,0) COMMENT 'Encounter surrogate key reference value (no FK constraint)',
 PATIENT_KEY               number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 DIAGNOSIS_CODE            varchar(20) NOT NULL COMMENT 'Diagnosis code assigned to the patient',
 DIAGNOSIS_DATE_KEY        number(8,0) COMMENT 'Date key when diagnosis was recorded',
 DIAGNOSIS_SEQUENCE        number(3,0) COMMENT 'Sequence number, for example 1 = primary diagnosis',
 PRESENT_ON_ADMISSION_FLAG boolean COMMENT 'Flag indicating present on admission when applicable',
 CREATED_TIMESTAMP         timestamp NOT NULL,
 CREATED_BY_NAME           varchar(50) NOT NULL,
 UPDATED_TIMESTAMP         timestamp NOT NULL,
 UPDATED_BY_NAME           varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_DIAGNOSIS PRIMARY KEY ( DIAGNOSIS_FACT_KEY ),
 CONSTRAINT fk_FACT_DIAGNOSIS_DIM_DATE FOREIGN KEY ( DIAGNOSIS_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_DIAGNOSIS_DIM_PATIENT FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY )
)
CLUSTER BY ( DIAGNOSIS_DATE_KEY, PATIENT_KEY )
COMMENT = 'Diagnosis fact table, one row per diagnosis per patient and encounter.';

-- ************************************** ANALYTICS.FACT_CLAIM_LINE
CREATE TABLE ANALYTICS.FACT_CLAIM_LINE
(
 CLAIM_LINE_KEY      number(38,0) NOT NULL COMMENT 'Surrogate key for claim line fact row',
 CLAIM_KEY           number(38,0) NOT NULL COMMENT 'Claim surrogate key reference value (no FK constraint)',
 CLAIM_ID            varchar(50) NOT NULL COMMENT 'Claim identifier from source system',
 LINE_NUMBER         number(5,0) NOT NULL COMMENT 'Line number within the claim',
 PATIENT_KEY         number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 PROVIDER_KEY        number(38,0) COMMENT 'Rendering provider for this line',
 FACILITY_KEY        number(38,0) COMMENT 'Facility where service was rendered',
 SERVICE_DATE_KEY    number(8,0) COMMENT 'Service date for this claim line',
 PROCEDURE_CODE      varchar(20) COMMENT 'Billed procedure code',
 DIAGNOSIS_CODE      varchar(20) COMMENT 'Primary diagnosis code attached to the line',
 UNITS_OF_SERVICE    number(10,2) COMMENT 'Units billed on this claim line',
 LINE_BILLED_AMOUNT  number(18,2) COMMENT 'Billed amount for the line',
 LINE_ALLOWED_AMOUNT number(18,2) COMMENT 'Allowed amount for the line',
 LINE_PAID_AMOUNT    number(18,2) COMMENT 'Paid amount for the line',
 CREATED_TIMESTAMP   timestamp NOT NULL,
 CREATED_BY_NAME     varchar(50) NOT NULL,
 UPDATED_TIMESTAMP   timestamp NOT NULL,
 UPDATED_BY_NAME     varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_CLAIM_LINE PRIMARY KEY ( CLAIM_LINE_KEY ),
 CONSTRAINT UK_FACT_CLAIM_LINE_BK UNIQUE ( CLAIM_ID, LINE_NUMBER ),
 CONSTRAINT fk_FACT_CLAIM_LINE_DIM_DATE FOREIGN KEY ( SERVICE_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_CLAIM_LINE_DIM_FACILITY FOREIGN KEY ( FACILITY_KEY ) REFERENCES ANALYTICS.DIM_FACILITY ( FACILITY_KEY ),
 CONSTRAINT fk_FACT_CLAIM_LINE_DIM_PATIENT FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY ),
 CONSTRAINT fk_FACT_CLAIM_LINE_DIM_PROVIDER FOREIGN KEY ( PROVIDER_KEY ) REFERENCES ANALYTICS.DIM_PROVIDER ( PROVIDER_KEY )
)
CLUSTER BY ( PATIENT_KEY, SERVICE_DATE_KEY )
COMMENT = 'Claim line fact table, one row per claim line item. Uses codes but no FK to reference tables.';

-- ************************************** ANALYTICS.FACT_CLAIM
CREATE TABLE ANALYTICS.FACT_CLAIM
(
 CLAIM_KEY             number(38,0) NOT NULL COMMENT 'Surrogate key for the claim fact row',
 CLAIM_ID              varchar(50) NOT NULL COMMENT 'Claim identifier from source system',
 PATIENT_KEY           number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 PAYER_PLAN_KEY        number(38,0) COMMENT 'Payer plan for the claim',
 CLAIM_SUBMIT_DATE_KEY number(8,0) COMMENT 'Date key when the claim was submitted',
 CLAIM_PAID_DATE_KEY   number(8,0) COMMENT 'Date key when the claim was paid',
 CLAIM_STATUS          varchar(50) COMMENT 'Current status of claim, for example Submitted, Pending, Paid, Denied',
 CLAIM_TYPE            varchar(50) COMMENT 'Claim type, for example Professional, Facility',
 TOTAL_BILLED_AMOUNT   number(18,2) COMMENT 'Total billed amount on the claim',
 TOTAL_ALLOWED_AMOUNT  number(18,2) COMMENT 'Total allowed amount after contract adjustments',
 TOTAL_PAID_AMOUNT     number(18,2) COMMENT 'Total paid amount from payer and patient combined',
 TOTAL_DENIED_AMOUNT   number(18,2) COMMENT 'Total denied amount',
 CREATED_TIMESTAMP     timestamp NOT NULL,
 CREATED_BY_NAME       varchar(50) NOT NULL,
 UPDATED_TIMESTAMP     timestamp NOT NULL,
 UPDATED_BY_NAME       varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_CLAIM PRIMARY KEY ( CLAIM_KEY ),
 CONSTRAINT UK_FACT_CLAIM_BK UNIQUE ( CLAIM_ID ),
 CONSTRAINT fk_FACT_CLAIM_DIM_DATE FOREIGN KEY ( CLAIM_SUBMIT_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_CLAIM_DIM_PATIENT FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY ),
 CONSTRAINT fk_FACT_CLAIM_DIM_PAYER_PLAN FOREIGN KEY ( PAYER_PLAN_KEY ) REFERENCES ANALYTICS.DIM_PAYER_PLAN ( PAYER_PLAN_KEY )
)
CLUSTER BY ( PATIENT_KEY, CLAIM_SUBMIT_DATE_KEY )
COMMENT = 'Claim fact table summarizing claim level financials.';

-- ************************************** ANALYTICS.FACT_APPOINTMENT
CREATE TABLE ANALYTICS.FACT_APPOINTMENT
(
 APPOINTMENT_KEY        number(38,0) NOT NULL COMMENT 'Surrogate key for appointment fact row',
 APPOINTMENT_ID         varchar(50) NOT NULL COMMENT 'Appointment identifier from source system',
 PATIENT_KEY            number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 PROVIDER_KEY           number(38,0) COMMENT 'Provider with whom the appointment is scheduled',
 FACILITY_KEY           number(38,0) COMMENT 'Facility where appointment will occur',
 DEPARTMENT_KEY         number(38,0) COMMENT 'Department hosting the appointment',
 APPOINTMENT_DATE_KEY   number(8,0) COMMENT 'Date key for scheduled appointment date',
 APPOINTMENT_STATUS_KEY number(38,0) COMMENT 'Link to appointment status dimension',
 SCHEDULED_DATETIME     timestamp_ntz COMMENT 'Original scheduled date and time',
 CHECKIN_DATETIME       timestamp_ntz COMMENT 'Time patient checked in',
 CHECKOUT_DATETIME      timestamp_ntz COMMENT 'Time patient checked out',
 CANCEL_DATETIME        timestamp_ntz COMMENT 'Time appointment was canceled when applicable',
 NO_SHOW_FLAG           boolean COMMENT 'Indicates if patient did not show for appointment',
 CREATED_TIMESTAMP      timestamp NOT NULL,
 CREATED_BY_NAME        varchar(50) NOT NULL,
 UPDATED_TIMESTAMP      timestamp NOT NULL,
 UPDATED_BY_NAME        varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_APPOINTMENT PRIMARY KEY ( APPOINTMENT_KEY ),
 CONSTRAINT UK_FACT_APPOINTMENT_BK UNIQUE ( APPOINTMENT_ID ),
 CONSTRAINT fk_FACT_APPOINTMENT_DIM_APPOINTMENT_STATUS FOREIGN KEY ( APPOINTMENT_STATUS_KEY ) REFERENCES ANALYTICS.DIM_APPOINTMENT_STATUS ( APPOINTMENT_STATUS_KEY ),
 CONSTRAINT fk_FACT_APPOINTMENT_DIM_DATE FOREIGN KEY ( APPOINTMENT_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_APPOINTMENT_DIM_PATIENT FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY )
)
CLUSTER BY ( APPOINTMENT_DATE_KEY, PATIENT_KEY )
COMMENT = 'Appointment fact table, one row per scheduled appointment.';

-- ************************************** ANALYTICS.PATIENT_CARE_TASKS
CREATE HYBRID TABLE ANALYTICS.PATIENT_CARE_TASKS
(
 TASK_KEY          number(38,0) NOT NULL COMMENT 'Surrogate key for patient care task',
 PATIENT_KEY       number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 PROVIDER_KEY      number(38,0) COMMENT 'Provider responsible for task',
 TASK_TYPE         varchar(100) NOT NULL COMMENT 'Type of task, for example Follow-up, Reminder, Lab Review',
 TASK_STATUS       varchar(50) NOT NULL COMMENT 'Status of the task, for example Open, Completed, In Progress',
 PRIORITY_LEVEL    varchar(50) COMMENT 'Priority such as Low, Medium, High, Urgent',
 DUE_DATE_KEY      number(8,0) COMMENT 'Date task is due',
 CREATED_TIMESTAMP timestamp NOT NULL,
 UPDATED_TIMESTAMP timestamp NOT NULL,
 NOTES             varchar(2000) COMMENT 'Optional notes or comments about the task',
 CREATED_BY_NAME   varchar(50) NOT NULL,
 UPDATED_BY_NAME   varchar(50) NOT NULL,

 CONSTRAINT pk_PATIENT_CARE_TASKS PRIMARY KEY ( TASK_KEY ),
 CONSTRAINT fk_PATIENT_CARE_TASKS_ FOREIGN KEY ( DUE_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_PATIENT_CARE_TASKS__1 FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY ),
 CONSTRAINT fk_PATIENT_CARE_TASKS__2 FOREIGN KEY ( PROVIDER_KEY ) REFERENCES ANALYTICS.DIM_PROVIDER ( PROVIDER_KEY )
)
COMMENT = 'Hybrid table for real-time patient care management tasks requiring frequent updates.';

-- ************************************** ANALYTICS.ICE_ARCHIVE_LAB_RESULTS
CREATE ICEBERG TABLE ANALYTICS.ICE_ARCHIVE_LAB_RESULTS
(
 ARCHIVE_KEY       string NOT NULL,
 LAB_RESULT_KEY    number,
 PATIENT_ID        string,
 LAB_TEST_CODE     string,
 RESULT_VALUE      string,
 RESULT_TIMESTAMP  timestamp_ntz,
 ARCHIVED_AT       timestamp_ntz DEFAULT CURRENT_TIMESTAMP(),
 CREATED_TIMESTAMP timestamp NOT NULL,
 CREATED_BY_NAME   varchar(50) NOT NULL,
 UPDATED_TIMESTAMP timestamp NOT NULL,
 UPDATED_BY_NAME   varchar(50) NOT NULL,

 CONSTRAINT pk_ICE_ARCHIVE_LAB_RESULTS PRIMARY KEY ( ARCHIVE_KEY )
)
BASE_LOCATION = 'iceberg/archive_lab_results/'
EXTERNAL_VOLUME = 'MY_ICEBERG_VOL'
CATALOG = 'SNOWFLAKE'
REPLACE_INVALID_CHARACTERS = FALSE
AUTO_REFRESH = FALSE;

-- ************************************** ANALYTICS.DYN_PATIENT_RECENT_ENCOUNTERS
CREATE DYNAMIC TABLE ANALYTICS.DYN_PATIENT_RECENT_ENCOUNTERS
(
 PATIENT_KEY,
 PATIENT_ID,
 ENCOUNTER_KEY,
 ENCOUNTER_ID,
 ADMIT_DATE_KEY,
 DISCHARGE_DATE_KEY,
 ENCOUNTER_TYPE,
 LENGTH_OF_STAY_DAYS,
 TOTAL_CHARGES_AMOUNT,
 TOTAL_PAYMENTS_AMOUNT,
 READMISSION_FLAG,
 PROVIDER_KEY,
 ATTENDING_PROVIDER,
 FACILITY_KEY,
 FACILITY_NAME,
 LAST_ENCOUNTER_DATE,
 CREATED_TIMESTAMP,
 CREATED_BY_NAME,
 UPDATED_TIMESTAMP,
 UPDATED_BY_NAME
)
WAREHOUSE = COMPUTE_WH
TARGET_LAG = '5 MINUTES'
INITIALIZE = ON_CREATE
REFRESH_MODE = AUTO
  AS SELECT
    e.PATIENT_KEY,
    p.PATIENT_ID,
    e.ENCOUNTER_KEY,
    e.ENCOUNTER_ID,
    e.ADMIT_DATE_KEY,
    e.DISCHARGE_DATE_KEY,
    e.ENCOUNTER_TYPE,
    e.LENGTH_OF_STAY_DAYS,
    e.TOTAL_CHARGES_AMOUNT,
    e.TOTAL_PAYMENTS_AMOUNT,
    e.READMISSION_FLAG,
    pr.PROVIDER_KEY,
    pr.PROVIDER_NAME AS ATTENDING_PROVIDER,
    f.FACILITY_KEY,
    f.FACILITY_NAME,
    d.CALENDAR_DATE AS LAST_ENCOUNTER_DATE
FROM ANALYTICS.FACT_ENCOUNTER e
JOIN ANALYTICS.DIM_PATIENT p
    ON e.PATIENT_KEY = p.PATIENT_KEY
LEFT JOIN ANALYTICS.DIM_PROVIDER pr
    ON e.PROVIDER_KEY = pr.PROVIDER_KEY
LEFT JOIN ANALYTICS.DIM_FACILITY f
    ON e.FACILITY_KEY = f.FACILITY_KEY
LEFT JOIN ANALYTICS.DIM_DATE d
    ON e.ADMIT_DATE_KEY = d.DATE_KEY
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY e.PATIENT_KEY 
    ORDER BY e.ADMIT_DATE_KEY DESC
) = 1;

-- ************************************** ANALYTICS.VW_PROVIDER_PERFORMANCE
CREATE VIEW ANALYTICS.VW_PROVIDER_PERFORMANCE
(
  CREATED_TIMESTAMP,
  CREATED_BY_NAME,
  UPDATED_TIMESTAMP,
  UPDATED_BY_NAME
)
AS
SELECT 
    pr.PROVIDER_KEY,
    pr.PROVIDER_ID,
    pr.PROVIDER_NPI,
    pr.PROVIDER_NAME,
    pr.SPECIALTY,
    pr.SUBSPECIALTY,
    f.FACILITY_KEY,
    f.FACILITY_ID,
    f.FACILITY_NAME,
    COUNT(DISTINCT e.ENCOUNTER_KEY) AS TOTAL_ENCOUNTERS,
    COUNT(DISTINCT CASE WHEN e.READMISSION_FLAG = TRUE THEN e.ENCOUNTER_KEY END) AS READMISSION_COUNT,
    ROUND(COUNT(DISTINCT CASE WHEN e.READMISSION_FLAG = TRUE THEN e.ENCOUNTER_KEY END)::FLOAT / 
          NULLIF(COUNT(DISTINCT e.ENCOUNTER_KEY), 0) * 100, 2) AS READMISSION_RATE,
    ROUND(AVG(e.LENGTH_OF_STAY_DAYS), 2) AS AVG_LENGTH_OF_STAY,
    SUM(e.TOTAL_CHARGES_AMOUNT) AS TOTAL_CHARGES,
    SUM(e.TOTAL_PAYMENTS_AMOUNT) AS TOTAL_PAYMENTS,
    COUNT(DISTINCT fp.PROCEDURE_FACT_KEY) AS TOTAL_PROCEDURES,
    ROUND(AVG(COALESCE(fp.ANESTHESIA_MINUTES, 0)), 2) AS AVG_ANESTHESIA_MINUTES
FROM ANALYTICS.DIM_PROVIDER pr
LEFT JOIN ANALYTICS.DIM_FACILITY f ON 1=1
LEFT JOIN ANALYTICS.FACT_ENCOUNTER e ON pr.PROVIDER_KEY = e.PROVIDER_KEY AND f.FACILITY_KEY = e.FACILITY_KEY
LEFT JOIN ANALYTICS.FACT_PROCEDURE fp ON e.ENCOUNTER_KEY = fp.ENCOUNTER_KEY
WHERE pr.IS_CURRENT = TRUE AND pr.ACTIVE_FLAG = TRUE
GROUP BY 
    pr.PROVIDER_KEY,
    pr.PROVIDER_ID,
    pr.PROVIDER_NPI,
    pr.PROVIDER_NAME,
    pr.SPECIALTY,
    pr.SUBSPECIALTY,
    f.FACILITY_KEY,
    f.FACILITY_ID,
    f.FACILITY_NAME;


-- ************************************** ANALYTICS.VW_PATIENT_ENCOUNTER_SUMMARY
CREATE VIEW ANALYTICS.VW_PATIENT_ENCOUNTER_SUMMARY
(
  ENCOUNTER_KEY,
  ENCOUNTER_ID,
  PATIENT_KEY,
  PATIENT_ID,
  FIRST_NAME,
  LAST_NAME,
  DATE_OF_BIRTH,
  GENDER,
  PROVIDER_KEY,
  PROVIDER_ID,
  PROVIDER_NAME,
  SPECIALTY,
  FACILITY_KEY,
  FACILITY_ID,
  FACILITY_NAME,
  FACILITY_TYPE,
  DEPARTMENT_KEY,
  DEPARTMENT_ID,
  DEPARTMENT_NAME,
  SERVICE_LINE,
  LOCATION_KEY,
  LOCATION_ID,
  LOCATION_NAME,
  PAYER_PLAN_KEY,
  PAYER_PLAN_ID,
  PAYER_NAME,
  PLAN_NAME,
  INSURANCE_COVERAGE_KEY,
  COVERAGE_TIER,
  ADMIT_DATE,
  DISCHARGE_DATE,
  ENCOUNTER_TYPE,
  ENCOUNTER_CLASS,
  LENGTH_OF_STAY_DAYS,
  TOTAL_CHARGES_AMOUNT,
  TOTAL_PAYMENTS_AMOUNT,
  EADMISSION_FLAG,
  WRITE_OFF_AMOUNT,
  CREATED_TIMESTAMP,
  CREATED_BY_NAME,
  UPDATED_TIMESTAMP,
  UPDATED_BY_NAME
)
AS
SELECT 
    e.ENCOUNTER_KEY,
    e.ENCOUNTER_ID,
    p.PATIENT_KEY,
    p.PATIENT_ID,
    p.FIRST_NAME,
    p.LAST_NAME,
    p.DATE_OF_BIRTH,
    p.GENDER,
    pr.PROVIDER_KEY,
    pr.PROVIDER_ID,
    pr.PROVIDER_NAME,
    pr.SPECIALTY,
    f.FACILITY_KEY,
    f.FACILITY_ID,
    f.FACILITY_NAME,
    f.FACILITY_TYPE,
    d.DEPARTMENT_KEY,
    d.DEPARTMENT_ID,
    d.DEPARTMENT_NAME,
    d.SERVICE_LINE,
    l.LOCATION_KEY,
    l.LOCATION_ID,
    l.LOCATION_NAME,
    pp.PAYER_PLAN_KEY,
    pp.PAYER_PLAN_ID,
    pp.PAYER_NAME,
    pp.PLAN_NAME,
    ic.INSURANCE_COVERAGE_KEY,
    ic.COVERAGE_TIER,
    dd_admit.CALENDAR_DATE AS ADMIT_DATE,
    dd_discharge.CALENDAR_DATE AS DISCHARGE_DATE,
    e.ENCOUNTER_TYPE,
    e.ENCOUNTER_CLASS,
    e.LENGTH_OF_STAY_DAYS,
    e.TOTAL_CHARGES_AMOUNT,
    e.TOTAL_PAYMENTS_AMOUNT,
    e.READMISSION_FLAG,
    (e.TOTAL_CHARGES_AMOUNT - e.TOTAL_PAYMENTS_AMOUNT) AS WRITE_OFF_AMOUNT
FROM ANALYTICS.FACT_ENCOUNTER e
LEFT JOIN ANALYTICS.DIM_PATIENT p ON e.PATIENT_KEY = p.PATIENT_KEY AND p.IS_CURRENT = TRUE
LEFT JOIN ANALYTICS.DIM_PROVIDER pr ON e.PROVIDER_KEY = pr.PROVIDER_KEY AND pr.IS_CURRENT = TRUE
LEFT JOIN ANALYTICS.DIM_FACILITY f ON e.FACILITY_KEY = f.FACILITY_KEY AND f.IS_CURRENT = TRUE
LEFT JOIN ANALYTICS.DIM_DEPARTMENT d ON e.DEPARTMENT_KEY = d.DEPARTMENT_KEY
LEFT JOIN ANALYTICS.DIM_LOCATION l ON e.LOCATION_KEY = l.LOCATION_KEY
LEFT JOIN ANALYTICS.DIM_PAYER_PLAN pp ON e.PAYER_PLAN_KEY = pp.PAYER_PLAN_KEY AND pp.IS_CURRENT = TRUE
LEFT JOIN ANALYTICS.DIM_INSURANCE_COVERAGE ic ON e.INSURANCE_COVERAGE_KEY = ic.INSURANCE_COVERAGE_KEY AND ic.IS_CURRENT = TRUE
LEFT JOIN ANALYTICS.DIM_DATE dd_admit ON e.ADMIT_DATE_KEY = dd_admit.DATE_KEY
LEFT JOIN ANALYTICS.DIM_DATE dd_discharge ON e.DISCHARGE_DATE_KEY = dd_discharge.DATE_KEY;


-- ************************************** ANALYTICS.VW_PATIENT_CLINICAL_SUMMARY
CREATE VIEW ANALYTICS.VW_PATIENT_CLINICAL_SUMMARY
(
  CREATED_TIMESTAMP,
  CREATED_BY_NAME,
  UPDATED_TIMESTAMP,
  UPDATED_BY_NAME
)
AS
SELECT 
    e.ENCOUNTER_KEY,
    e.ENCOUNTER_ID,
    p.PATIENT_KEY,
    p.PATIENT_ID,
    p.FIRST_NAME,
    p.LAST_NAME,
    dd.CALENDAR_DATE AS ENCOUNTER_DATE,
    COUNT(DISTINCT fd.DIAGNOSIS_FACT_KEY) AS DIAGNOSIS_COUNT,
    COUNT(DISTINCT fp.PROCEDURE_FACT_KEY) AS PROCEDURE_COUNT,
    COUNT(DISTINCT fm.MEDICATION_ORDER_KEY) AS MEDICATION_COUNT,
    COUNT(DISTINCT flr.LAB_RESULT_KEY) AS LAB_RESULT_COUNT,
    SUM(CASE WHEN flr.ABNORMAL_FLAG = 'Y' THEN 1 ELSE 0 END) AS ABNORMAL_LAB_COUNT,
    STRING_AGG(DISTINCT rdc.DIAGNOSIS_DESCRIPTION, ', ') AS DIAGNOSIS_LIST,
    STRING_AGG(DISTINCT rpc.PROCEDURE_DESCRIPTION, ', ') AS PROCEDURE_LIST
FROM ANALYTICS.FACT_ENCOUNTER e
LEFT JOIN ANALYTICS.DIM_PATIENT p ON e.PATIENT_KEY = p.PATIENT_KEY AND p.IS_CURRENT = TRUE
LEFT JOIN ANALYTICS.DIM_DATE dd ON e.ADMIT_DATE_KEY = dd.DATE_KEY
LEFT JOIN ANALYTICS.FACT_DIAGNOSIS fd ON e.ENCOUNTER_KEY = fd.ENCOUNTER_KEY
LEFT JOIN ANALYTICS.REF_DIAGNOSIS_CODE rdc ON fd.DIAGNOSIS_CODE = rdc.DIAGNOSIS_CODE AND rdc.IS_ACTIVE = TRUE
LEFT JOIN ANALYTICS.FACT_PROCEDURE fp ON e.ENCOUNTER_KEY = fp.ENCOUNTER_KEY
LEFT JOIN ANALYTICS.REF_PROCEDURE_CODE rpc ON fp.PROCEDURE_CODE = rpc.PROCEDURE_CODE AND rpc.IS_ACTIVE = TRUE
LEFT JOIN ANALYTICS.FACT_MEDICATION_ORDER fm ON e.ENCOUNTER_KEY = fm.ENCOUNTER_KEY
LEFT JOIN ANALYTICS.FACT_LAB_RESULT flr ON e.ENCOUNTER_KEY = flr.ENCOUNTER_KEY
GROUP BY 
    e.ENCOUNTER_KEY,
    e.ENCOUNTER_ID,
    p.PATIENT_KEY,
    p.PATIENT_ID,
    p.FIRST_NAME,
    p.LAST_NAME,
    dd.CALENDAR_DATE;


-- ************************************** ANALYTICS.VW_CLAIM_ANALYSIS
CREATE VIEW ANALYTICS.VW_CLAIM_ANALYSIS
(
  CREATED_TIMESTAMP,
  CREATED_BY_NAME,
  UPDATED_TIMESTAMP,
  UPDATED_BY_NAME
)
AS
SELECT 
    c.CLAIM_KEY,
    c.CLAIM_ID,
    p.PATIENT_KEY,
    p.PATIENT_ID,
    p.FIRST_NAME || ' ' || p.LAST_NAME AS PATIENT_NAME,
    pp.PAYER_PLAN_KEY,
    pp.PAYER_PLAN_ID,
    pp.PAYER_NAME,
    pp.PLAN_NAME,
    dd_submit.CALENDAR_DATE AS CLAIM_SUBMIT_DATE,
    dd_paid.CALENDAR_DATE AS CLAIM_PAID_DATE,
    c.CLAIM_STATUS,
    c.CLAIM_TYPE,
    c.TOTAL_BILLED_AMOUNT,
    c.TOTAL_ALLOWED_AMOUNT,
    c.TOTAL_PAID_AMOUNT,
    c.TOTAL_DENIED_AMOUNT,
    (c.TOTAL_BILLED_AMOUNT - c.TOTAL_ALLOWED_AMOUNT) AS CONTRACTUAL_ADJUSTMENT,
    (c.TOTAL_ALLOWED_AMOUNT - c.TOTAL_PAID_AMOUNT) AS PATIENT_RESPONSIBILITY,
    COUNT(DISTINCT ccl.CLAIM_LINE_KEY) AS LINE_ITEM_COUNT,
    SUM(ccl.LINE_BILLED_AMOUNT) AS SUM_LINE_BILLED,
    SUM(ccl.LINE_ALLOWED_AMOUNT) AS SUM_LINE_ALLOWED,
    SUM(ccl.LINE_PAID_AMOUNT) AS SUM_LINE_PAID
FROM ANALYTICS.FACT_CLAIM c
LEFT JOIN ANALYTICS.DIM_PATIENT p ON c.PATIENT_KEY = p.PATIENT_KEY AND p.IS_CURRENT = TRUE
LEFT JOIN ANALYTICS.DIM_PAYER_PLAN pp ON c.PAYER_PLAN_KEY = pp.PAYER_PLAN_KEY AND pp.IS_CURRENT = TRUE
LEFT JOIN ANALYTICS.DIM_DATE dd_submit ON c.CLAIM_SUBMIT_DATE_KEY = dd_submit.DATE_KEY
LEFT JOIN ANALYTICS.DIM_DATE dd_paid ON c.CLAIM_PAID_DATE_KEY = dd_paid.DATE_KEY
LEFT JOIN ANALYTICS.FACT_CLAIM_LINE ccl ON c.CLAIM_KEY = ccl.CLAIM_KEY
GROUP BY 
    c.CLAIM_KEY,
    c.CLAIM_ID,
    p.PATIENT_KEY,
    p.PATIENT_ID,
    p.FIRST_NAME,
    p.LAST_NAME,
    pp.PAYER_PLAN_KEY,
    pp.PAYER_PLAN_ID,
    pp.PAYER_NAME,
    pp.PLAN_NAME,
    dd_submit.CALENDAR_DATE,
    dd_paid.CALENDAR_DATE,
    c.CLAIM_STATUS,
    c.CLAIM_TYPE,
    c.TOTAL_BILLED_AMOUNT,
    c.TOTAL_ALLOWED_AMOUNT,
    c.TOTAL_PAID_AMOUNT,
    c.TOTAL_DENIED_AMOUNT;


-- ************************************** ANALYTICS.MV_PATIENT_RISK_SUMMARY
CREATE MATERIALIZED VIEW ANALYTICS.MV_PATIENT_RISK_SUMMARY
(
  CREATED_TIMESTAMP,
  CREATED_BY_NAME,
  UPDATED_TIMESTAMP,
  UPDATED_BY_NAME
)
AS
SELECT 
    p.PATIENT_KEY,
    p.PATIENT_ID,
    p.FIRST_NAME,
    p.LAST_NAME,
    p.DATE_OF_BIRTH,
    p.GENDER,
    pr.RISK_SCORE,
    pr.RISK_SCORE_MODEL_NAME,
    pr.RISK_BAND,
    pr.HIGH_RISK_FLAG,
    dd.CALENDAR_DATE AS RISK_AS_OF_DATE,
    dd.YEAR_NUMBER AS RISK_YEAR,
    dd.MONTH_NUMBER AS RISK_MONTH,
    COUNT(DISTINCT e.ENCOUNTER_KEY) AS RECENT_ENCOUNTER_COUNT,
    SUM(CASE WHEN e.READMISSION_FLAG = TRUE THEN 1 ELSE 0 END) AS RECENT_READMISSION_COUNT,
    COUNT(DISTINCT fd.DIAGNOSIS_FACT_KEY) AS RECENT_DIAGNOSIS_COUNT,
    COUNT(DISTINCT fm.MEDICATION_ORDER_KEY) AS CURRENT_MEDICATION_COUNT,
    ROUND(AVG(e.LENGTH_OF_STAY_DAYS), 2) AS AVG_RECENT_LOS,
    ic.COVERAGE_TIER,
    pp.PAYER_NAME
FROM ANALYTICS.FACT_PATIENT_RISK pr
LEFT JOIN ANALYTICS.DIM_PATIENT p ON pr.PATIENT_KEY = p.PATIENT_KEY AND p.IS_CURRENT = TRUE
LEFT JOIN ANALYTICS.DIM_DATE dd ON pr.AS_OF_DATE_KEY = dd.DATE_KEY
LEFT JOIN ANALYTICS.FACT_ENCOUNTER e ON pr.PATIENT_KEY = e.PATIENT_KEY 
    AND e.ADMIT_DATE_KEY >= (pr.AS_OF_DATE_KEY - 18250)
    AND e.ADMIT_DATE_KEY <= pr.AS_OF_DATE_KEY
LEFT JOIN ANALYTICS.FACT_DIAGNOSIS fd ON e.ENCOUNTER_KEY = fd.ENCOUNTER_KEY
LEFT JOIN ANALYTICS.FACT_MEDICATION_ORDER fm ON e.ENCOUNTER_KEY = fm.ENCOUNTER_KEY
LEFT JOIN ANALYTICS.DIM_INSURANCE_COVERAGE ic ON e.INSURANCE_COVERAGE_KEY = ic.INSURANCE_COVERAGE_KEY 
    AND ic.IS_CURRENT = TRUE
LEFT JOIN ANALYTICS.DIM_PAYER_PLAN pp ON e.PAYER_PLAN_KEY = pp.PAYER_PLAN_KEY 
    AND pp.IS_CURRENT = TRUE
GROUP BY 
    p.PATIENT_KEY,
    p.PATIENT_ID,
    p.FIRST_NAME,
    p.LAST_NAME,
    p.DATE_OF_BIRTH,
    p.GENDER,
    pr.RISK_SCORE,
    pr.RISK_SCORE_MODEL_NAME,
    pr.RISK_BAND,
    pr.HIGH_RISK_FLAG,
    dd.CALENDAR_DATE,
    dd.YEAR_NUMBER,
    dd.MONTH_NUMBER,
    ic.COVERAGE_TIER,
    pp.PAYER_NAME;


-- ************************************** ANALYTICS.MV_ENCOUNTER_FINANCIAL_SUMMARY
CREATE MATERIALIZED VIEW ANALYTICS.MV_ENCOUNTER_FINANCIAL_SUMMARY
(
  CREATED_TIMESTAMP,
  CREATED_BY_NAME,
  UPDATED_TIMESTAMP,
  UPDATED_BY_NAME
)
AS
SELECT 
    e.ENCOUNTER_KEY,
    e.ENCOUNTER_ID,
    p.PATIENT_KEY,
    p.PATIENT_ID,
    pr.PROVIDER_KEY,
    pr.PROVIDER_ID,
    f.FACILITY_KEY,
    f.FACILITY_ID,
    pp.PAYER_PLAN_KEY,
    pp.PAYER_PLAN_ID,
    dd_admit.YEAR_NUMBER AS ENCOUNTER_YEAR,
    dd_admit.MONTH_NUMBER AS ENCOUNTER_MONTH,
    dd_admit.QUARTER_NUMBER AS ENCOUNTER_QUARTER,
    e.ENCOUNTER_TYPE,
    e.ENCOUNTER_CLASS,
    e.LENGTH_OF_STAY_DAYS,
    e.TOTAL_CHARGES_AMOUNT,
    e.TOTAL_PAYMENTS_AMOUNT,
    (e.TOTAL_CHARGES_AMOUNT - e.TOTAL_PAYMENTS_AMOUNT) AS WRITE_OFF_AMOUNT,
    e.READMISSION_FLAG,
    COUNT(DISTINCT ccl.CLAIM_LINE_KEY) AS CLAIM_LINE_COUNT,
    SUM(ccl.LINE_BILLED_AMOUNT) AS CLAIM_BILLED_AMOUNT,
    SUM(ccl.LINE_ALLOWED_AMOUNT) AS CLAIM_ALLOWED_AMOUNT,
    SUM(ccl.LINE_PAID_AMOUNT) AS CLAIM_PAID_AMOUNT,
    COUNT(DISTINCT fd.DIAGNOSIS_FACT_KEY) AS DIAGNOSIS_COUNT,
    COUNT(DISTINCT fp.PROCEDURE_FACT_KEY) AS PROCEDURE_COUNT
FROM ANALYTICS.FACT_ENCOUNTER e
LEFT JOIN ANALYTICS.DIM_PATIENT p ON e.PATIENT_KEY = p.PATIENT_KEY AND p.IS_CURRENT = TRUE
LEFT JOIN ANALYTICS.DIM_PROVIDER pr ON e.PROVIDER_KEY = pr.PROVIDER_KEY AND pr.IS_CURRENT = TRUE
LEFT JOIN ANALYTICS.DIM_FACILITY f ON e.FACILITY_KEY = f.FACILITY_KEY AND f.IS_CURRENT = TRUE
LEFT JOIN ANALYTICS.DIM_PAYER_PLAN pp ON e.PAYER_PLAN_KEY = pp.PAYER_PLAN_KEY AND pp.IS_CURRENT = TRUE
LEFT JOIN ANALYTICS.DIM_DATE dd_admit ON e.ADMIT_DATE_KEY = dd_admit.DATE_KEY
LEFT JOIN ANALYTICS.FACT_CLAIM_LINE ccl ON e.ENCOUNTER_KEY = ccl.CLAIM_KEY
LEFT JOIN ANALYTICS.FACT_DIAGNOSIS fd ON e.ENCOUNTER_KEY = fd.ENCOUNTER_KEY
LEFT JOIN ANALYTICS.FACT_PROCEDURE fp ON e.ENCOUNTER_KEY = fp.ENCOUNTER_KEY
GROUP BY 
    e.ENCOUNTER_KEY,
    e.ENCOUNTER_ID,
    p.PATIENT_KEY,
    p.PATIENT_ID,
    pr.PROVIDER_KEY,
    pr.PROVIDER_ID,
    f.FACILITY_KEY,
    f.FACILITY_ID,
    pp.PAYER_PLAN_KEY,
    pp.PAYER_PLAN_ID,
    dd_admit.YEAR_NUMBER,
    dd_admit.MONTH_NUMBER,
    dd_admit.QUARTER_NUMBER,
    e.ENCOUNTER_TYPE,
    e.ENCOUNTER_CLASS,
    e.LENGTH_OF_STAY_DAYS,
    e.TOTAL_CHARGES_AMOUNT,
    e.TOTAL_PAYMENTS_AMOUNT,
    e.READMISSION_FLAG;


-- ************************************** ANALYTICS.MV_DAILY_PROVIDER_METRICS
CREATE MATERIALIZED VIEW ANALYTICS.MV_DAILY_PROVIDER_METRICS
(
  CREATED_TIMESTAMP,
  CREATED_BY_NAME,
  UPDATED_TIMESTAMP,
  UPDATED_BY_NAME
)
AS
SELECT 
    pp.PROVIDER_PRODUCTIVITY_KEY,
    pp.PROVIDER_KEY,
    pr.PROVIDER_ID,
    pr.PROVIDER_NAME,
    pr.SPECIALTY,
    dd.DATE_KEY,
    dd.CALENDAR_DATE,
    dd.YEAR_NUMBER,
    dd.MONTH_NUMBER,
    dd.WEEK_OF_YEAR,
    dd.DAY_NAME,
    pp.ENCOUNTER_COUNT,
    pp.PROCEDURE_COUNT,
    pp.WORK_RVU_TOTAL,
    pp.CHARGES_TOTAL_AMOUNT,
    ROUND(pp.CHARGES_TOTAL_AMOUNT / NULLIF(pp.ENCOUNTER_COUNT, 0), 2) AS AVG_CHARGE_PER_ENCOUNTER,
    ROUND(pp.WORK_RVU_TOTAL / NULLIF(pp.ENCOUNTER_COUNT, 0), 4) AS AVG_RVU_PER_ENCOUNTER,
    COUNT(DISTINCT e.PATIENT_KEY) AS UNIQUE_PATIENT_COUNT
FROM ANALYTICS.FACT_PROVIDER_PRODUCTIVITY pp
LEFT JOIN ANALYTICS.DIM_PROVIDER pr ON pp.PROVIDER_KEY = pr.PROVIDER_KEY AND pr.IS_CURRENT = TRUE
LEFT JOIN ANALYTICS.DIM_DATE dd ON pp.DATE_KEY = dd.DATE_KEY
LEFT JOIN ANALYTICS.FACT_ENCOUNTER e ON pp.PROVIDER_KEY = e.PROVIDER_KEY AND pp.DATE_KEY = e.ADMIT_DATE_KEY
GROUP BY 
    pp.PROVIDER_PRODUCTIVITY_KEY,
    pp.PROVIDER_KEY,
    pr.PROVIDER_ID,
    pr.PROVIDER_NAME,
    pr.SPECIALTY,
    dd.DATE_KEY,
    dd.CALENDAR_DATE,
    dd.YEAR_NUMBER,
    dd.MONTH_NUMBER,
    dd.WEEK_OF_YEAR,
    dd.DAY_NAME,
    pp.ENCOUNTER_COUNT,
    pp.PROCEDURE_COUNT,
    pp.WORK_RVU_TOTAL,
    pp.CHARGES_TOTAL_AMOUNT;


