-- ************************************ SqlDBM: Snowflake ***********************************
-- * Generated by SqlDBM: Sample/Sample Project: Healthcare by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.PATIENT_CARE_TASKS
CREATE HYBRID TABLE ANALYTICS.PATIENT_CARE_TASKS
(
 TASK_KEY          number(38,0) NOT NULL COMMENT 'Surrogate key for patient care task',
 PATIENT_KEY       number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 PROVIDER_KEY      number(38,0) COMMENT 'Provider responsible for task',
 TASK_TYPE         varchar(100) NOT NULL COMMENT 'Type of task, for example Follow-up, Reminder, Lab Review',
 TASK_STATUS       varchar(50) NOT NULL COMMENT 'Status of the task, for example Open, Completed, In Progress',
 PRIORITY_LEVEL    varchar(50) COMMENT 'Priority such as Low, Medium, High, Urgent',
 DUE_DATE_KEY      number(8,0) COMMENT 'Date task is due',
 CREATED_TIMESTAMP timestamp NOT NULL,
 UPDATED_TIMESTAMP timestamp NOT NULL,
 NOTES             varchar(2000) COMMENT 'Optional notes or comments about the task',
 CREATED_BY_NAME   varchar(50) NOT NULL,
 UPDATED_BY_NAME   varchar(50) NOT NULL,

 CONSTRAINT pk_PATIENT_CARE_TASKS PRIMARY KEY ( TASK_KEY ),
 CONSTRAINT fk_PATIENT_CARE_TASKS_ FOREIGN KEY ( DUE_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_PATIENT_CARE_TASKS__1 FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY ),
 CONSTRAINT fk_PATIENT_CARE_TASKS__2 FOREIGN KEY ( PROVIDER_KEY ) REFERENCES ANALYTICS.DIM_PROVIDER ( PROVIDER_KEY )
)
COMMENT = 'Hybrid table for real-time patient care management tasks requiring frequent updates.';
