-- ************************************ SqlDBM: Snowflake ***********************************
-- * Generated by SqlDBM: Sample/Sample Project: Healthcare by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.DIM_PROVIDER
CREATE TABLE ANALYTICS.DIM_PROVIDER
(
 PROVIDER_KEY         number(38,0) NOT NULL COMMENT 'Surrogate key for the provider dimension',
 PROVIDER_ID          varchar(50) NOT NULL COMMENT 'Natural identifier for the provider from source system',
 EFFECTIVE_START_DATE date NOT NULL COMMENT 'Start date for this version of the provider record',
 EFFECTIVE_END_DATE   date COMMENT 'End date for this version of the provider record',
 IS_CURRENT           boolean NOT NULL DEFAULT TRUE COMMENT 'Indicates if this is the current provider row',
 PROVIDER_NPI         varchar(20) COMMENT 'National Provider Identifier or equivalent',
 PROVIDER_NAME        varchar(255) COMMENT 'Full provider name',
 PROVIDER_FIRST_NAME  varchar(100) COMMENT 'Provider first name',
 PROVIDER_LAST_NAME   varchar(100) COMMENT 'Provider last name',
 SPECIALTY            varchar(100) COMMENT 'Primary specialty',
 SUBSPECIALTY         varchar(100) COMMENT 'Subspecialty if applicable',
 EMPLOYMENT_TYPE      varchar(50) COMMENT 'Employment type, for example Employed, Contracted',
 ACTIVE_FLAG          boolean COMMENT 'Indicates if provider is active in the network',
 CREATED_TIMESTAMP    timestamp NOT NULL,
 CREATED_BY_NAME      varchar(50) NOT NULL,
 UPDATED_TIMESTAMP    timestamp NOT NULL,
 UPDATED_BY_NAME      varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_PROVIDER PRIMARY KEY ( PROVIDER_KEY ),
 CONSTRAINT UK_DIM_PROVIDER_BK_EFF UNIQUE ( PROVIDER_ID, EFFECTIVE_START_DATE )
)
COMMENT = 'Provider dimension with SCD2 tracking of changes such as specialty and employment.';
