-- ************************************ SqlDBM: Snowflake ***********************************
-- * Generated by SqlDBM: Sample/Sample Project: Healthcare by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.FACT_CLAIM_LINE
CREATE TABLE ANALYTICS.FACT_CLAIM_LINE
(
 CLAIM_LINE_KEY      number(38,0) NOT NULL COMMENT 'Surrogate key for claim line fact row',
 CLAIM_KEY           number(38,0) NOT NULL COMMENT 'Claim surrogate key reference value (no FK constraint)',
 CLAIM_ID            varchar(50) NOT NULL COMMENT 'Claim identifier from source system',
 LINE_NUMBER         number(5,0) NOT NULL COMMENT 'Line number within the claim',
 PATIENT_KEY         number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 PROVIDER_KEY        number(38,0) COMMENT 'Rendering provider for this line',
 FACILITY_KEY        number(38,0) COMMENT 'Facility where service was rendered',
 SERVICE_DATE_KEY    number(8,0) COMMENT 'Service date for this claim line',
 PROCEDURE_CODE      varchar(20) COMMENT 'Billed procedure code',
 DIAGNOSIS_CODE      varchar(20) COMMENT 'Primary diagnosis code attached to the line',
 UNITS_OF_SERVICE    number(10,2) COMMENT 'Units billed on this claim line',
 LINE_BILLED_AMOUNT  number(18,2) COMMENT 'Billed amount for the line',
 LINE_ALLOWED_AMOUNT number(18,2) COMMENT 'Allowed amount for the line',
 LINE_PAID_AMOUNT    number(18,2) COMMENT 'Paid amount for the line',
 CREATED_TIMESTAMP   timestamp NOT NULL,
 CREATED_BY_NAME     varchar(50) NOT NULL,
 UPDATED_TIMESTAMP   timestamp NOT NULL,
 UPDATED_BY_NAME     varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_CLAIM_LINE PRIMARY KEY ( CLAIM_LINE_KEY ),
 CONSTRAINT UK_FACT_CLAIM_LINE_BK UNIQUE ( CLAIM_ID, LINE_NUMBER ),
 CONSTRAINT fk_FACT_CLAIM_LINE_DIM_DATE FOREIGN KEY ( SERVICE_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_CLAIM_LINE_DIM_FACILITY FOREIGN KEY ( FACILITY_KEY ) REFERENCES ANALYTICS.DIM_FACILITY ( FACILITY_KEY ),
 CONSTRAINT fk_FACT_CLAIM_LINE_DIM_PATIENT FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY ),
 CONSTRAINT fk_FACT_CLAIM_LINE_DIM_PROVIDER FOREIGN KEY ( PROVIDER_KEY ) REFERENCES ANALYTICS.DIM_PROVIDER ( PROVIDER_KEY )
)
CLUSTER BY ( PATIENT_KEY, SERVICE_DATE_KEY )
COMMENT = 'Claim line fact table, one row per claim line item. Uses codes but no FK to reference tables.';
