-- ************************************ SqlDBM: Snowflake ***********************************
-- * Generated by SqlDBM: Sample/Sample Project: Healthcare by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.REF_PROCEDURE_CODE
CREATE TABLE ANALYTICS.REF_PROCEDURE_CODE
(
 PROCEDURE_CODE        varchar(20) NOT NULL COMMENT 'Procedure code, for example CPT or HCPCS',
 PROCEDURE_DESCRIPTION varchar(255) NOT NULL COMMENT 'Description of the procedure code',
 CODE_SYSTEM           varchar(50) NOT NULL COMMENT 'Code system, for example CPT',
 EFFECTIVE_START_DATE  date NOT NULL COMMENT 'Date the code became valid',
 EFFECTIVE_END_DATE    date COMMENT 'Date the code expired, if applicable',
 IS_ACTIVE             boolean NOT NULL DEFAULT TRUE COMMENT 'Indicates if the code is currently active',
 CREATED_TIMESTAMP     timestamp NOT NULL,
 CREATED_BY_NAME       varchar(50) NOT NULL,
 UPDATED_TIMESTAMP     timestamp NOT NULL,
 UPDATED_BY_NAME       varchar(50) NOT NULL,

 CONSTRAINT pk_REF_PROCEDURE_CODE PRIMARY KEY ( PROCEDURE_CODE )
)
COMMENT = 'Reference table for procedure codes, such as CPT.';
