-- ************************************ SqlDBM: Snowflake ***********************************
-- * Generated by SqlDBM: Sample/Sample Project: Healthcare by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.DIM_INSURANCE_COVERAGE
CREATE TABLE ANALYTICS.DIM_INSURANCE_COVERAGE
(
 INSURANCE_COVERAGE_KEY number(38,0) NOT NULL COMMENT 'Surrogate key for the insurance coverage dimension',
 PATIENT_ID             varchar(50) NOT NULL COMMENT 'Patient business key to link coverage to the patient',
 PAYER_PLAN_ID          varchar(50) NOT NULL COMMENT 'Business key of the payer plan',
 EFFECTIVE_START_DATE   date NOT NULL COMMENT 'Coverage effective start date',
 EFFECTIVE_END_DATE     date COMMENT 'Coverage effective end date',
 IS_CURRENT             boolean NOT NULL DEFAULT TRUE COMMENT 'Indicates if this is the current coverage row',
 COVERAGE_TIER          varchar(50) COMMENT 'Coverage tier, for example Employee, Spouse, Dependent',
 SUBSCRIBER_ID          varchar(50) COMMENT 'Subscriber identifier',
 GROUP_NUMBER           varchar(50) COMMENT 'Employer or group number',
 COB_PRIORITY           number(3,0) COMMENT 'Coordination of benefits priority, lower is primary',
 CREATED_TIMESTAMP      timestamp NOT NULL,
 CREATED_BY_NAME        varchar(50) NOT NULL,
 UPDATED_TIMESTAMP      timestamp NOT NULL,
 UPDATED_BY_NAME        varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_INSURANCE_COVERAGE PRIMARY KEY ( INSURANCE_COVERAGE_KEY ),
 CONSTRAINT UK_DIM_INSURANCE_COVERAGE_BK_EFF UNIQUE ( PAYER_PLAN_ID, EFFECTIVE_START_DATE, PATIENT_ID )
)
COMMENT = 'Insurance coverage dimension, SCD2, representing patient coverage periods.';
