-- ************************************ SqlDBM: Snowflake ***********************************
-- * Generated by SqlDBM: Sample/Sample Project: Healthcare by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.DIM_MEDICATION
CREATE TABLE ANALYTICS.DIM_MEDICATION
(
 MEDICATION_KEY    number(38,0) NOT NULL COMMENT 'Surrogate key for the medication dimension',
 MEDICATION_ID     varchar(50) NOT NULL COMMENT 'Medication identifier from source system or formulary',
 MEDICATION_NAME   varchar(255) NOT NULL COMMENT 'Display name for the medication',
 GENERIC_NAME      varchar(255) COMMENT 'Generic medication name',
 BRAND_NAME        varchar(255) COMMENT 'Brand name',
 THERAPEUTIC_CLASS varchar(255) COMMENT 'Therapeutic class',
 ROUTE_OF_ADMIN    varchar(100) COMMENT 'Route of administration, for example Oral, IV',
 FORM_STRENGTH     varchar(100) COMMENT 'Dose form and strength text',
 CREATED_TIMESTAMP timestamp NOT NULL,
 CREATED_BY_NAME   varchar(50) NOT NULL,
 UPDATED_TIMESTAMP timestamp NOT NULL,
 UPDATED_BY_NAME   varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_MEDICATION PRIMARY KEY ( MEDICATION_KEY ),
 CONSTRAINT UK_DIM_MEDICATION_BK UNIQUE ( MEDICATION_ID )
)
COMMENT = 'Medication dimension for orders and administrations.';
