-- ************************************ SqlDBM: Snowflake ***********************************
-- * Generated by SqlDBM: Sample/Sample Project: Healthcare by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.FACT_PROVIDER_PRODUCTIVITY
CREATE TABLE ANALYTICS.FACT_PROVIDER_PRODUCTIVITY
(
 PROVIDER_PRODUCTIVITY_KEY number(38,0) NOT NULL COMMENT 'Surrogate key for provider productivity fact row',
 PROVIDER_KEY              number(38,0) NOT NULL COMMENT 'Link to provider dimension',
 DATE_KEY                  number(8,0) NOT NULL COMMENT 'Date key for productivity aggregation',
 ENCOUNTER_COUNT           number(18,0) COMMENT 'Number of encounters for the provider on the date',
 PROCEDURE_COUNT           number(18,0) COMMENT 'Number of procedures performed',
 WORK_RVU_TOTAL            number(18,2) COMMENT 'Total work RVUs for the date',
 CHARGES_TOTAL_AMOUNT      number(18,2) COMMENT 'Total charges for the date',
 CREATED_TIMESTAMP         timestamp NOT NULL,
 CREATED_BY_NAME           varchar(50) NOT NULL,
 UPDATED_TIMESTAMP         timestamp NOT NULL,
 UPDATED_BY_NAME           varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_PROVIDER_PRODUCTIVITY PRIMARY KEY ( PROVIDER_PRODUCTIVITY_KEY ),
 CONSTRAINT UK_FACT_PROVIDER_PROD_BK UNIQUE ( PROVIDER_KEY, DATE_KEY ),
 CONSTRAINT fk_FACT_PROVIDER_PRODUCTIVITY_DIM_DATE FOREIGN KEY ( DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_PROVIDER_PRODUCTIVITY_DIM_PROVIDER FOREIGN KEY ( PROVIDER_KEY ) REFERENCES ANALYTICS.DIM_PROVIDER ( PROVIDER_KEY )
)
CLUSTER BY ( DATE_KEY, PROVIDER_KEY )
COMMENT = 'Provider productivity fact table, usually aggregated at daily grain.';
