-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.V_CUSTOMER_ORDER_HISTORY_VW
CREATE VIEW SUPPLYCHAIN.V_CUSTOMER_ORDER_HISTORY_VW
(
  CUSTOMER_KEY COMMENT 'Unique key identifying the customer',
  CUSTOMER_ID COMMENT 'Business identifier for the customer',
  FIRST_NAME COMMENT 'Customer''s first name',
  LAST_NAME COMMENT 'Customer''s last name',
  SEGMENT COMMENT 'Customer segmentation category',
  DW_CREATED_TS,
  CREATED_BY,
  UPDATED_TS,
  UPDATED_BY,
  IS_UPDATED
)
COMMENT = 'View providing a comprehensive summary of customer order history and behavior.'
AS
SELECT 
    dc.customer_key,
    dc.customer_id,
    dc.first_name,
    dc.last_name,
    dc.segment,
    COUNT(DISTINCT fso.sales_order_key) AS total_orders,
    SUM(fso.total_price) AS total_spend,
    AVG(fso.total_price) AS avg_order_value,
    MAX(d.full_date) AS most_recent_order_date,
    SUM(fso.quantity) AS total_items_purchased
FROM 
    Dim_Customer dc
JOIN 
    Fact_Sales_Order fso ON dc.customer_key = fso.customer_key
JOIN 
    Dim_Date d ON fso.order_date_key = d.date_key
GROUP BY 
    dc.customer_key,
    dc.customer_id,
    dc.first_name,
    dc.last_name,
    dc.segment;

