-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.CUSTOMER_MV
CREATE MATERIALIZED VIEW SUPPLYCHAIN.CUSTOMER_MV
(
  CUSTOMERID,
  CUSTOMERNAME,
  CONTACTNAME,
  CONTACTTITLE,
  ADDRESS,
  CITY,
  STATE,
  ZIPCODE,
  COUNTRY,
  PHONE,
  EMAIL,
  CUSTOMERTYPE
)
AS
select * from SUPPLYCHAIN.CUSTOMER
where customerid=2;

