-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.V_INVENTORY_SALES_CORRELATION_VW
CREATE VIEW SUPPLYCHAIN.V_INVENTORY_SALES_CORRELATION_VW
(
  PRODUCT_KEY COMMENT 'Unique identifier for the product',
  PRODUCT_NAME COMMENT 'Name of the product',
  CATEGORY COMMENT 'Product category',
  SUB_CATEGORY COMMENT 'Product subcategory',
  STORE_NAME COMMENT 'Name of the store',
  BEGINNING_INVENTORY_QUANTITY COMMENT 'Inventory quantity at the start of the period',
  RECEIVED_QUANTITY COMMENT 'Number of units received',
  SOLD_QUANTITY COMMENT 'Number of units sold',
  RETURNED_QUANTITY COMMENT 'Number of units returned',
  ENDING_INVENTORY_QUANTITY COMMENT 'Inventory quantity at the end of the period',
  TOTAL_SALES COMMENT 'Total sales amount',
  INVENTORY_TURNOVER_RATIO COMMENT 'Ratio of sold quantity to beginning inventory',
  DW_CREATED_TS,
  CREATED_BY,
  UPDATED_TS,
  UPDATED_BY,
  IS_UPDATED
)
COMMENT = 'View analyzing the relationship between inventory levels and sales performance.'
AS
SELECT 
    dp.product_key,
    dp.product_name,
    dp.category,
    dp.sub_category,
    ds.store_name,
    fi.beginning_inventory_quantity,
    fi.received_quantity,
    fi.sold_quantity,
    fi.returned_quantity,
    fi.ending_inventory_quantity,
    fso.total_price AS total_sales,
    (fi.sold_quantity * 1.0 / NULLIF(fi.beginning_inventory_quantity, 0)) AS inventory_turnover_ratio
FROM 
    Fact_Inventory fi
JOIN 
    Dim_Product dp ON fi.product_key = dp.product_key
JOIN 
    Dim_Store ds ON fi.store_key = ds.store_key
LEFT JOIN 
    Fact_Sales_Order fso ON fi.product_key = fso.product_key 
    AND fi.store_key = fso.store_key 
    AND fi.date_key = fso.order_date_key;

