-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.V_SALES_PERFORMANCE_VW
CREATE VIEW SUPPLYCHAIN.V_SALES_PERFORMANCE_VW
(
  YEAR COMMENT 'Calendar year of sales',
  QUARTER COMMENT 'Calendar quarter of sales',
  MONTH_NAME COMMENT 'Month of sales',
  DEPARTMENT COMMENT 'Department responsible for sales',
  SALES_TERRITORY COMMENT 'Sales territory of the performance',
  TOTAL_SALES_AMOUNT COMMENT 'Total monetary value of sales',
  TOTAL_UNITS_SOLD COMMENT 'Total number of units sold',
  AVG_UNIT_PRICE COMMENT 'Average price per unit sold',
  TOTAL_DISCOUNTS COMMENT 'Total discounts applied',
  TOTAL_TAX COMMENT 'Total tax collected',
  TOTAL_ORDERS COMMENT 'Total number of orders',
  DW_CREATED_TS,
  CREATED_BY,
  UPDATED_TS,
  UPDATED_BY,
  IS_UPDATED
)
COMMENT = 'View providing a detailed analysis of sales performance across various dimensions.'
AS
SELECT 
    d.year,
    d.quarter,
    d.month_name,
    e.department,
    e.sales_territory,
    SUM(fso.total_price) AS total_sales_amount,
    SUM(fso.quantity) AS total_units_sold,
    AVG(fso.unit_price) AS avg_unit_price,
    SUM(fso.discount_amount) AS total_discounts,
    SUM(fso.tax_amount) AS total_tax,
    COUNT(DISTINCT fso.sales_order_key) AS total_orders
FROM 
    Fact_Sales_Order fso
JOIN 
    Dim_Date d ON fso.order_date_key = d.date_key
JOIN 
    Dim_Employee e ON fso.employee_key = e.employee_key
GROUP BY 
    d.year, 
    d.quarter, 
    d.month_name,
    e.department,
    e.sales_territory;

