-- ************************************************** SqlDBM: Snowflake **************************************************
-- * Generated by SqlDBM: Healthcare Sample Project  [from PROD] - 12/1/2025 10:47:29 PM by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.DIM_PATIENT
CREATE TABLE ANALYTICS.DIM_PATIENT
(
 PATIENT_KEY          number(38,0) NOT NULL COMMENT 'Surrogate key for the patient dimension',
 PATIENT_ID           varchar(50) NOT NULL COMMENT 'Natural business identifier for the patient from source system',
 EFFECTIVE_START_DATE date NOT NULL COMMENT 'Start date for this version of the patient record',
 EFFECTIVE_END_DATE   date COMMENT 'End date for this version of the patient record',
 IS_CURRENT           boolean NOT NULL DEFAULT TRUE COMMENT 'Indicates if this is the current version of the patient record',
 FIRST_NAME           varchar(100) COMMENT 'Patient first name',
 LAST_NAME            varchar(100) COMMENT 'Patient last name',
 DATE_OF_BIRTH        date COMMENT 'Patient date of birth',
 GENDER               varchar(50) COMMENT 'Gender as stored in the source system',
 MARITAL_STATUS       varchar(50) COMMENT 'Marital status',
 EMAIL_ADDRESS        varchar(255) COMMENT 'Patient email address',
 PHONE_NUMBER         varchar(50) COMMENT 'Primary phone number',
 ADDRESS_LINE_1       varchar(255) COMMENT 'Primary street address line 1',
 ADDRESS_LINE_2       varchar(255) COMMENT 'Primary street address line 2',
 CITY                 varchar(100) COMMENT 'Patient city',
 STATE_PROVINCE       varchar(50) COMMENT 'Patient state or province',
 POSTAL_CODE          varchar(20) COMMENT 'Postal or ZIP code',
 COUNTRY              varchar(100) COMMENT 'Patient country',
 PRIMARY_LANGUAGE     varchar(100) COMMENT 'Primary language',
 RACE_ETHNICITY       varchar(100) COMMENT 'Race or ethnicity as captured in source',
 DECEASED_FLAG        boolean COMMENT 'Indicates if the patient is deceased',
 DECEASED_DATE        date COMMENT 'Date of death if available',
 CREATED_TIMESTAMP    timestamp NOT NULL,
 CREATED_BY_NAME      varchar(50) NOT NULL,
 UPDATED_TIMESTAMP    timestamp NOT NULL,
 UPDATED_BY_NAME      varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_PATIENT PRIMARY KEY ( PATIENT_KEY ),
 CONSTRAINT UK_DIM_PATIENT_BK_EFF UNIQUE ( PATIENT_ID, EFFECTIVE_START_DATE )
)
COMMENT = 'Patient dimension with SCD2 tracking of demographic changes.';
