-- ************************************ SqlDBM: Snowflake ***********************************
-- * Generated by SqlDBM: Sample/Sample Project: Healthcare by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.DIM_DATE
CREATE TABLE ANALYTICS.DIM_DATE
(
 DATE_KEY          number(8,0) NOT NULL COMMENT 'Surrogate key in YYYYMMDD format',
 CALENDAR_DATE     date NOT NULL COMMENT 'Actual calendar date',
 DAY_OF_WEEK       number(1,0) NOT NULL COMMENT 'Day of week as number, for example 1 = Monday',
 DAY_NAME          varchar(20) NOT NULL COMMENT 'Day of week name',
 DAY_OF_MONTH      number(2,0) NOT NULL COMMENT 'Day of month',
 DAY_OF_YEAR       number(3,0) NOT NULL COMMENT 'Day of year',
 WEEK_OF_YEAR      number(2,0) NOT NULL COMMENT 'Week of year number',
 MONTH_NUMBER      number(2,0) NOT NULL COMMENT 'Month number 1 to 12',
 MONTH_NAME        varchar(20) NOT NULL COMMENT 'Full month name',
 QUARTER_NUMBER    number(1,0) NOT NULL COMMENT 'Quarter number 1 to 4',
 YEAR_NUMBER       number(4,0) NOT NULL COMMENT 'Calendar year',
 IS_WEEKEND        boolean NOT NULL COMMENT 'Indicates if the date falls on a weekend',
 IS_HOLIDAY        boolean NOT NULL DEFAULT FALSE COMMENT 'Indicates if the date is a holiday in the local region',
 CREATED_TIMESTAMP timestamp NOT NULL,
 CREATED_BY_NAME   varchar(50) NOT NULL,
 UPDATED_TIMESTAMP timestamp NOT NULL,
 UPDATED_BY_NAME   varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_DATE PRIMARY KEY ( DATE_KEY ),
 CONSTRAINT UK_DIM_DATE UNIQUE ( CALENDAR_DATE )
)
COMMENT = 'Date dimension with standard calendar breakdown for analytics.';
