-- ************************************************** SqlDBM: Snowflake **************************************************
-- * Generated by SqlDBM: Healthcare Sample Project  [from PROD] - 12/1/2025 10:47:29 PM by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.FACT_PROCEDURE
CREATE TABLE ANALYTICS.FACT_PROCEDURE
(
 PROCEDURE_FACT_KEY     number(38,0) NOT NULL COMMENT 'Surrogate key for procedure fact row',
 ENCOUNTER_KEY          number(38,0) COMMENT 'Encounter surrogate key reference value (no FK constraint)',
 PATIENT_KEY            number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 PROVIDER_KEY           number(38,0) COMMENT 'Provider performing the procedure',
 PROCEDURE_CODE         varchar(20) NOT NULL COMMENT 'Procedure code',
 PROCEDURE_DATE_KEY     number(8,0) COMMENT 'Date key when procedure was performed',
 PRIMARY_PROCEDURE_FLAG boolean COMMENT 'Indicates if this was the primary procedure for the encounter',
 ANESTHESIA_MINUTES     number(5,0) COMMENT 'Anesthesia time in minutes if applicable',
 CREATED_TIMESTAMP      timestamp NOT NULL,
 CREATED_BY_NAME        varchar(50) NOT NULL,
 UPDATED_TIMESTAMP      timestamp NOT NULL,
 UPDATED_BY_NAME        varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_PROCEDURE PRIMARY KEY ( PROCEDURE_FACT_KEY ),
 CONSTRAINT fk_FACT_PROCEDURE_DIM_DATE FOREIGN KEY ( PROCEDURE_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_PROCEDURE_DIM_PATIENT FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY ),
 CONSTRAINT fk_FACT_PROCEDURE_DIM_PROVIDER FOREIGN KEY ( PROVIDER_KEY ) REFERENCES ANALYTICS.DIM_PROVIDER ( PROVIDER_KEY )
)
CLUSTER BY ( PROCEDURE_DATE_KEY, PATIENT_KEY )
COMMENT = 'Procedure fact table, one row per procedure performed.';
