-- ************************************ SqlDBM: Snowflake ***********************************
-- * Generated by SqlDBM: Sample/Sample Project: Healthcare by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.DIM_APPOINTMENT_STATUS
CREATE TABLE ANALYTICS.DIM_APPOINTMENT_STATUS
(
 APPOINTMENT_STATUS_KEY  number(38,0) NOT NULL COMMENT 'Surrogate key for appointment status dimension',
 APPOINTMENT_STATUS_CODE varchar(50) NOT NULL COMMENT 'Code for appointment status',
 APPOINTMENT_STATUS_NAME varchar(100) NOT NULL COMMENT 'Description of appointment status, for example Completed, Canceled, No show',
 CREATED_TIMESTAMP       timestamp NOT NULL,
 CREATED_BY_NAME         varchar(50) NOT NULL,
 UPDATED_TIMESTAMP       timestamp NOT NULL,
 UPDATED_BY_NAME         varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_APPOINTMENT_STATUS PRIMARY KEY ( APPOINTMENT_STATUS_KEY ),
 CONSTRAINT UK_DIM_APPOINTMENT_STATUS_BK UNIQUE ( APPOINTMENT_STATUS_CODE )
)
COMMENT = 'Appointment status dimension used by appointment facts.';
