-- ************************************************** SqlDBM: Snowflake **************************************************
-- * Generated by SqlDBM: Healthcare Sample Project  [from PROD] - 12/1/2025 10:47:29 PM by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.REF_DIAGNOSIS_CODE
CREATE TABLE ANALYTICS.REF_DIAGNOSIS_CODE
(
 DIAGNOSIS_CODE        varchar(20) NOT NULL COMMENT 'ICD diagnosis code',
 DIAGNOSIS_DESCRIPTION varchar(255) NOT NULL COMMENT 'Description of the diagnosis code',
 CODE_SYSTEM           varchar(50) NOT NULL COMMENT 'Code system, for example ICD-10',
 EFFECTIVE_START_DATE  date NOT NULL COMMENT 'Date the code became valid',
 EFFECTIVE_END_DATE    date COMMENT 'Date the code expired, if applicable',
 IS_ACTIVE             boolean NOT NULL DEFAULT TRUE COMMENT 'Indicates if the code is currently active',
 CREATED_TIMESTAMP     timestamp NOT NULL,
 CREATED_BY_NAME       varchar(50) NOT NULL,
 UPDATED_TIMESTAMP     timestamp NOT NULL,
 UPDATED_BY_NAME       varchar(50) NOT NULL,

 CONSTRAINT pk_REF_DIAGNOSIS_CODE PRIMARY KEY ( DIAGNOSIS_CODE )
)
COMMENT = 'Reference table for diagnosis codes, such as ICD-10.';
