-- ************************************ SqlDBM: Snowflake ***********************************
-- * Generated by SqlDBM: Sample/Sample Project: Healthcare by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.FACT_APPOINTMENT
CREATE TABLE ANALYTICS.FACT_APPOINTMENT
(
 APPOINTMENT_KEY        number(38,0) NOT NULL COMMENT 'Surrogate key for appointment fact row',
 APPOINTMENT_ID         varchar(50) NOT NULL COMMENT 'Appointment identifier from source system',
 PATIENT_KEY            number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 PROVIDER_KEY           number(38,0) COMMENT 'Provider with whom the appointment is scheduled',
 FACILITY_KEY           number(38,0) COMMENT 'Facility where appointment will occur',
 DEPARTMENT_KEY         number(38,0) COMMENT 'Department hosting the appointment',
 APPOINTMENT_DATE_KEY   number(8,0) COMMENT 'Date key for scheduled appointment date',
 APPOINTMENT_STATUS_KEY number(38,0) COMMENT 'Link to appointment status dimension',
 SCHEDULED_DATETIME     timestamp_ntz COMMENT 'Original scheduled date and time',
 CHECKIN_DATETIME       timestamp_ntz COMMENT 'Time patient checked in',
 CHECKOUT_DATETIME      timestamp_ntz COMMENT 'Time patient checked out',
 CANCEL_DATETIME        timestamp_ntz COMMENT 'Time appointment was canceled when applicable',
 NO_SHOW_FLAG           boolean COMMENT 'Indicates if patient did not show for appointment',
 CREATED_TIMESTAMP      timestamp NOT NULL,
 CREATED_BY_NAME        varchar(50) NOT NULL,
 UPDATED_TIMESTAMP      timestamp NOT NULL,
 UPDATED_BY_NAME        varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_APPOINTMENT PRIMARY KEY ( APPOINTMENT_KEY ),
 CONSTRAINT UK_FACT_APPOINTMENT_BK UNIQUE ( APPOINTMENT_ID ),
 CONSTRAINT fk_FACT_APPOINTMENT_DIM_APPOINTMENT_STATUS FOREIGN KEY ( APPOINTMENT_STATUS_KEY ) REFERENCES ANALYTICS.DIM_APPOINTMENT_STATUS ( APPOINTMENT_STATUS_KEY ),
 CONSTRAINT fk_FACT_APPOINTMENT_DIM_DATE FOREIGN KEY ( APPOINTMENT_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_APPOINTMENT_DIM_PATIENT FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY )
)
CLUSTER BY ( APPOINTMENT_DATE_KEY, PATIENT_KEY )
COMMENT = 'Appointment fact table, one row per scheduled appointment.';
