-- ************************************ SqlDBM: Snowflake ***********************************
-- * Generated by SqlDBM: Sample/Sample Project: Healthcare by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.FACT_CLAIM
CREATE TABLE ANALYTICS.FACT_CLAIM
(
 CLAIM_KEY             number(38,0) NOT NULL COMMENT 'Surrogate key for the claim fact row',
 CLAIM_ID              varchar(50) NOT NULL COMMENT 'Claim identifier from source system',
 PATIENT_KEY           number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 PAYER_PLAN_KEY        number(38,0) COMMENT 'Payer plan for the claim',
 CLAIM_SUBMIT_DATE_KEY number(8,0) COMMENT 'Date key when the claim was submitted',
 CLAIM_PAID_DATE_KEY   number(8,0) COMMENT 'Date key when the claim was paid',
 CLAIM_STATUS          varchar(50) COMMENT 'Current status of claim, for example Submitted, Pending, Paid, Denied',
 CLAIM_TYPE            varchar(50) COMMENT 'Claim type, for example Professional, Facility',
 TOTAL_BILLED_AMOUNT   number(18,2) COMMENT 'Total billed amount on the claim',
 TOTAL_ALLOWED_AMOUNT  number(18,2) COMMENT 'Total allowed amount after contract adjustments',
 TOTAL_PAID_AMOUNT     number(18,2) COMMENT 'Total paid amount from payer and patient combined',
 TOTAL_DENIED_AMOUNT   number(18,2) COMMENT 'Total denied amount',
 CREATED_TIMESTAMP     timestamp NOT NULL,
 CREATED_BY_NAME       varchar(50) NOT NULL,
 UPDATED_TIMESTAMP     timestamp NOT NULL,
 UPDATED_BY_NAME       varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_CLAIM PRIMARY KEY ( CLAIM_KEY ),
 CONSTRAINT UK_FACT_CLAIM_BK UNIQUE ( CLAIM_ID ),
 CONSTRAINT fk_FACT_CLAIM_DIM_DATE FOREIGN KEY ( CLAIM_SUBMIT_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_CLAIM_DIM_PATIENT FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY ),
 CONSTRAINT fk_FACT_CLAIM_DIM_PAYER_PLAN FOREIGN KEY ( PAYER_PLAN_KEY ) REFERENCES ANALYTICS.DIM_PAYER_PLAN ( PAYER_PLAN_KEY )
)
CLUSTER BY ( PATIENT_KEY, CLAIM_SUBMIT_DATE_KEY )
COMMENT = 'Claim fact table summarizing claim level financials.';
