-- ************************************************** SqlDBM: Snowflake **************************************************
-- * Generated by SqlDBM: Healthcare Sample Project  [from PROD] - 12/1/2025 10:47:29 PM by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.FACT_PATIENT_RISK
CREATE TABLE ANALYTICS.FACT_PATIENT_RISK
(
 PATIENT_RISK_KEY      number(38,0) NOT NULL COMMENT 'Surrogate key for patient risk fact row',
 PATIENT_KEY           number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 AS_OF_DATE_KEY        number(8,0) NOT NULL COMMENT 'Date key representing when the risk score was calculated',
 RISK_SCORE            number(9,4) COMMENT 'Calculated risk score for the patient',
 RISK_SCORE_MODEL_NAME varchar(100) COMMENT 'Name of the risk scoring model, for example HCC or custom model',
 RISK_BAND             varchar(50) COMMENT 'Bucket of risk such as Low, Medium, High',
 HIGH_RISK_FLAG        boolean COMMENT 'Indicates if patient is considered high risk',
 CREATED_TIMESTAMP     timestamp NOT NULL,
 CREATED_BY_NAME       varchar(50) NOT NULL,
 UPDATED_TIMESTAMP     timestamp NOT NULL,
 UPDATED_BY_NAME       varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_PATIENT_RISK PRIMARY KEY ( PATIENT_RISK_KEY ),
 CONSTRAINT UK_FACT_PATIENT_RISK_BK UNIQUE ( PATIENT_KEY, AS_OF_DATE_KEY, RISK_SCORE_MODEL_NAME ),
 CONSTRAINT fk_FACT_PATIENT_RISK_DIM_DATE FOREIGN KEY ( AS_OF_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_PATIENT_RISK_DIM_PATIENT FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY )
)
CLUSTER BY ( PATIENT_KEY, AS_OF_DATE_KEY )
COMMENT = 'Patient risk fact table, one row per patient per risk model and as of date.';
