-- ************************************************** SqlDBM: Snowflake **************************************************
-- * Generated by SqlDBM: Healthcare Sample Project  [from PROD] - 12/1/2025 10:47:29 PM by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.DIM_PAYER_PLAN
CREATE TABLE ANALYTICS.DIM_PAYER_PLAN
(
 PAYER_PLAN_KEY       number(38,0) NOT NULL COMMENT 'Surrogate key for the payer plan dimension',
 PAYER_PLAN_ID        varchar(50) NOT NULL COMMENT 'Natural identifier for the payer plan from source',
 EFFECTIVE_START_DATE date NOT NULL COMMENT 'Start date for this version of the payer plan record',
 EFFECTIVE_END_DATE   date COMMENT 'End date for this version of the payer plan record',
 IS_CURRENT           boolean NOT NULL DEFAULT TRUE COMMENT 'Indicates if this is the current payer plan row',
 PAYER_NAME           varchar(255) NOT NULL COMMENT 'Payer organization name',
 PLAN_NAME            varchar(255) NOT NULL COMMENT 'Insurance plan name',
 PLAN_TYPE            varchar(100) COMMENT 'Plan type, for example HMO, PPO, EPO',
 NETWORK_TYPE         varchar(100) COMMENT 'Network type, for example In-network, Out-of-network',
 METAL_TIER           varchar(50) COMMENT 'Metal tier for ACA plans, for example Bronze, Silver',
 ACTIVE_FLAG          boolean COMMENT 'Indicates if plan is active',
 CREATED_TIMESTAMP    timestamp NOT NULL,
 CREATED_BY_NAME      varchar(50) NOT NULL,
 UPDATED_TIMESTAMP    timestamp NOT NULL,
 UPDATED_BY_NAME      varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_PAYER_PLAN PRIMARY KEY ( PAYER_PLAN_KEY ),
 CONSTRAINT UK_DIM_PAYER_PLAN_BK_EFF UNIQUE ( EFFECTIVE_START_DATE, PAYER_PLAN_ID )
)
COMMENT = 'Payer and insurance plan dimension with SCD2 tracking.';
