-- ************************************ SqlDBM: Snowflake ***********************************
-- * Generated by SqlDBM: Sample/Sample Project: Healthcare by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.FACT_DIAGNOSIS
CREATE TABLE ANALYTICS.FACT_DIAGNOSIS
(
 DIAGNOSIS_FACT_KEY        number(38,0) NOT NULL COMMENT 'Surrogate key for diagnosis fact row',
 ENCOUNTER_KEY             number(38,0) COMMENT 'Encounter surrogate key reference value (no FK constraint)',
 PATIENT_KEY               number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 DIAGNOSIS_CODE            varchar(20) NOT NULL COMMENT 'Diagnosis code assigned to the patient',
 DIAGNOSIS_DATE_KEY        number(8,0) COMMENT 'Date key when diagnosis was recorded',
 DIAGNOSIS_SEQUENCE        number(3,0) COMMENT 'Sequence number, for example 1 = primary diagnosis',
 PRESENT_ON_ADMISSION_FLAG boolean COMMENT 'Flag indicating present on admission when applicable',
 CREATED_TIMESTAMP         timestamp NOT NULL,
 CREATED_BY_NAME           varchar(50) NOT NULL,
 UPDATED_TIMESTAMP         timestamp NOT NULL,
 UPDATED_BY_NAME           varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_DIAGNOSIS PRIMARY KEY ( DIAGNOSIS_FACT_KEY ),
 CONSTRAINT fk_FACT_DIAGNOSIS_DIM_DATE FOREIGN KEY ( DIAGNOSIS_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_DIAGNOSIS_DIM_PATIENT FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY )
)
CLUSTER BY ( DIAGNOSIS_DATE_KEY, PATIENT_KEY )
COMMENT = 'Diagnosis fact table, one row per diagnosis per patient and encounter.';
