-- ************************************ SqlDBM: Snowflake ***********************************
-- * Generated by SqlDBM: Sample/Sample Project: Healthcare by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.REF_LAB_TEST
CREATE TABLE ANALYTICS.REF_LAB_TEST
(
 LAB_TEST_CODE       varchar(50) NOT NULL COMMENT 'Lab test code, for example LOINC code',
 LAB_TEST_NAME       varchar(255) NOT NULL COMMENT 'Display name for the lab test',
 RESULT_UNIT_DEFAULT varchar(50) COMMENT 'Default unit of measure for this test',
 CATEGORY            varchar(100) COMMENT 'Category, for example Chemistry, Hematology',
 IS_ACTIVE           boolean NOT NULL DEFAULT TRUE COMMENT 'Indicates if the lab test code is active',
 CREATED_TIMESTAMP   timestamp NOT NULL,
 CREATED_BY_NAME     varchar(50) NOT NULL,
 UPDATED_TIMESTAMP   timestamp NOT NULL,
 UPDATED_BY_NAME     varchar(50) NOT NULL,

 CONSTRAINT pk_REF_LAB_TEST PRIMARY KEY ( LAB_TEST_CODE )
)
COMMENT = 'Reference table for lab test codes, such as LOINC.';
