-- ************************************************** SqlDBM: Snowflake **************************************************
-- * Generated by SqlDBM: Healthcare Sample Project  [from PROD] - 12/1/2025 10:47:29 PM by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.FACT_ENCOUNTER
CREATE TABLE ANALYTICS.FACT_ENCOUNTER
(
 ENCOUNTER_KEY          number(38,0) NOT NULL COMMENT 'Surrogate key for the encounter fact row',
 ENCOUNTER_ID           varchar(50) NOT NULL COMMENT 'Encounter identifier from source system',
 PATIENT_KEY            number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 PROVIDER_KEY           number(38,0) COMMENT 'Attending or rendering provider',
 FACILITY_KEY           number(38,0) COMMENT 'Facility where encounter occurred',
 DEPARTMENT_KEY         number(38,0) COMMENT 'Department responsible for the encounter',
 LOCATION_KEY           number(38,0) COMMENT 'Location where encounter took place',
 ADMIT_DATE_KEY         number(8,0) COMMENT 'Date key when patient was admitted',
 DISCHARGE_DATE_KEY     number(8,0) COMMENT 'Date key when patient was discharged',
 PAYER_PLAN_KEY         number(38,0) COMMENT 'Payer plan at time of encounter',
 INSURANCE_COVERAGE_KEY number(38,0) COMMENT 'Insurance coverage record at time of encounter',
 ENCOUNTER_TYPE         varchar(100) COMMENT 'Encounter type, for example Inpatient, Outpatient, Emergency',
 ENCOUNTER_CLASS        varchar(100) COMMENT 'Additional classification of encounter',
 LENGTH_OF_STAY_DAYS    number(5,2) COMMENT 'Length of stay in days',
 TOTAL_CHARGES_AMOUNT   number(18,2) COMMENT 'Total charges associated with the encounter',
 TOTAL_PAYMENTS_AMOUNT  number(18,2) COMMENT 'Total payments applied to the encounter',
 READMISSION_FLAG       boolean COMMENT 'Indicates if this encounter is a readmission within policy window',
 CREATED_TIMESTAMP      timestamp NOT NULL,
 CREATED_BY_NAME        varchar(50) NOT NULL,
 UPDATED_TIMESTAMP      timestamp NOT NULL,
 UPDATED_BY_NAME        varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_ENCOUNTER PRIMARY KEY ( ENCOUNTER_KEY ),
 CONSTRAINT UK_FACT_ENCOUNTER_BK UNIQUE ( ENCOUNTER_ID ),
 CONSTRAINT fk_FACT_ENCOUNTER_DIM_DATE FOREIGN KEY ( ADMIT_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_ENCOUNTER_DIM_PATIENT FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY )
)
CLUSTER BY ( PATIENT_KEY, ADMIT_DATE_KEY )
COMMENT = 'Encounter fact table, one row per patient encounter.';
