-- ************************************************** SqlDBM: Snowflake **************************************************
-- * Generated by SqlDBM: Healthcare Sample Project  [from PROD] - 12/1/2025 10:47:29 PM by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.DIM_LOCATION
CREATE TABLE ANALYTICS.DIM_LOCATION
(
 LOCATION_KEY      number(38,0) NOT NULL COMMENT 'Surrogate key for the location dimension',
 LOCATION_ID       varchar(50) NOT NULL COMMENT 'Location identifier from source system',
 LOCATION_NAME     varchar(255) NOT NULL COMMENT 'Location name, for example Nursing unit, Room',
 LOCATION_TYPE     varchar(100) COMMENT 'Location type, for example Nursing unit, Bed, Clinic room',
 CREATED_TIMESTAMP timestamp NOT NULL,
 CREATED_BY_NAME   varchar(50) NOT NULL,
 UPDATED_TIMESTAMP timestamp NOT NULL,
 UPDATED_BY_NAME   varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_LOCATION PRIMARY KEY ( LOCATION_KEY ),
 CONSTRAINT UK_DIM_LOCATION_BK UNIQUE ( LOCATION_ID )
)
COMMENT = 'Location dimension representing nursing units, rooms, and other physical locations.';
