-- ************************************************** SqlDBM: Snowflake **************************************************
-- * Generated by SqlDBM: Healthcare Sample Project  [from PROD] - 12/1/2025 10:47:29 PM by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.DIM_FACILITY
CREATE TABLE ANALYTICS.DIM_FACILITY
(
 FACILITY_KEY         number(38,0) NOT NULL COMMENT 'Surrogate key for the facility dimension',
 FACILITY_ID          varchar(50) NOT NULL COMMENT 'Natural identifier for the facility from source system',
 EFFECTIVE_START_DATE date NOT NULL COMMENT 'Start date for this version of the facility record',
 EFFECTIVE_END_DATE   date COMMENT 'End date for this version of the facility record',
 IS_CURRENT           boolean NOT NULL DEFAULT TRUE COMMENT 'Indicates if this is the current facility row',
 FACILITY_NAME        varchar(255) NOT NULL COMMENT 'Facility name, for example Hospital or Clinic name',
 FACILITY_TYPE        varchar(100) COMMENT 'Type, for example Hospital, Clinic, ASC',
 ADDRESS_LINE_1       varchar(255) COMMENT 'Facility address line 1',
 ADDRESS_LINE_2       varchar(255) COMMENT 'Facility address line 2',
 CITY                 varchar(100) COMMENT 'Facility city',
 STATE_PROVINCE       varchar(50) COMMENT 'Facility state or province',
 POSTAL_CODE          varchar(20) COMMENT 'Facility postal or ZIP code',
 COUNTRY              varchar(100) COMMENT 'Facility country',
 REGION               varchar(100) COMMENT 'Region or market assignment',
 ACTIVE_FLAG          boolean COMMENT 'Indicates if facility is active',
 CREATED_TIMESTAMP    timestamp NOT NULL,
 CREATED_BY_NAME      varchar(50) NOT NULL,
 UPDATED_TIMESTAMP    timestamp NOT NULL,
 UPDATED_BY_NAME      varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_FACILITY PRIMARY KEY ( FACILITY_KEY ),
 CONSTRAINT UK_DIM_FACILITY_BK_EFF UNIQUE ( FACILITY_ID, EFFECTIVE_START_DATE )
)
COMMENT = 'Facility dimension with SCD2 tracking, representing hospitals, clinics, and other sites.';
