-- ************************************************** SqlDBM: Snowflake **************************************************
-- * Generated by SqlDBM: Healthcare Sample Project  [from PROD] - 12/1/2025 10:47:29 PM by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.DIM_DEPARTMENT
CREATE TABLE ANALYTICS.DIM_DEPARTMENT
(
 DEPARTMENT_KEY    number(38,0) NOT NULL COMMENT 'Surrogate key for the department dimension',
 DEPARTMENT_ID     varchar(50) NOT NULL COMMENT 'Department identifier from source system',
 DEPARTMENT_NAME   varchar(255) NOT NULL COMMENT 'Name of the department',
 DEPARTMENT_TYPE   varchar(100) COMMENT 'Type, for example Emergency, Inpatient, Outpatient, Radiology',
 SERVICE_LINE      varchar(100) COMMENT 'Clinical service line classification',
 CREATED_TIMESTAMP timestamp NOT NULL,
 CREATED_BY_NAME   varchar(50) NOT NULL,
 UPDATED_TIMESTAMP timestamp NOT NULL,
 UPDATED_BY_NAME   varchar(50) NOT NULL,

 CONSTRAINT pk_DIM_DEPARTMENT PRIMARY KEY ( DEPARTMENT_KEY ),
 CONSTRAINT UK_DIM_DEPARTMENT_BK UNIQUE ( DEPARTMENT_ID )
)
COMMENT = 'Department dimension representing clinical and operational departments.';
