-- ************************************************** SqlDBM: Snowflake **************************************************
-- * Generated by SqlDBM: Healthcare Sample Project  [from PROD] - 12/1/2025 10:47:29 PM by heather.ready+yew@sqldbm.com *

-- ************************************** ANALYTICS.FACT_MEDICATION_ORDER
CREATE TABLE ANALYTICS.FACT_MEDICATION_ORDER
(
 MEDICATION_ORDER_KEY number(38,0) NOT NULL COMMENT 'Surrogate key for medication order fact row',
 ENCOUNTER_KEY        number(38,0) COMMENT 'Encounter surrogate key reference value (no FK constraint)',
 PATIENT_KEY          number(38,0) NOT NULL COMMENT 'Link to patient dimension',
 PROVIDER_KEY         number(38,0) COMMENT 'Ordering provider',
 MEDICATION_KEY       number(38,0) NOT NULL COMMENT 'Link to medication dimension',
 ORDER_DATE_KEY       number(8,0) COMMENT 'Date key when order was placed',
 START_DATE_KEY       number(8,0) COMMENT 'Date key when therapy started',
 END_DATE_KEY         number(8,0) COMMENT 'Date key when therapy ended or order was completed',
 ORDER_STATUS         varchar(50) COMMENT 'Status of the order, for example Ordered, Active, Completed, Canceled',
 ORDERING_ROUTE       varchar(100) COMMENT 'Route of administration as ordered',
 ORDERED_DOSE         number(18,4) COMMENT 'Ordered dose amount',
 ORDERED_DOSE_UNIT    varchar(50) COMMENT 'Unit for ordered dose',
 FREQUENCY_TEXT       varchar(100) COMMENT 'Frequency instructions text',
 CREATED_TIMESTAMP    timestamp NOT NULL,
 CREATED_BY_NAME      varchar(50) NOT NULL,
 UPDATED_TIMESTAMP    timestamp NOT NULL,
 UPDATED_BY_NAME      varchar(50) NOT NULL,

 CONSTRAINT pk_FACT_MEDICATION_ORDER PRIMARY KEY ( MEDICATION_ORDER_KEY ),
 CONSTRAINT fk_FACT_MEDICATION_ORDER_DIM_DATE FOREIGN KEY ( END_DATE_KEY ) REFERENCES ANALYTICS.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_MEDICATION_ORDER_DIM_MEDICATION FOREIGN KEY ( MEDICATION_KEY ) REFERENCES ANALYTICS.DIM_MEDICATION ( MEDICATION_KEY ),
 CONSTRAINT fk_FACT_MEDICATION_ORDER_DIM_PATIENT FOREIGN KEY ( PATIENT_KEY ) REFERENCES ANALYTICS.DIM_PATIENT ( PATIENT_KEY ),
 CONSTRAINT fk_FACT_MEDICATION_ORDER_DIM_PROVIDER FOREIGN KEY ( PROVIDER_KEY ) REFERENCES ANALYTICS.DIM_PROVIDER ( PROVIDER_KEY )
)
CLUSTER BY ( PATIENT_KEY, ORDER_DATE_KEY )
COMMENT = 'Medication order fact table, one row per medication order.';
