-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dynamic Tables Snowflake by heather.ready+yew@sqldbm.com *

-- ************************************** BRONZE.RAW_ORDERS_T
CREATE TABLE BRONZE.RAW_ORDERS_T
(
 ORDER_ID        number(38,0),
 CUS_ID          number(38,0),
 ORDER_AMOUNT    number(10,2),
 ORDER_TIMESTAMP timestamp_ntz(9)
);
