-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dynamic Tables Snowflake by heather.ready+yew@sqldbm.com *

-- ************************************** BRONZE.RAW_SALES_T
CREATE TABLE BRONZE.RAW_SALES_T
(
 SALES_ID        number(38,0),
 CUS_ID          number(38,0),
 PRODUCT_ID      number(38,0),
 STORE_ID        number(38,0),
 SALES_REP_ID    number(38,0),
 SALES_AMOUNT    number(10,2),
 SALES_TIMESTAMP timestamp_ntz(9)
);
