-- ***************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Automotive EDW Demo by heather.ready+yew@sqldbm.com *

-- ************************************** CORE.DIM_LOCATION
CREATE TABLE CORE.DIM_LOCATION
(
 LOCATION_SK       number,
 LOCATION_NK       varchar,
 COUNTRY           varchar,
 STATE_PROVINCE    varchar,
 CITY              varchar,
 POSTAL_CODE       varchar,
 LATITUDE          number(9,6),
 LONGITUDE         number(9,6),
 MARKET_AREA       varchar,
 CREATED_TS        timestamp_tz DEFAULT CURRENT_TIMESTAMP(),
 UPDATED_TS        timestamp_tz,
 EFFECTIVE_FROM_TS timestamp_tz,
 EFFECTIVE_TO_TS   timestamp_tz,
 IS_CURRENT        boolean
);
