-- ***************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Automotive EDW Demo by heather.ready+yew@sqldbm.com *

-- ************************************** "CORE"."FACT_AD_METRICS"
CREATE OR REPLACE TABLE "CORE"."FACT_AD_METRICS"
(
 "EVENT_TS"    timestamp_tz,
 "CAMPAIGN_ID" varchar,
 "DEALER_SK"   number,
 "LISTING_SK"  number,
 "IMPRESSIONS" number,
 "CLICKS"      number,
 "SPEND_USD"   number(12,2)
);
