-- ***************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Automotive EDW Demo by heather.ready+yew@sqldbm.com *

-- ************************************** CORE.DIM_USER
CREATE TABLE CORE.DIM_USER
(
 USER_SK           number,
 USER_NK           varchar,
 USER_TYPE         varchar,
 MARKETING_OPT_IN  boolean,
 CREATED_TS        timestamp_tz DEFAULT CURRENT_TIMESTAMP(),
 UPDATED_TS        timestamp_tz,
 EFFECTIVE_FROM_TS timestamp_tz,
 EFFECTIVE_TO_TS   timestamp_tz,
 IS_CURRENT        boolean
);
