-- ***************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Automotive EDW Demo by heather.ready+yew@sqldbm.com *

-- ************************************** CORE.DIM_DATE
CREATE TABLE CORE.DIM_DATE
(
 DATE_SK      number,
 CAL_DATE     date,
 YEAR         number,
 QUARTER      number,
 MONTH        number,
 DAY          number,
 DOW          number,
 WEEK_OF_YEAR number,
 IS_WEEKEND   boolean
);
