-- ***************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Automotive EDW Demo by heather.ready+yew@sqldbm.com *

-- ************************************** CORE.FACT_DEALER_BILLING
CREATE TABLE CORE.FACT_DEALER_BILLING
(
 BILLING_ID           varchar,
 BILLING_PERIOD_START date,
 BILLING_PERIOD_END   date,
 DEALER_SK            number,
 PLAN_NAME            varchar,
 SEAT_COUNT           number,
 BASE_FEE_USD         number(12,2),
 OVERAGE_USD          number(12,2),
 TAX_USD              number(12,2),
 TOTAL_USD            number(12,2),
 INVOICE_TS           timestamp_tz,
 PAID_TS              timestamp_tz
);
