-- ***************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Automotive EDW Demo by heather.ready+yew@sqldbm.com *

-- ************************************** CORE.DIM_VEHICLE
CREATE TABLE CORE.DIM_VEHICLE
(
 VEHICLE_SK        number,
 VEHICLE_NK        varchar,
 MAKE              varchar,
 MODEL             varchar,
 TRIM              varchar,
 MODEL_YEAR        number(4),
 BODY_STYLE        varchar,
 DRIVETRAIN        varchar,
 FUEL_TYPE         varchar,
 TRANSMISSION      varchar,
 DOORS             number,
 CREATED_TS        timestamp_tz DEFAULT CURRENT_TIMESTAMP(),
 UPDATED_TS        timestamp_tz,
 EFFECTIVE_FROM_TS timestamp_tz,
 EFFECTIVE_TO_TS   timestamp_tz,
 IS_CURRENT        boolean
);
