-- ***************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Automotive EDW Demo by heather.ready+yew@sqldbm.com *

-- ************************************** CORE.FACT_LISTING_DAILY
CREATE TABLE CORE.FACT_LISTING_DAILY
(
 DATE_SK        number NOT NULL,
 LISTING_SK     number NOT NULL,
 VEHICLE_SK     number NOT NULL,
 DEALER_SK      number NOT NULL,
 LOCATION_SK    number NOT NULL,
 ASKING_PRICE   number(12,2),
 MILEAGE        number,
 DAYS_ON_SITE   number,
 LISTING_STATUS varchar,

 CONSTRAINT PK_1 PRIMARY KEY ( DATE_SK, LISTING_SK, VEHICLE_SK, DEALER_SK, LOCATION_SK )
);
