-- ***************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Automotive EDW Demo by heather.ready+yew@sqldbm.com *

-- ************************************** CORE.DIM_DEALER
CREATE TABLE CORE.DIM_DEALER
(
 DEALER_SK         number NOT NULL,
 DEALER_NK         varchar,
 DEALER_NAME       varchar,
 DEALER_TIER       varchar,
 PHONE             varchar,
 EMAIL             varchar,
 WEBSITE_URL       varchar,
 CREATED_TS        timestamp_tz DEFAULT CURRENT_TIMESTAMP(),
 UPDATED_TS        timestamp_tz,
 EFFECTIVE_FROM_TS timestamp_tz,
 EFFECTIVE_TO_TS   timestamp_tz,
 IS_CURRENT        boolean,

 CONSTRAINT PK_1 PRIMARY KEY ( DEALER_SK )
);
