-- ***************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Automotive EDW Demo by heather.ready+yew@sqldbm.com *

-- ************************************** CORE.DIM_LISTING
CREATE TABLE CORE.DIM_LISTING
(
 LISTING_SK        number,
 LISTING_NK        varchar,
 VEHICLE_SK        number,
 DEALER_SK         number,
 LOCATION_SK       number,
 LISTING_STATUS    varchar,
 MILEAGE           number,
 ASKING_PRICE      number(12,2),
 PRICE_CURRENCY    varchar(3),
 CPO_FLAG          boolean,
 CREATED_TS        timestamp_tz DEFAULT CURRENT_TIMESTAMP(),
 UPDATED_TS        timestamp_tz,
 EFFECTIVE_FROM_TS timestamp_tz,
 EFFECTIVE_TO_TS   timestamp_tz,
 IS_CURRENT        boolean
);
