-- ***************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Automotive EDW Demo by heather.ready+yew@sqldbm.com *

-- ************************************** CORE.FACT_LEAD
CREATE TABLE CORE.FACT_LEAD
(
 LEAD_ID           varchar,
 LEAD_CREATED_TS   timestamp_tz,
 USER_SK           number,
 LISTING_SK        number,
 DEALER_SK         number,
 LEAD_TYPE         varchar,
 LEAD_STATUS       varchar,
 RESPONSE_TIME_SEC number,
 CLOSE_TS          timestamp_tz,
 REVENUE_USD       number(12,2)
);
