-- ***************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: Automotive EDW Demo by heather.ready+yew@sqldbm.com *

-- ************************************** CORE.FACT_USER_EVENT
CREATE TABLE CORE.FACT_USER_EVENT
(
 EVENT_TS        timestamp_tz NOT NULL,
 USER_SK         number NOT NULL,
 SESSION_ID      varchar NOT NULL,
 LISTING_SK      number NOT NULL,
 VEHICLE_SK      number NOT NULL,
 EVENT_TYPE      varchar,
 DEALER_SK       number,
 LOCATION_SK     number,
 SOURCE_CHANNEL  varchar,
 REFERER_DOMAIN  varchar,
 DEVICE_CATEGORY varchar,
 AB_TEST_BUCKET  varchar,

 CONSTRAINT PK_1 PRIMARY KEY ( EVENT_TS, USER_SK, SESSION_ID, LISTING_SK, VEHICLE_SK )
);
