-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Jira Project - Sample by heather.ready+yew@sqldbm.com *

-- ************************************** dim_product
CREATE TABLE dim_product
(

);
