-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Jira Project - Sample by heather.ready+yew@sqldbm.com *

-- ************************************** dim_time
CREATE TABLE dim_time
(

);
