-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Jira Project - Sample by heather.ready+yew@sqldbm.com *

-- ************************************** dim_store
CREATE TABLE dim_store
(

);
