-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Jira Project - Sample by heather.ready+yew@sqldbm.com *

-- ************************************** dim_employee
CREATE TABLE dim_employee
(
 emp_key  NOT NULL,
 fname   string NOT NULL COMMENT 'Example Description.',
 lname   string NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( emp_key )
);
