-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Jira Project - Sample by heather.ready+yew@sqldbm.com *

-- ************************************** dim_customer
CREATE TABLE dim_customer
(

);
