-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Jira Project - Sample by heather.ready+yew@sqldbm.com *

-- ************************************** fact_sales
CREATE TABLE fact_sales
(
 emp_key  NOT NULL,

 CONSTRAINT FK_6 FOREIGN KEY ( emp_key ) REFERENCES dim_employee ( emp_key )
);
