-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dynamic Tables Snowflake by heather.ready+yew@sqldbm.com *

-- ************************************** GOLD.DIM_DATE_T
CREATE TABLE GOLD.DIM_DATE_T
(
 DATE_SK        number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 DATE_VALUE     date,
 YEAR           number(38,0),
 QUARTER        number(38,0),
 MONTH          number(38,0),
 DAY            number(38,0),
 WEEKDAY        varchar(16777216),
 EFF_START_DATE date NOT NULL,
 EFF_END_DATE   date NOT NULL,
 IS_CURRENT     boolean NOT NULL,

 CONSTRAINT PK_DIM_DATE PRIMARY KEY ( DATE_SK )
);
