-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dynamic Tables Snowflake by heather.ready+yew@sqldbm.com *

-- ************************************** GOLD.DIM_CUSTOMER_T
CREATE TABLE GOLD.DIM_CUSTOMER_T
(
 CUSTOMER_SK    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Surrogate key for the customer dimension. Auto-incremented unique identifier used as the primary key for referential integrity.',
 CUS_ID         number(38,0) COMMENT 'Identifier for a customer record. This column serves as a foreign key or reference to uniquely identify and link customer entities throughout the system.',
 CUSTOMER_NAME  varchar(16777216) COMMENT 'CUSTOMER_NAME - Column for storing the full name of a customer',
 CUSTOMER_EMAIL varchar(16777216) COMMENT 'CUSTOMER_EMAIL',
 DATE_CREATED   timestamp_ntz(9) DEFAULT CURRENT_TIMESTAMP() COMMENT 'A timestamp column that records when the record was created or initially inserted into the database. This field is typically set automatically by the system and should not be manually modified after creation.',
 EFF_START_DATE date NOT NULL COMMENT 'Effective start date for the customer record. Marks the date when this version of the customer record became valid.',
 EFF_END_DATE   date NOT NULL COMMENT 'Effective end date for the customer record. Marks the date when this version of the customer record was superseded by a newer version.',
 IS_CURRENT     boolean NOT NULL COMMENT 'Flag indicating whether this is the current (most recent) version of the customer record. True for active records, False for historical records.',
 LAST_UPDATED   datetime NOT NULL COMMENT 'Timestamp of the last update to this customer record. Tracks when the record was last modified in the system.',

 CONSTRAINT PK_DIM_CUSTOMER PRIMARY KEY ( CUSTOMER_SK )
)
COMMENT = 'Dimension table containing customer master data with slowly changing dimensions (SCD Type 2) tracking. Stores current and historical customer information with effective dating.';
