-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dynamic Tables Snowflake by heather.ready+yew@sqldbm.com *

-- ************************************** GOLD.DIM_STORE_T
CREATE TABLE GOLD.DIM_STORE_T
(
 STORE_SK       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 STORE_ID       number(38,0),
 STORE_NAME     varchar(16777216),
 REGION         varchar(16777216),
 EFF_START_DATE date NOT NULL,
 EFF_END_DATE   date NOT NULL,
 IS_CURRENT     boolean NOT NULL,

 CONSTRAINT PK_DIM_STORE PRIMARY KEY ( STORE_SK )
);
