-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dynamic Tables Snowflake by heather.ready+yew@sqldbm.com *

-- ************************************** GOLD.DIM_PRODUCT_T
CREATE TABLE GOLD.DIM_PRODUCT_T
(
 PRODUCT_SK       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 PRODUCT_ID       number(38,0),
 PRODUCT_NAME     varchar(16777216),
 PRODUCT_CATEGORY varchar(16777216),
 UNIT_PRICE       number(10,2),
 EFF_START_DATE   date NOT NULL,
 EFF_END_DATE     date NOT NULL,
 IS_CURRENT       boolean NOT NULL,

 CONSTRAINT PK_DIM_PRODUCT PRIMARY KEY ( PRODUCT_SK )
);
