-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dynamic Tables Snowflake by heather.ready+yew@sqldbm.com *

-- ************************************** GOLD.DIM_SALES_REP_T
CREATE TABLE GOLD.DIM_SALES_REP_T
(
 SALES_REP_SK   number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 SALES_REP_ID   number(38,0),
 REP_NAME       varchar(16777216),
 REP_EMAIL      varchar(16777216),
 REGION         varchar(16777216),
 EFF_START_DATE date NOT NULL,
 EFF_END_DATE   date NOT NULL,
 IS_CURRENT     boolean NOT NULL,

 CONSTRAINT PK_DIM_SALES_REP PRIMARY KEY ( SALES_REP_SK )
);
