-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dynamic Tables Snowflake by heather.ready+yew@sqldbm.com *

-- ************************************** SILVER.SILVER_STORE_T
CREATE TABLE SILVER.SILVER_STORE_T
(
 STORE_ID         number,
 STORE_NAME       string,
 REGION           string,
 SOURCE_TIMESTAMP timestamp_ntz,
 LOAD_TIMESTAMP   timestamp_ntz DEFAULT CURRENT_TIMESTAMP()
);
