-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dynamic Tables Snowflake by heather.ready+yew@sqldbm.com *

-- ************************************** SILVER.SILVER_SALES_REP_T
CREATE TABLE SILVER.SILVER_SALES_REP_T
(
 SALES_REP_ID     number,
 REP_NAME         string,
 REP_EMAIL        string,
 REGION           string,
 SOURCE_TIMESTAMP timestamp_ntz,
 LOAD_TIMESTAMP   timestamp_ntz DEFAULT CURRENT_TIMESTAMP()
);
