-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dynamic Tables Snowflake by heather.ready+yew@sqldbm.com *

-- ************************************** SILVER.SILVER_CUSTOMER_T
CREATE TABLE SILVER.SILVER_CUSTOMER_T
(
 CUS_ID           number,
 CUSTOMER_NAME    string,
 CUSTOMER_EMAIL   string,
 REGION           string,
 SOURCE_TIMESTAMP timestamp_ntz,
 LOAD_TIMESTAMP   timestamp_ntz DEFAULT CURRENT_TIMESTAMP()
);
