-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dynamic Tables Snowflake by heather.ready+yew@sqldbm.com *

-- ************************************** SILVER.SILVER_DATE_T
CREATE TABLE SILVER.SILVER_DATE_T
(
 DATE_VALUE     date,
 YEAR           number,
 QUARTER        number,
 MONTH          number,
 DAY            number,
 WEEKDAY        string,
 LOAD_TIMESTAMP timestamp_ntz DEFAULT CURRENT_TIMESTAMP()
);
