-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dynamic Tables Snowflake by heather.ready+yew@sqldbm.com *

-- ************************************** SILVER.SILVER_PRODUCT_T
CREATE TABLE SILVER.SILVER_PRODUCT_T
(
 PRODUCT_ID       number,
 PRODUCT_NAME     string,
 PRODUCT_CATEGORY string,
 UNIT_PRICE       number(10,2),
 SOURCE_TIMESTAMP timestamp_ntz,
 LOAD_TIMESTAMP   timestamp_ntz DEFAULT CURRENT_TIMESTAMP()
);
