-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dynamic Tables Snowflake by heather.ready+yew@sqldbm.com *

-- ************************************** SILVER.SILVER_SALES_T
CREATE TABLE SILVER.SILVER_SALES_T
(
 SALES_ID        number,
 CUS_ID          number,
 PRODUCT_ID      number,
 STORE_ID        number,
 SALES_REP_ID    number,
 SALES_AMOUNT    number(10,2),
 SALES_TIMESTAMP timestamp_ntz,
 LOAD_TIMESTAMP  timestamp_ntz DEFAULT CURRENT_TIMESTAMP()
);
