-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.DIM_SHIPPING_METHOD
CREATE TABLE SUPPLYCHAIN.DIM_SHIPPING_METHOD
(
 SHIPPING_METHOD_KEY     number(38,0) NOT NULL COMMENT 'Unique surrogate key for shipping methods',
 SHIPPING_METHOD_ID      varchar(50) NOT NULL COMMENT 'Unique identifier for the shipping method',
 METHOD_NAME             varchar(100) COMMENT 'Descriptive name of the shipping method',
 CARRIER_NAME            varchar(100) COMMENT 'Name of the shipping carrier',
 SHIPPING_TYPE           varchar(50) COMMENT 'Type or category of shipping method',
 ESTIMATED_DELIVERY_DAYS number(3,0) COMMENT 'Expected number of days for delivery',
 BASE_COST               number(12,2) COMMENT 'Base shipping cost for the method',
 DW_CREATED_TS           datetime NOT NULL,
 CREATED_BY              varchar(50) NOT NULL,
 UPDATED_TS              timestamp NOT NULL,
 UPDATED_BY              varchar(50) NOT NULL,
 IS_UPDATED              boolean NOT NULL,

 CONSTRAINT pk_DIM_SHIPPING_METHOD PRIMARY KEY ( SHIPPING_METHOD_KEY )
)
COMMENT = 'Dimension table containing shipping method and carrier information.';
