-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.DIM_CUSTOMER
CREATE TABLE SUPPLYCHAIN.DIM_CUSTOMER
(
 CUSTOMER_KEY      number(38,0) NOT NULL COMMENT 'Unique surrogate key for each customer in the dimension table',
 CUSTOMER_ID       varchar(50) NOT NULL COMMENT 'Unique business identifier for the customer',
 FIRST_NAME        varchar(100) COMMENT 'Customer''s first name',
 LAST_NAME         varchar(100) COMMENT 'Customer''s last name',
 EMAIL             varchar(200) COMMENT 'Customer''s contact email address',
 PHONE             varchar(20) COMMENT 'Customer''s contact phone number',
 ADDRESS           varchar(500) COMMENT 'Customer''s full postal address',
 CITY              varchar(100) COMMENT 'City where the customer is located',
 STATE             varchar(50) COMMENT 'State or province of the customer''s address',
 POSTAL_CODE       varchar(20) COMMENT 'Postal or ZIP code of the customer''s address',
 COUNTRY           varchar(50) COMMENT 'Country of the customer''s residence',
 SEGMENT           varchar(50) COMMENT 'Customer segmentation category or group',
 REGISTRATION_DATE timestamp COMMENT 'Date when the customer first registered',
 DW_CREATED_TS     datetime NOT NULL,
 CREATED_BY        varchar(50) NOT NULL,
 UPDATED_TS        timestamp NOT NULL,
 UPDATED_BY        varchar(50) NOT NULL,
 IS_UPDATED        boolean NOT NULL,
 GEOGRAPHY_HKEY    binary NOT NULL,

 CONSTRAINT pk_DIM_CUSTOMER PRIMARY KEY ( CUSTOMER_KEY ),
 CONSTRAINT fk_DIM_CUSTOMER_DIM_GEOGRAPHY FOREIGN KEY ( GEOGRAPHY_HKEY ) REFERENCES CENTRAL_INFOMART.DIM_GEOGRAPHY ( GEOGRAPHY_HKEY )
)
COMMENT = 'Dimension table storing detailed customer information for customer-related analytics.';
