-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.FACT_INVENTORY
CREATE TABLE SUPPLYCHAIN.FACT_INVENTORY
(
 INVENTORY_KEY                number(38,0) NOT NULL COMMENT 'Unique surrogate key for inventory records',
 PRODUCT_KEY                  number(38,0) COMMENT 'Foreign key linking to the product',
 STORE_KEY                    number(38,0) COMMENT 'Foreign key linking to the store',
 DATE_KEY                     number(38,0) COMMENT 'Foreign key linking to the date of inventory record',
 SUPPLIER_KEY                 number(38,0) COMMENT 'Foreign key linking to the supplier',
 BEGINNING_INVENTORY_QUANTITY number(10,0) COMMENT 'Inventory quantity at the start of the period',
 RECEIVED_QUANTITY            number(10,0) COMMENT 'Number of units received during the period',
 SOLD_QUANTITY                number(10,0) COMMENT 'Number of units sold during the period',
 RETURNED_QUANTITY            number(10,0) COMMENT 'Number of units returned during the period',
 ENDING_INVENTORY_QUANTITY    number(10,0) COMMENT 'Inventory quantity at the end of the period',
 INVENTORY_COST               number(12,2) COMMENT 'Total cost of the inventory',
 INVENTORY_VALUE              number(12,2) COMMENT 'Total monetary value of the inventory',
 DW_CREATED_TS                datetime NOT NULL,
 CREATED_BY                   varchar(50) NOT NULL,
 UPDATED_TS                   timestamp NOT NULL,
 UPDATED_BY                   varchar(50) NOT NULL,
 IS_UPDATED                   boolean NOT NULL,
 STORE_ID                     varchar(50) NOT NULL COMMENT 'Unique business identifier for the store',

 CONSTRAINT pk_FACT_INVENTORY PRIMARY KEY ( INVENTORY_KEY ),
 CONSTRAINT fk_FACT_INVENTORY_DIM_DATE FOREIGN KEY ( DATE_KEY ) REFERENCES SUPPLYCHAIN.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_INVENTORY_DIM_PRODUCT FOREIGN KEY ( PRODUCT_KEY ) REFERENCES SUPPLYCHAIN.DIM_PRODUCT ( PRODUCT_KEY ),
 CONSTRAINT fk_FACT_INVENTORY_DIM_STORE FOREIGN KEY ( STORE_KEY ) REFERENCES SUPPLYCHAIN.DIM_STORE ( STORE_KEY ),
 CONSTRAINT fk_FACT_INVENTORY_DIM_SUPPLIER FOREIGN KEY ( SUPPLIER_KEY ) REFERENCES SUPPLYCHAIN.DIM_SUPPLIER ( SUPPLIER_KEY )
)
COMMENT = 'Fact table tracking inventory levels, movements, and valuation.';
