-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.FACT_PAYMENT
CREATE TABLE SUPPLYCHAIN.FACT_PAYMENT
(
 PAYMENT_KEY        number(38,0) NOT NULL COMMENT 'Unique surrogate key for each payment transaction',
 SALES_ORDER_KEY    number(38,0) COMMENT 'Foreign key linking to the sales order',
 PAYMENT_METHOD_KEY number(38,0) COMMENT 'Foreign key linking to the payment method',
 PAYMENT_DATE_KEY   number(38,0) COMMENT 'Foreign key linking to the date of payment',
 PAYMENT_AMOUNT     number(12,2) COMMENT 'Total amount of the payment',
 PAYMENT_STATUS     varchar(50) COMMENT 'Current status of the payment transaction',
 TRANSACTION_FEE    number(12,2) COMMENT 'Fee associated with the payment transaction',
 DW_CREATED_TS      datetime NOT NULL,
 CREATED_BY         varchar(50) NOT NULL,
 UPDATED_TS         timestamp NOT NULL,
 UPDATED_BY         varchar(50) NOT NULL,
 IS_UPDATED         boolean NOT NULL,
 STORE_KEY          number(38,0) NOT NULL COMMENT 'Unique surrogate key for each store',
 STORE_ID           varchar(50) NOT NULL COMMENT 'Unique business identifier for the store',

 CONSTRAINT pk_FACT_PAYMENT PRIMARY KEY ( PAYMENT_KEY ),
 CONSTRAINT fk_FACT_PAYMENT_DIM_DATE FOREIGN KEY ( PAYMENT_DATE_KEY ) REFERENCES SUPPLYCHAIN.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_PAYMENT_DIM_PAYMENT_METHOD FOREIGN KEY ( PAYMENT_METHOD_KEY ) REFERENCES SUPPLYCHAIN.DIM_PAYMENT_METHOD ( PAYMENT_METHOD_KEY ),
 CONSTRAINT fk_FACT_PAYMENT_DIM_STORE FOREIGN KEY ( STORE_KEY ) REFERENCES SUPPLYCHAIN.DIM_STORE ( STORE_KEY ),
 CONSTRAINT fk_FACT_PAYMENT_FACT_SALES_ORDER FOREIGN KEY ( SALES_ORDER_KEY ) REFERENCES SUPPLYCHAIN.FACT_SALES_ORDER ( SALES_ORDER_KEY )
)
COMMENT = 'Fact table recording detailed payment transactions.';
