-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.DIM_PAYMENT_METHOD
CREATE TABLE SUPPLYCHAIN.DIM_PAYMENT_METHOD
(
 PAYMENT_METHOD_KEY number(38,0) NOT NULL COMMENT 'Unique surrogate key for payment methods',
 PAYMENT_METHOD_ID  varchar(50) NOT NULL COMMENT 'Unique identifier for the payment method',
 METHOD_NAME        varchar(100) COMMENT 'Descriptive name of the payment method',
 METHOD_TYPE        varchar(50) COMMENT 'Type or category of payment method',
 CARD_TYPE          varchar(50) COMMENT 'Specific type of card for card-based payments',
 DW_CREATED_TS      datetime NOT NULL,
 CREATED_BY         varchar(50) NOT NULL,
 UPDATED_TS         timestamp NOT NULL,
 UPDATED_BY         varchar(50) NOT NULL,
 IS_UPDATED         boolean NOT NULL,

 CONSTRAINT pk_DIM_PAYMENT_METHOD PRIMARY KEY ( PAYMENT_METHOD_KEY )
)
COMMENT = 'Dimension table capturing different payment method details.';
