-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.DIM_DATE
CREATE TABLE SUPPLYCHAIN.DIM_DATE
(
 DATE_KEY      number(38,0) NOT NULL COMMENT 'Unique surrogate key for each date',
 FULL_DATE     date COMMENT 'Complete calendar date',
 DAY_OF_WEEK   varchar(20) COMMENT 'Name of the day of the week',
 MONTH_NAME    varchar(20) COMMENT 'Name of the month',
 QUARTER       varchar(10) COMMENT 'Calendar quarter of the year',
 YEAR          number(4) COMMENT 'Four-digit year',
 HOLIDAY_FLAG  boolean COMMENT 'Indicates if the date is a holiday',
 WEEKEND_FLAG  boolean COMMENT 'Indicates if the date is a weekend',
 DW_CREATED_TS datetime NOT NULL,
 CREATED_BY    varchar(50) NOT NULL,
 UPDATED_TS    timestamp NOT NULL,
 UPDATED_BY    varchar(50) NOT NULL,
 IS_UPDATED    boolean NOT NULL,

 CONSTRAINT pk_DIM_DATE PRIMARY KEY ( DATE_KEY )
)
COMMENT = 'Dimension table for date-related information, supporting time-based analysis.';
