-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.DIM_STORE
CREATE TABLE SUPPLYCHAIN.DIM_STORE
(
 STORE_KEY     number(38,0) NOT NULL COMMENT 'Unique surrogate key for each store',
 STORE_ID      varchar(50) NOT NULL COMMENT 'Unique business identifier for the store',
 STORE_NAME    varchar(200) COMMENT 'Name of the retail store',
 LOCATION_TYPE varchar(50) COMMENT 'Type of store location (e.g., flagship, outlet)',
 ADDRESS       varchar(500) COMMENT 'Full postal address of the store',
 CITY          varchar(100) COMMENT 'City where the store is located',
 STATE         varchar(50) COMMENT 'State or province of the store',
 POSTAL_CODE   varchar(20) COMMENT 'Postal or ZIP code of the store',
 COUNTRY       varchar(50) COMMENT 'Country where the store is situated',
 REGION        varchar(50) COMMENT 'Geographic region of the store',
 DW_CREATED_TS datetime NOT NULL,
 CREATED_BY    varchar(50) NOT NULL,
 UPDATED_TS    timestamp NOT NULL,
 UPDATED_BY    varchar(50) NOT NULL,
 IS_UPDATED    boolean NOT NULL,

 CONSTRAINT pk_DIM_STORE PRIMARY KEY ( STORE_KEY )
)
COMMENT = 'Dimension table containing information about retail store locations.';
