-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.DIM_SUPPLIER
CREATE TABLE SUPPLYCHAIN.DIM_SUPPLIER
(
 SUPPLIER_KEY  number(38,0) NOT NULL COMMENT 'Unique surrogate key for each supplier',
 SUPPLIER_ID   varchar(50) NOT NULL COMMENT 'Unique business identifier for the supplier',
 SUPPLIER_NAME varchar(200) COMMENT 'Name of the supplier or vendor',
 CONTACT_NAME  varchar(100) COMMENT 'Name of the primary contact person',
 CONTACT_EMAIL varchar(200) COMMENT 'Contact email for the supplier',
 CONTACT_PHONE varchar(20) COMMENT 'Contact phone number for the supplier',
 ADDRESS       varchar(500) COMMENT 'Full postal address of the supplier',
 CITY          varchar(100) COMMENT 'City where the supplier is located',
 STATE         varchar(50) COMMENT 'State or province of the supplier',
 POSTAL_CODE   varchar(20) COMMENT 'Postal or ZIP code of the supplier',
 COUNTRY       varchar(50) COMMENT 'Country of the supplier',
 SUPPLIER_TYPE varchar(100) COMMENT 'Classification or type of supplier',
 PAYMENT_TERMS varchar(100) COMMENT 'Payment conditions or terms with the supplier',
 DW_CREATED_TS datetime NOT NULL,
 CREATED_BY    varchar(50) NOT NULL,
 UPDATED_TS    timestamp NOT NULL,
 UPDATED_BY    varchar(50) NOT NULL,
 IS_UPDATED    boolean NOT NULL,

 CONSTRAINT pk_DIM_SUPPLIER PRIMARY KEY ( SUPPLIER_KEY )
)
COMMENT = 'Dimension table storing supplier and vendor information.';
