-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.DIM_PRODUCT
CREATE TABLE SUPPLYCHAIN.DIM_PRODUCT
(
 PRODUCT_KEY   number(38,0) NOT NULL COMMENT 'Unique surrogate key for each product',
 PRODUCT_ID    varchar(50) NOT NULL COMMENT 'Unique business identifier for the product',
 PRODUCT_NAME  varchar(200) COMMENT 'Full name or title of the product',
 CATEGORY      varchar(100) COMMENT 'Primary product category',
 SUB_CATEGORY  varchar(100) COMMENT 'More specific product subcategory',
 BRAND         varchar(100) COMMENT 'Manufacturer or brand of the product',
 UNIT_PRICE    number(12,2) COMMENT 'Selling price per unit of the product',
 COST_PRICE    number(12,2) COMMENT 'Cost of producing or acquiring the product',
 SIZE          varchar(50) COMMENT 'Physical size or dimension of the product',
 COLOR         varchar(50) COMMENT 'Color of the product',
 DW_CREATED_TS datetime NOT NULL,
 CREATED_BY    varchar(50) NOT NULL,
 UPDATED_TS    timestamp NOT NULL,
 UPDATED_BY    varchar(50) NOT NULL,
 IS_UPDATED    boolean NOT NULL,

 CONSTRAINT pk_DIM_PRODUCT PRIMARY KEY ( PRODUCT_KEY )
) WITH TAG (SUPPLYCHAIN.PII = 'YES')
COMMENT = 'Dimension table storing detailed product information for product-related analytics.';
