-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.DIM_EMPLOYEE
CREATE TABLE SUPPLYCHAIN.DIM_EMPLOYEE
(
 EMPLOYEE_KEY         number(38,0) NOT NULL COMMENT 'Unique surrogate key for each employee',
 EMPLOYEE_ID          varchar(50) NOT NULL COMMENT 'Unique business identifier for the employee',
 FIRST_NAME           varchar(100) COMMENT 'Employee''s first name',
 LAST_NAME            varchar(100) COMMENT 'Employee''s last name',
 EMAIL                varchar(200) COMMENT 'Employee''s work email address',
 PHONE                varchar(20) COMMENT 'Employee''s work phone number',
 HIRE_DATE            date COMMENT 'Date when the employee was hired',
 DEPARTMENT           varchar(100) COMMENT 'Department where the employee works',
 JOB_TITLE            varchar(100) COMMENT 'Employee''s specific job title',
 MANAGER_EMPLOYEE_KEY number(38,0) COMMENT 'Foreign key to the employee''s manager',
 SALES_TERRITORY      varchar(100) COMMENT 'Sales territory assigned to the employee',
 DW_CREATED_TS        datetime NOT NULL,
 CREATED_BY           varchar(50) NOT NULL,
 UPDATED_TS           timestamp NOT NULL,
 UPDATED_BY           varchar(50) NOT NULL,
 IS_UPDATED           boolean NOT NULL,

 CONSTRAINT pk_DIM_EMPLOYEE PRIMARY KEY ( EMPLOYEE_KEY )
)
COMMENT = 'Dimension table storing detailed employee information.';
