-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Sample Project: Orders to Cash by heather.ready+yew@sqldbm.com *

-- ************************************** SUPPLYCHAIN.FACT_SALES_ORDER
CREATE TABLE SUPPLYCHAIN.FACT_SALES_ORDER
(
 SALES_ORDER_KEY number(38,0) NOT NULL COMMENT 'Unique surrogate key for each sales order',
 ORDER_ID        varchar(50) NOT NULL COMMENT 'Unique business identifier for the sales order',
 CUSTOMER_KEY    number(38,0) COMMENT 'Foreign key linking to the customer',
 PRODUCT_KEY     number(38,0) COMMENT 'Foreign key linking to the product',
 STORE_KEY       number(38,0) COMMENT 'Foreign key linking to the store',
 ORDER_DATE_KEY  number(38,0) COMMENT 'Foreign key linking to the order date',
 QUANTITY        number(10,0) COMMENT 'Number of product units sold in the order',
 UNIT_PRICE      number(12,2) COMMENT 'Price per unit at the time of sale',
 TOTAL_PRICE     number(12,2) COMMENT 'Total monetary value of the order',
 DISCOUNT_AMOUNT number(12,2) COMMENT 'Discount applied to the order',
 TAX_AMOUNT      number(12,2) COMMENT 'Sales tax charged on the order',
 SHIPPING_COST   number(12,2) COMMENT 'Cost of shipping for the order',
 ORDER_STATUS    varchar(50) COMMENT 'Current status of the sales order',
 DW_CREATED_TS   datetime NOT NULL,
 CREATED_BY      varchar(50) NOT NULL,
 UPDATED_TS      timestamp NOT NULL,
 UPDATED_BY      varchar(50) NOT NULL,
 IS_UPDATED      boolean NOT NULL,

 CONSTRAINT pk_FACT_SALES_ORDER PRIMARY KEY ( SALES_ORDER_KEY ),
 CONSTRAINT fk_FACT_SALES_ORDER_DIM_CUSTOMER FOREIGN KEY ( CUSTOMER_KEY ) REFERENCES SUPPLYCHAIN.DIM_CUSTOMER ( CUSTOMER_KEY ),
 CONSTRAINT fk_FACT_SALES_ORDER_DIM_DATE FOREIGN KEY ( ORDER_DATE_KEY ) REFERENCES SUPPLYCHAIN.DIM_DATE ( DATE_KEY ),
 CONSTRAINT fk_FACT_SALES_ORDER_DIM_PRODUCT FOREIGN KEY ( PRODUCT_KEY ) REFERENCES SUPPLYCHAIN.DIM_PRODUCT ( PRODUCT_KEY ),
 CONSTRAINT fk_FACT_SALES_ORDER_DIM_STORE FOREIGN KEY ( STORE_KEY ) REFERENCES SUPPLYCHAIN.DIM_STORE ( STORE_KEY )
)
COMMENT = 'Fact table capturing detailed information about sales orders.';
