-- ************************************ SqlDBM: Databricks ************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer-  by heather.ready+yew@sqldbm.com *

-- ************************************** table_24
CREATE TABLE table_24
(
 pk_test    NOT NULL,
 pk_test_1  NOT NULL,
 CONSTRAINT pk_table_24 PRIMARY KEY (pk_test, pk_test_1)
)
 TBLPROPERTIES (delta.columnMapping.mode = 'name');
