-- ************************************ SqlDBM: Databricks ************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer-  by heather.ready+yew@sqldbm.com *

-- ************************************** table_25
CREATE TABLE table_25
(
 pk_test    NOT NULL,
 pk_test_1  NOT NULL,
 CONSTRAINT fk_table_25_table_24 FOREIGN KEY (pk_test, pk_test_1) REFERENCES table_24 (pk_test, pk_test_1)
)
 TBLPROPERTIES (delta.columnMapping.mode = 'name');
