-- ************************************ SqlDBM: Databricks ************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer-  by heather.ready+yew@sqldbm.com *

-- ************************************** table_26
CREATE TABLE table_26
(
 `<tablename>_id`  bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Surrogate identifier' CONSTRAINT pk_table_26 PRIMARY KEY,
 business_key      string NOT NULL COMMENT 'Natural key from source system',
 created_timestamp timestamp NOT NULL GENERATED ALWAYS AS (current_timestamp()) COMMENT 'When the record was created',
 dw_created_ts     timestamp NOT NULL COMMENT 'When the record was first created',
 created_by        varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts        timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by        varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted        boolean NOT NULL COMMENT 'Logical deletion flag.'
)
 COMMENT 'Modeled via template. Includes ingestion, audit, DQ, and governance metadata.'
 TBLPROPERTIES (delta.columnMapping.mode = 'name');
