-- ************************************ SqlDBM: Databricks ************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer-  by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.dim_customer
CREATE TABLE veh_dm.dim_customer
(
 customer_sk   bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for customer' CONSTRAINT pk_dim_customer PRIMARY KEY,
 customer_code string COMMENT 'Unique customer identifier',
 customer_name string COMMENT 'Full name of customer',
 segment       string COMMENT 'Customer market segment classification',
 country       string COMMENT 'Customer''s country of origin',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'End customers and dealers.';
