-- ************************************ SqlDBM: Databricks ***********************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer  by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.dim_time
CREATE TABLE veh_dm.dim_time
(
 time_key      int NOT NULL COMMENT 'Unique time identifier' CONSTRAINT pk_dim_time PRIMARY KEY,
 hour          int COMMENT 'Hour of the day',
 minute        int COMMENT 'Minute within the hour',
 second        int COMMENT 'Second within the minute',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Time-of-day dimension (optional, for telemetry/service).';
