-- ***************************************** SqlDBM: Databricks *****************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer - team copy by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.dim_model
CREATE TABLE veh_dm.dim_model
(
 model_sk           bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for model' CONSTRAINT pk_dim_model PRIMARY KEY,
 model_code         string COMMENT 'Unique model identifier',
 model_name         string COMMENT 'Descriptive name of the model',
 powertrain         string COMMENT 'Type of powertrain configuration',
 gvwr_class         string COMMENT 'Gross vehicle weight rating classification',
 platform_sk        bigint COMMENT 'Reference to platform family' CONSTRAINT fk_dim_model_dim_platform REFERENCES veh_dm.dim_platform,
 dw_created_ts      timestamp NOT NULL COMMENT 'When the record was first created',
 created_by         varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts         timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by         varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted         boolean NOT NULL COMMENT 'Logical deletion flag.',
 forecast_type_hkey binary NOT NULL CONSTRAINT fk_dim_model_dim_forecast_type REFERENCES sales_infomart.dim_forecast_type
)
USING DELTA
 COMMENT 'Specific models under a platform.';
