-- ***************************************** SqlDBM: Databricks *****************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer - team copy by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.fact_warranty_claim
CREATE TABLE veh_dm.fact_warranty_claim
(
 claim_sk       bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for warranty claim' CONSTRAINT pk_fact_warranty_claim PRIMARY KEY,
 claim_id       string COMMENT 'Unique identifier for warranty claim',
 claim_date_key int COMMENT 'Date of warranty claim',
 vehicle_sk     bigint COMMENT 'Reference to specific vehicle' CONSTRAINT fk_fact_warranty_claim_dim_vehicle REFERENCES veh_dm.dim_vehicle,
 model_sk       bigint COMMENT 'Reference to vehicle model' CONSTRAINT fk_fact_warranty_claim_dim_model REFERENCES veh_dm.dim_model,
 failure_sk     bigint COMMENT 'Reference to failure mode' CONSTRAINT fk_fact_warranty_claim_dim_failure REFERENCES veh_dm.dim_failure,
 claim_status   string COMMENT 'Current status of warranty claim',
 labor_cost     decimal(18, 2) COMMENT 'Labor costs associated with claim',
 parts_cost     decimal(18, 2) COMMENT 'Parts costs associated with claim',
 total_cost     decimal(18, 2) COMMENT 'Total cost of warranty claim',
 dw_created_ts  timestamp NOT NULL COMMENT 'When the record was first created',
 created_by     varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts     timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by     varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted     boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Warranty claims and costs.';
