-- ************************************ SqlDBM: Databricks ************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer-  by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.dim_vehicle
CREATE TABLE veh_dm.dim_vehicle
(
 vehicle_sk     bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for vehicle' CONSTRAINT pk_dim_vehicle PRIMARY KEY,
 serial_no      string COMMENT 'Unique serial number of vehicle',
 model_sk       bigint COMMENT 'Reference to vehicle model',
 plant_sk       bigint COMMENT 'Reference to manufacturing plant',
 customer_sk    bigint COMMENT 'Reference to customer owning vehicle',
 status         string COMMENT 'Current status of vehicle',
 build_date_key int COMMENT 'Date of vehicle manufacture',
 ship_date_key  int COMMENT 'Date of vehicle shipment',
 dw_created_ts  timestamp NOT NULL COMMENT 'When the record was first created',
 created_by     varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts     timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by     varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted     boolean NOT NULL COMMENT 'Logical deletion flag.',
 employee_id    int NOT NULL CONSTRAINT fk_dim_vehicle_EMPLOYEES REFERENCES EMPLOYEES (EMPLOYEE_ID)
)
USING DELTA
 COMMENT 'Serialized finished units for lifecycle analytics.';
