-- ************************************ SqlDBM: Databricks ************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer-  by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.dim_plant
CREATE TABLE veh_dm.dim_plant
(
 plant_sk   bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for plant',
 plant_code string COMMENT 'Unique plant identifier',
 plant_name string COMMENT 'Descriptive name of plant',
 country    string COMMENT 'Country where plant is located',
 tz         string COMMENT 'Timezone of the plant',
 bu_sk      bigint COMMENT 'Reference to business unit'
)
USING DELTA
 COMMENT 'Manufacturing / assembly sites.';
