-- ************************************ SqlDBM: Databricks ***********************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer  by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.dim_part
CREATE TABLE veh_dm.dim_part
(
 part_sk       bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for part' CONSTRAINT pk_dim_part PRIMARY KEY,
 part_number   string COMMENT 'Unique part identifier',
 part_desc     string COMMENT 'Detailed description of part',
 uom           string COMMENT 'Unit of measurement',
 part_type     string COMMENT 'Classification of part type',
 is_serialized boolean COMMENT 'Indicates if part is tracked by serial number',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Parts and assemblies (includes finished goods).';
