-- ************************************ SqlDBM: Databricks ************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer-  by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.dim_failure
CREATE TABLE veh_dm.dim_failure
(
 failure_sk    bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for failure mode' CONSTRAINT pk_dim_failure PRIMARY KEY,
 failure_code  string COMMENT 'Standardized failure identification code',
 failure_desc  string COMMENT 'Detailed description of failure mode',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Optional: normalize warranty/service failure codes.';
