-- ************************************ SqlDBM: Databricks ***********************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer  by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.dim_date
CREATE TABLE veh_dm.dim_date
(
 date_key      int NOT NULL COMMENT 'Unique date identifier' CONSTRAINT pk_dim_date PRIMARY KEY,
 full_date     date COMMENT 'Complete calendar date',
 `year`        int COMMENT 'Year of the date',
 quarter       int COMMENT 'Quarter of the year',
 month         int COMMENT 'Month of the year',
 day_of_month  int COMMENT 'Day within the month',
 day_of_week   int COMMENT 'Day of the week (1-7)',
 week_of_year  int COMMENT 'Week number within the year',
 month_name    string COMMENT 'Full name of the month',
 day_name      string COMMENT 'Full name of the day',
 is_weekend    boolean COMMENT 'Flag indicating if the date is a weekend',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Calendar/date dimension (populate via seed script).';
