-- ************************************ SqlDBM: Databricks ***********************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer  by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.fact_work_order
CREATE TABLE veh_dm.fact_work_order
(
 wo_sk          bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for work order' CONSTRAINT pk_fact_work_order PRIMARY KEY,
 work_order_id  string COMMENT 'Unique identifier for work order',
 start_date_key int COMMENT 'Planned start date of work order',
 due_date_key   int COMMENT 'Planned completion date of work order',
 plant_sk       bigint COMMENT 'Reference to manufacturing plant' CONSTRAINT fk_fact_work_order_dim_plant REFERENCES veh_dm.dim_plant,
 model_sk       bigint COMMENT 'Reference to product model' CONSTRAINT fk_fact_work_order_dim_model REFERENCES veh_dm.dim_model,
 qty_planned    decimal(18, 2) COMMENT 'Planned quantity of units to produce',
 qty_completed  decimal(18, 2) COMMENT 'Actual quantity of units produced',
 status         string COMMENT 'Current status of work order',
 dw_created_ts  timestamp NOT NULL COMMENT 'When the record was first created',
 created_by     varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts     timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by     varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted     boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Production orders by model/plant.';
