-- ************************************ SqlDBM: Databricks ***********************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer  by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.dim_op
CREATE TABLE veh_dm.dim_op
(
 op_sk         bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for operation' CONSTRAINT pk_dim_op PRIMARY KEY,
 op_code       string COMMENT 'Unique operation identifier',
 op_name       string COMMENT 'Descriptive name of the operation',
 work_center   string COMMENT 'Manufacturing work center associated with operation',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Manufacturing operations for routings.';
