-- ***************************************** SqlDBM: Databricks *****************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer - team copy by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.fact_sales_order
CREATE TABLE veh_dm.fact_sales_order
(
 so_line_sk              bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for sales order line' CONSTRAINT pk_fact_sales_order PRIMARY KEY,
 order_number            string COMMENT 'Unique sales order identifier',
 order_line_number       int COMMENT 'Line number within sales order',
 order_date_key          int COMMENT 'Date of sales order creation',
 requested_ship_date_key int COMMENT 'Customer requested shipment date',
 customer_sk             bigint COMMENT 'Reference to customer' CONSTRAINT fk_fact_sales_order_dim_customer REFERENCES veh_dm.dim_customer,
 contract_sk             bigint COMMENT 'Reference to sales contract' CONSTRAINT fk_fact_sales_order_dim_contract REFERENCES veh_dm.dim_contract,
 model_sk                bigint COMMENT 'Reference to product model' CONSTRAINT fk_fact_sales_order_dim_model REFERENCES veh_dm.dim_model,
 qty_ordered             decimal(18, 2) COMMENT 'Quantity of items ordered',
 unit_price              decimal(18, 4) COMMENT 'Price per unit',
 extended_amount         decimal(18, 4) COMMENT 'Total order line amount',
 dw_created_ts           timestamp NOT NULL COMMENT 'When the record was first created',
 created_by              varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts              timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by              varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted              boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Sales order lines (bookings/backlog analysis).';
