-- ************************************ SqlDBM: Databricks ***********************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer  by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.dim_business_unit
CREATE TABLE veh_dm.dim_business_unit
(
 bu_sk   bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Surrogate key for business unit, used as the primary unique identifier.' CONSTRAINT pk_dim_business_unit PRIMARY KEY,
 bu_code string COMMENT 'Unique code representing the business unit.',
 bu_name string COMMENT 'Full name of the business unit.'
)
USING DELTA
 COMMENT 'Business unit (e.g., defense, access, fire & emergency).';
