-- ***************************************** SqlDBM: Databricks *****************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer - team copy by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.dim_supplier
CREATE TABLE veh_dm.dim_supplier
(
 supplier_sk   bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for supplier' CONSTRAINT pk_dim_supplier PRIMARY KEY,
 supplier_code string COMMENT 'Unique supplier identifier',
 supplier_name string COMMENT 'Full name of supplier',
 country       string COMMENT 'Country of supplier origin',
 is_preferred  boolean COMMENT 'Indicates if supplier is preferred vendor',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Suppliers for direct/indirect materials.';
