-- ************************************ SqlDBM: Databricks ************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer-  by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.fact_purchase_order
CREATE TABLE veh_dm.fact_purchase_order
(
 po_line_sk                bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for purchase order line' CONSTRAINT pk_fact_purchase_order PRIMARY KEY,
 po_number                 string COMMENT 'Unique purchase order identifier',
 po_line_number            int COMMENT 'Line number within purchase order',
 order_date_key            int COMMENT 'Date of purchase order creation',
 expected_receipt_date_key int COMMENT 'Planned date of material receipt',
 plant_sk                  bigint COMMENT 'Reference to receiving manufacturing plant',
 supplier_sk               bigint COMMENT 'Reference to supplier' CONSTRAINT fk_fact_purchase_order_dim_supplier REFERENCES veh_dm.dim_supplier,
 part_sk                   bigint COMMENT 'Reference to purchased part' CONSTRAINT fk_fact_purchase_order_dim_part REFERENCES veh_dm.dim_part,
 ordered_qty               decimal(18, 2) COMMENT 'Quantity of parts ordered',
 unit_price                decimal(18, 4) COMMENT 'Price per unit of part',
 received_qty              decimal(18, 2) COMMENT 'Quantity of parts actually received',
 dw_created_ts             timestamp NOT NULL COMMENT 'When the record was first created',
 created_by                varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts                timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by                varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted                boolean NOT NULL COMMENT 'Logical deletion flag.',
 CONSTRAINT fk_fact_purchase_order_dim_plant FOREIGN KEY () REFERENCES veh_dm.dim_plant ()
)
USING DELTA
 COMMENT 'Materials purchasing and receipts.';
