-- ************************************ SqlDBM: Databricks ************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer-  by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.fact_inventory_snapshot
CREATE TABLE veh_dm.fact_inventory_snapshot
(
 inv_snap_sk   bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for inventory snapshot' CONSTRAINT pk_fact_inventory_snapshot PRIMARY KEY,
 date_key      int COMMENT 'Date of inventory snapshot',
 plant_sk      bigint COMMENT 'Reference to manufacturing plant',
 part_sk       bigint COMMENT 'Reference to specific part',
 on_hand_qty   decimal(18, 2) COMMENT 'Current quantity of part in inventory',
 reserved_qty  decimal(18, 2) COMMENT 'Quantity of part reserved for specific purposes',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.',
 CONSTRAINT fk_fact_inventory_snapshot_dim_plant FOREIGN KEY () REFERENCES veh_dm.dim_plant ()
)
USING DELTA
 COMMENT 'Daily inventory snapshot.';
