-- ************************************ SqlDBM: Databricks ***********************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer  by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.dim_contract
CREATE TABLE veh_dm.dim_contract
(
 contract_sk   bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for contract' CONSTRAINT pk_dim_contract PRIMARY KEY,
 contract_code string COMMENT 'Unique identifier for contract',
 contract_type string COMMENT 'Classification of contract',
 incoterms     string COMMENT 'International commercial terms defining shipping responsibilities',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Sales contracts/terms.';
