-- ***************************************** SqlDBM: Databricks *****************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer - team copy by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.fact_service_event
CREATE TABLE veh_dm.fact_service_event
(
 service_sk     bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for service event' CONSTRAINT pk_fact_service_event PRIMARY KEY,
 event_id       string COMMENT 'Unique identifier for service event',
 event_date_key int COMMENT 'Date of service event',
 event_time_key int COMMENT 'Time of service event',
 vehicle_sk     bigint COMMENT 'Reference to specific vehicle' CONSTRAINT fk_fact_service_event_dim_vehicle REFERENCES veh_dm.dim_vehicle,
 model_sk       bigint COMMENT 'Reference to vehicle model' CONSTRAINT fk_fact_service_event_dim_model REFERENCES veh_dm.dim_model,
 customer_sk    bigint COMMENT 'Reference to customer' CONSTRAINT fk_fact_service_event_dim_customer REFERENCES veh_dm.dim_customer,
 event_type_sk  bigint COMMENT 'Reference to event type' CONSTRAINT fk_fact_service_event_dim_event_type REFERENCES veh_dm.dim_event_type,
 labor_minutes  decimal(18, 2) COMMENT 'Labor time spent on service event',
 dw_created_ts  timestamp NOT NULL COMMENT 'When the record was first created',
 created_by     varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts     timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by     varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted     boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Field service activity by vehicle/customer.';
