-- ***************************************** SqlDBM: Databricks *****************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer - team copy by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.fact_op_exec
CREATE TABLE veh_dm.fact_op_exec
(
 op_exec_sk    bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for operation execution' CONSTRAINT pk_fact_op_exec PRIMARY KEY,
 work_order_id string COMMENT 'Identifier for work order',
 date_key      int COMMENT 'Date of operation execution',
 op_sk         bigint COMMENT 'Reference to specific operation' CONSTRAINT fk_fact_op_exec_dim_op REFERENCES veh_dm.dim_op,
 plant_sk      bigint COMMENT 'Reference to manufacturing plant',
 model_sk      bigint COMMENT 'Reference to product model' CONSTRAINT fk_fact_op_exec_dim_model REFERENCES veh_dm.dim_model,
 labor_minutes decimal(18, 2) COMMENT 'Labor time spent on operation',
 yield_qty     decimal(18, 2) COMMENT 'Quantity of successful units produced',
 scrap_qty     decimal(18, 2) COMMENT 'Quantity of units scrapped during operation',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Executed operations for throughput/FPY.';
