-- ***************************************** SqlDBM: Databricks *****************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer - team copy by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.dim_plant
CREATE TABLE veh_dm.dim_plant
(
 plant_sk      bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for plant' CONSTRAINT pk_dim_plant PRIMARY KEY,
 plant_code    string COMMENT 'Unique plant identifier',
 plant_name    string COMMENT 'Descriptive name of plant',
 country       string COMMENT 'Country where plant is located',
 tz            string COMMENT 'Timezone of the plant',
 bu_sk         bigint COMMENT 'Reference to business unit',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Manufacturing / assembly sites.';
