-- ************************************ SqlDBM: Databricks ************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer-  by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.fact_vehicle_telemetry
CREATE TABLE veh_dm.fact_vehicle_telemetry
(
 veh_telem_sk   bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for vehicle telemetry event' CONSTRAINT pk_fact_vehicle_telemetry PRIMARY KEY,
 event_date_key int COMMENT 'Date of telemetry event',
 event_time_key int COMMENT 'Time of telemetry event',
 vehicle_sk     bigint COMMENT 'Reference to specific vehicle',
 model_sk       bigint COMMENT 'Reference to vehicle model',
 latitude       double COMMENT 'Geographical latitude of vehicle',
 longitude      double COMMENT 'Geographical longitude of vehicle',
 odo_km         double COMMENT 'Vehicle odometer reading in kilometers',
 soc_pct        double COMMENT 'State of charge percentage (for electric vehicles)',
 fault_code     string COMMENT 'Vehicle diagnostic fault code',
 dw_created_ts  timestamp NOT NULL COMMENT 'When the record was first created',
 created_by     varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts     timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by     varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted     boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 PARTITIONED BY (event_date_key)
 COMMENT 'High-volume time-series from connected vehicles.';
