-- ************************************ SqlDBM: Databricks ***********************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer  by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.dim_platform
CREATE TABLE veh_dm.dim_platform
(
 platform_sk     bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for platform' CONSTRAINT pk_dim_platform PRIMARY KEY,
 platform_code   string COMMENT 'Unique platform identifier',
 platform_name   string COMMENT 'Descriptive name of platform',
 lifecycle_stage string COMMENT 'Current stage in platform lifecycle',
 bu_sk           bigint COMMENT 'Reference to business unit',
 dw_created_ts   timestamp NOT NULL COMMENT 'When the record was first created',
 created_by      varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts      timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by      varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted      boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Vehicle/equipment platform family.';
