-- ***************************************** SqlDBM: Databricks *****************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer - team copy by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.fact_shipment
CREATE TABLE veh_dm.fact_shipment
(
 shipment_sk   bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for shipment' CONSTRAINT pk_fact_shipment PRIMARY KEY,
 shipment_id   string COMMENT 'Unique identifier for shipment',
 order_number  string COMMENT 'Related sales order number',
 ship_date_key int COMMENT 'Date of shipment',
 plant_sk      bigint COMMENT 'Reference to shipping manufacturing plant',
 customer_sk   bigint COMMENT 'Reference to receiving customer' CONSTRAINT fk_fact_shipment_dim_customer REFERENCES veh_dm.dim_customer,
 model_sk      bigint COMMENT 'Reference to product model' CONSTRAINT fk_fact_shipment_dim_model REFERENCES veh_dm.dim_model,
 shipped_qty   decimal(18, 2) COMMENT 'Quantity of items shipped',
 carrier       string COMMENT 'Shipping carrier name',
 tracking_no   string COMMENT 'Carrier tracking number',
 on_time_flag  int COMMENT 'Indicator of shipment timeliness',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Outbound shipments and OTD metrics.';
