-- ***************************************** SqlDBM: Databricks *****************************************
-- * Generated by SqlDBM: Sample Project: Auto Manufacturer - team copy by heather.ready+yew@sqldbm.com *

-- ************************************** veh_dm.dim_event_type
CREATE TABLE veh_dm.dim_event_type
(
 event_type_sk bigint NOT NULL GENERATED ALWAYS AS IDENTITY COMMENT 'Unique surrogate key for event type' CONSTRAINT pk_dim_event_type PRIMARY KEY,
 event_type    string COMMENT 'Description of event type',
 dw_created_ts timestamp NOT NULL COMMENT 'When the record was first created',
 created_by    varchar(50) NOT NULL COMMENT 'Process or user that created the record.',
 updated_ts    timestamp NOT NULL COMMENT 'When the record was last updated.',
 updated_by    varchar(50) NOT NULL COMMENT 'Process or user that modified the record.',
 is_deleted    boolean NOT NULL COMMENT 'Logical deletion flag.'
)
USING DELTA
 COMMENT 'Optional: normalize service/maintenance event types.';
